codetoanalyze/cpp/performance/list.cpp, list_add_in_loop_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
codetoanalyze/cpp/performance/list.cpp, list_add_in_nested_loop_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Call to list_add_in_loop_constant_FP,Unbounded loop,Loop]
codetoanalyze/cpp/performance/list.cpp, list_get_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
codetoanalyze/cpp/performance/list.cpp, list_push_back_then_loop_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
