codetoanalyze/cpp/performance/loops.cpp, loop_with_complicated_bound_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
codetoanalyze/cpp/performance/unordered_map.cpp, iterate_over_bucket_linear_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
codetoanalyze/cpp/performance/unordered_set.cpp, loop_over_buckets_count_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
