codetoanalyze/cpp/performance/foreachtest.cpp, list_quadratic_FN::lambda_foreachtest.cpp:39:42::operator(), 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded value list->elements.length.ub,Call to loop_linear_list,Loop]
codetoanalyze/cpp/performance/foreachtest.cpp, vector_quadratic_FN::lambda_foreachtest.cpp:45:36::operator(), 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded value vec->elements.length.ub,Call to loop_linear_vec,Loop]
codetoanalyze/cpp/performance/loops.cpp, loop_with_complicated_bound_constant_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
codetoanalyze/cpp/performance/unordered_set.cpp, loop_over_buckets_count_FP, 0, INFINITE_EXECUTION_TIME, no_bucket, ERROR, [Unbounded loop,Loop]
