java_library(
    name = 'compile',
    srcs = glob(['**/*.java']),
    deps = [
        '//dependencies/java/guava:guava',
        '//dependencies/java/jsr-305:jsr-305',
        '//dependencies/java/jackson:jackson',
        '//infer/annotations:annotations',
        '//infer/lib/java/android:android',
        '//infer/models/java:builtins',
    ],
    visibility = [
        'PUBLIC'
    ]
)
