src/a.c, a, 3, DEAD_STORE, no_bucket, ERROR, [Write of unused value (type `int`)]
src/a.c, a, 3, NULLPTR_DEREFERENCE, no_bucket, ERROR, [is assigned to the null pointer,assigned,when calling `a_get` here,parameter `ptr` of a_get,invalid access occurs here]
src/b.c, b, 3, DEAD_STORE, no_bucket, ERROR, [Write of unused value (type `int`)]
src/b.c, b, 3, NULLPTR_DEREFERENCE, no_bucket, ERROR, [is assigned to the null pointer,assigned,when calling `b_get` here,parameter `ptr` of b_get,invalid access occurs here]
