codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionOR1Bad(), 8, NULLPTR_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionOR2Bad(), 8, NULLPTR_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionOR3Bad(), 8, NULLPTR_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionANDBad(), 8, NULLPTR_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionXOR1Bad(), 8, NULLPTR_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullExceptionLogical.cs, Void TestCodeLogical.NullExceptionXOR2Bad(), 8, NULLPTR_DEREFERENCE, no_bucket
