codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionOR1Bad(), 8, NULL_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionOR2Bad(), 8, NULL_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionOR3Bad(), 8, NULL_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionANDBad(), 8, NULL_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionXOR1Bad(), 8, NULL_DEREFERENCE, no_bucket
codetoanalyze/dotnet/logical/NullDerefLogical.cs, Void TestCodeLogical.NullExceptionXOR2Bad(), 8, NULL_DEREFERENCE, no_bucket
