-- erl_hi
build_systems/codetoanalyze/rebar3/erl_hi/src/erl_hi_app.erl, main/0, 2, NO_MATCHING_CASE_CLAUSE, no_bucket, ERROR, [calling context starts here,in call to `maybe_good_matcher/1`,no matching case clause here]
build_systems/codetoanalyze/rebar3/erl_hi/src/erl_hi_app.erl, main/0, 4, NO_MATCHING_CASE_CLAUSE, no_bucket, ERROR, [calling context starts here,in call to `maybe_good_matcher/1`,no matching case clause here]
build_systems/codetoanalyze/rebar3/erl_hi/src/erl_hi_app.erl, main/0, 14, NO_MATCHING_CASE_CLAUSE, no_bucket, ERROR, [calling context starts here,in call to `maybe_good_matcher/1`,no matching case clause here]
