<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }) },
    [
      <#0f3f4d35:
         ({ #d121c0bd: 2, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 3, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 4,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true
          },
          { #c8ff724b: "SEL", #2cdb06fb: [ "SEL" ] },
          5,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true
          },
          { #c8ff724b: "id", #2cdb06fb: [ "id" ] },
          7,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 8,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true
          },
          { #c8ff724b: "Class", #2cdb06fb: [ "Class" ] },
          9,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 10,
            #f9005968: 1,
            #21793419: ({ }, { }),
            #eb8a1f5a: true
          },
          { #c8ff724b: "Protocol", #2cdb06fb: [ "Protocol" ] },
          [],
          { },
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 11, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__NSConstantString",
            #2cdb06fb: [ "__NSConstantString" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 12, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 13, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 14,
            #21793419:
              ({
                 #c3bbce7c: "tests/FoundationStub.h",
                 #c7b317f4: 8,
                 #c68b4ed6: 1
               },
               { #c68b4ed6: 13 }),
            #d3368c8a: true
          },
          { #c8ff724b: "BOOL", #2cdb06fb: [ "BOOL" ] },
          15,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 16,
            #21793419: ({ #c7b317f4: 9, #c68b4ed6: 1 }, { #c68b4ed6: 22 }),
            #d3368c8a: true
          },
          { #c8ff724b: "NSUInteger", #2cdb06fb: [ "NSUInteger" ] },
          17,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 18,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 16, #c68b4ed6: 1 },
               { #c7b317f4: 27, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 19,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 18, #c68b4ed6: 1 }, { #c68b4ed6: 22 }),
                  #1771a8d7: [
                    <#d394bbd3: ({ #d121c0bd: 20, #21793419: ({ }, { }) })>
                  ]
                },
                { #c8ff724b: "alloc", #2cdb06fb: [ "alloc", "NSObject" ] },
                {
                  #137b649c: { #c1127ea9: 21 },
                  #d2e9b40c: "+[NSObject alloc]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 22,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 19, #c68b4ed6: 1 }, { #c68b4ed6: 20 }),
                  #1771a8d7: [
                    <#d394bbd3: ({ #d121c0bd: 23, #21793419: ({ }, { }) })>
                  ]
                },
                { #c8ff724b: "new", #2cdb06fb: [ "new", "NSObject" ] },
                {
                  #137b649c: { #c1127ea9: 21 },
                  #d2e9b40c: "+[NSObject new]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 24,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 20, #c68b4ed6: 1 }, { #c68b4ed6: 28 })
                },
                {
                  #c8ff724b: "autorelease",
                  #2cdb06fb: [ "autorelease", "NSObject" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 21 },
                  #d2e9b40c: "-[NSObject autorelease]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 25,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 21, #c68b4ed6: 1 }, { #c68b4ed6: 21 }),
                  #1771a8d7: [
                    <#d9379b99: ({ #d121c0bd: 26, #21793419: ({ }, { }) })>,
                    <#d394bbd3: ({ #d121c0bd: 27, #21793419: ({ }, { }) })>
                  ]
                },
                { #c8ff724b: "init", #2cdb06fb: [ "init", "NSObject" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 21 },
                  #d2e9b40c: "-[NSObject init]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 28,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 22, #c68b4ed6: 1 }, { #c68b4ed6: 15 })
                },
                { #c8ff724b: "class", #2cdb06fb: [ "class", "NSObject" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 9 },
                  #d2e9b40c: "-[NSObject class]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 29,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 24, #c68b4ed6: 1 }, { #c68b4ed6: 34 })
                },
                {
                  #c8ff724b: "respondsToSelector:",
                  #2cdb06fb: [ "respondsToSelector:", "NSObject" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 15 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 30,
                          #21793419: ({ #c68b4ed6: 29 }, { #c68b4ed6: 33 })
                        },
                        { #c8ff724b: "s", #2cdb06fb: [ "s" ] },
                        { #c1127ea9: 5 },
                        { #0370b1b2: 0 })>
                  ],
                  #d2e9b40c: "-[NSObject respondsToSelector:]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 31,
                  #f9005968: 18,
                  #21793419:
                    ({ #c7b317f4: 25, #c68b4ed6: 1 }, { #c68b4ed6: 41 })
                },
                {
                  #c8ff724b: "conformsToProtocol:",
                  #2cdb06fb: [ "conformsToProtocol:", "NSObject" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 15 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 32,
                          #21793419: ({ #c68b4ed6: 29 }, { #c68b4ed6: 40 })
                        },
                        { #c8ff724b: "p", #2cdb06fb: [ "p" ] },
                        { #c1127ea9: 33 },
                        { #0370b1b2: 0 })>
                  ],
                  #d2e9b40c: "-[NSObject conformsToProtocol:]"
                })>
          ],
          { },
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 34,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 29, #c68b4ed6: 1 },
               { #c7b317f4: 31, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSNumber", #2cdb06fb: [ "NSNumber" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 35,
                  #f9005968: 34,
                  #21793419:
                    ({ #c7b317f4: 30, #c68b4ed6: 1 }, { #c68b4ed6: 37 })
                },
                {
                  #c8ff724b: "numberWithInt:",
                  #2cdb06fb: [ "numberWithInt:", "NSNumber" ]
                },
                {
                  #137b649c: { #c1127ea9: 21 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 36,
                          #21793419: ({ #c68b4ed6: 32 }, { #c68b4ed6: 36 })
                        },
                        { #c8ff724b: "x", #2cdb06fb: [ "x" ] },
                        { #c1127ea9: 37 },
                        { #0370b1b2: 0 })>
                  ],
                  #d2e9b40c: "+[NSNumber numberWithInt:]"
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 38,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 33, #c68b4ed6: 1 },
               { #c7b317f4: 35, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSString", #2cdb06fb: [ "NSString" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 39,
                  #f9005968: 38,
                  #21793419:
                    ({ #c7b317f4: 34, #c68b4ed6: 1 }, { #c68b4ed6: 21 })
                },
                { #c8ff724b: "length", #2cdb06fb: [ "length", "NSString" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 17 },
                  #d2e9b40c: "-[NSString length]"
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 40,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 37, #c68b4ed6: 1 },
               { #c7b317f4: 42, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSDictionary", #2cdb06fb: [ "NSDictionary" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 41,
                  #f9005968: 40,
                  #21793419:
                    ({ #c7b317f4: 38, #c68b4ed6: 1 },
                     { #c7b317f4: 40, #c68b4ed6: 56 })
                },
                {
                  #c8ff724b: "dictionaryWithObjects:forKeys:count:",
                  #2cdb06fb: [
                    "dictionaryWithObjects:forKeys:count:", "NSDictionary"
                  ]
                },
                {
                  #137b649c: { #c1127ea9: 21 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 42,
                          #21793419:
                            ({ #c7b317f4: 38, #c68b4ed6: 46 },
                             { #c68b4ed6: 51 })
                        },
                        { #c8ff724b: "objects", #2cdb06fb: [ "objects" ] },
                        { #c1127ea9: 43 },
                        { #0370b1b2: 0 })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 44,
                          #21793419:
                            ({ #c7b317f4: 39, #c68b4ed6: 46 },
                             { #c68b4ed6: 51 })
                        },
                        { #c8ff724b: "keys", #2cdb06fb: [ "keys" ] },
                        { #c1127ea9: 43 },
                        { #0370b1b2: 1 })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 45,
                          #21793419:
                            ({ #c7b317f4: 40, #c68b4ed6: 40 },
                             { #c68b4ed6: 51 })
                        },
                        { #c8ff724b: "count", #2cdb06fb: [ "count" ] },
                        { #c1127ea9: 17 },
                        { #0370b1b2: 2 })>
                  ],
                  #d2e9b40c:
                    "+[NSDictionary dictionaryWithObjects:forKeys:count:]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 46,
                  #f9005968: 40,
                  #21793419:
                    ({ #c7b317f4: 41, #c68b4ed6: 1 }, { #c68b4ed6: 38 })
                },
                {
                  #c8ff724b: "objectForKeyedSubscript:",
                  #2cdb06fb: [ "objectForKeyedSubscript:", "NSDictionary" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 7 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 47,
                          #21793419: ({ #c68b4ed6: 32 }, { #c68b4ed6: 35 })
                        },
                        { #c8ff724b: "key", #2cdb06fb: [ "key" ] },
                        { #c1127ea9: 7 },
                        { #0370b1b2: 0 })>
                  ],
                  #d2e9b40c: "-[NSDictionary objectForKeyedSubscript:]"
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 48,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 44, #c68b4ed6: 1 },
               { #c7b317f4: 47, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSArray", #2cdb06fb: [ "NSArray" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 49,
                  #f9005968: 48,
                  #21793419:
                    ({ #c7b317f4: 45, #c68b4ed6: 1 }, { #c68b4ed6: 64 })
                },
                {
                  #c8ff724b: "arrayWithObjects:count:",
                  #2cdb06fb: [ "arrayWithObjects:count:", "NSArray" ]
                },
                {
                  #137b649c: { #c1127ea9: 21 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 50,
                          #21793419: ({ #c68b4ed6: 35 }, { #c68b4ed6: 40 })
                        },
                        { #c8ff724b: "objs", #2cdb06fb: [ "objs" ] },
                        { #c1127ea9: 51 },
                        { #0370b1b2: 0 })>,
                    <#fd75cc45:
                       ({
                          #d121c0bd: 52,
                          #21793419: ({ #c68b4ed6: 52 }, { #c68b4ed6: 61 })
                        },
                        { #c8ff724b: "cnt", #2cdb06fb: [ "cnt" ] },
                        { #c1127ea9: 53 },
                        { #0370b1b2: 1 })>
                  ],
                  #d2e9b40c: "+[NSArray arrayWithObjects:count:]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 54,
                  #f9005968: 48,
                  #21793419:
                    ({ #c7b317f4: 46, #c68b4ed6: 1 }, { #c68b4ed6: 49 })
                },
                {
                  #c8ff724b: "objectAtIndexedSubscript:",
                  #2cdb06fb: [ "objectAtIndexedSubscript:", "NSArray" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 7 },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({
                          #d121c0bd: 55,
                          #21793419: ({ #c68b4ed6: 33 }, { #c68b4ed6: 44 })
                        },
                        { #c8ff724b: "index", #2cdb06fb: [ "index" ] },
                        { #c1127ea9: 17 },
                        { #0370b1b2: 0 })>
                  ],
                  #d2e9b40c: "-[NSArray objectAtIndexedSubscript:]"
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#18d25297:
         ({
            #d121c0bd: 56,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 49, #c68b4ed6: 1 },
               { #c7b317f4: 50, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSException", #2cdb06fb: [ "NSException" ] },
          [],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            }
          })>,
      <#f173dfc2:
         ({
            #d121c0bd: 57,
            #21793419: ({ #c7b317f4: 52, #c68b4ed6: 13 }, { #c68b4ed6: 13 }),
            #eb8a1f5a: true,
            #1771a8d7: [
              <#f68c4428:
                 ({
                    #d121c0bd: 58,
                    #21793419: ({ #c68b4ed6: 13 }, { #c68b4ed6: 13 })
                  })>
            ]
          },
          { #c8ff724b: "NSLog", #2cdb06fb: [ "NSLog" ] },
          { #c1127ea9: 59 },
          {
            #ed526254: true,
            #d17ebeaa: [
              <#fd75cc45:
                 ({ #d121c0bd: 60, #21793419: ({ }, { }) },
                  { #c8ff724b: "", #2cdb06fb: [ "" ] },
                  { #c1127ea9: 7 },
                  { #0370b1b2: 0 })>
            ]
          })>,
      <#f173dfc2:
         ({
            #d121c0bd: 61,
            #21793419: ({ #c68b4ed6: 1 }, { #c68b4ed6: 34 }),
            #1771a8d7: [
              <#f68c4428:
                 ({
                    #d121c0bd: 62,
                    #21793419: ({ #c68b4ed6: 13 }, { #c68b4ed6: 13 })
                  })>
            ]
          },
          { #c8ff724b: "NSLog", #2cdb06fb: [ "NSLog" ] },
          { #c1127ea9: 59 },
          {
            #ed526254: true,
            #d17ebeaa: [
              <#fd75cc45:
                 ({
                    #d121c0bd: 63,
                    #21793419: ({ #c68b4ed6: 19 }, { #c68b4ed6: 28 })
                  },
                  { #c8ff724b: "", #2cdb06fb: [ "" ] },
                  { #c1127ea9: 64 },
                  { #0370b1b2: 0 })>
            ]
          })>,
      <#cd6a13bb:
         ({
            #d121c0bd: 65,
            #f9005968: 1,
            #21793419:
              ({
                 #c3bbce7c: "tests/ObjCBridgeTransferTest.m",
                 #c7b317f4: 10,
                 #c68b4ed6: 9
               },
               { #c7b317f4: 11, #c68b4ed6: 1 })
          },
          { #c8ff724b: "ABFDataRef", #2cdb06fb: [ "ABFDataRef" ] },
          66,
          [],
          { },
          <#c5b1f8a9>,
          { #33244202: 65, #1a9a7e84: true })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 67,
            #21793419:
              ({ #c7b317f4: 10, #c68b4ed6: 1 },
               { #c7b317f4: 11, #c68b4ed6: 3 }),
            #d3368c8a: true
          },
          { #c8ff724b: "ABFDataRef", #2cdb06fb: [ "ABFDataRef" ] },
          68,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 69,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 13, #c68b4ed6: 1 },
               { #c7b317f4: 14, #c68b4ed6: 2 })
          },
          { #c8ff724b: "ABFData", #2cdb06fb: [ "ABFData" ] },
          [],
          { },
          { })>,
      <#f173dfc2:
         ({
            #d121c0bd: 70,
            #21793419: ({ #c7b317f4: 16, #c68b4ed6: 1 }, { #c68b4ed6: 27 }),
            #0a16e1f2: true,
            #d3368c8a: true
          },
          { #c8ff724b: "ABFDataCreate", #2cdb06fb: [ "ABFDataCreate" ] },
          { #c1127ea9: 71 },
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 72,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 18, #c68b4ed6: 1 },
               { #c7b317f4: 19, #c68b4ed6: 2 })
          },
          { #c8ff724b: "A", #2cdb06fb: [ "A" ] },
          [],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 18,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            },
            #d32dd232: {
              #c709e154: <#c37c57de>,
              #ec05e4a8: 73,
              #c8ff724b: { #c8ff724b: "A", #2cdb06fb: [ "A" ] }
            }
          })>,
      <#0e281b68:
         ({
            #d121c0bd: 73,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 21, #c68b4ed6: 1 },
               { #c7b317f4: 27, #c68b4ed6: 1 })
          },
          { #c8ff724b: "A", #2cdb06fb: [ "A" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 74,
                  #f9005968: 73,
                  #21793419:
                    ({ #c7b317f4: 23, #c68b4ed6: 1 },
                     { #c7b317f4: 25, #c68b4ed6: 1 })
                },
                {
                  #c8ff724b: "bridge_transfer_example",
                  #2cdb06fb: [ "bridge_transfer_example", "A" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 75 },
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 76,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 77, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 78,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #c11b7aa2:
                    <#d394bb73:
                       ({
                          #d121c0bd: 79,
                          #21793419:
                            ({ #c7b317f4: 23, #c68b4ed6: 33 },
                             { #c7b317f4: 25, #c68b4ed6: 1 })
                        },
                        [
                          <#152ea3f2:
                             ({
                                #d121c0bd: 80,
                                #21793419:
                                  ({ #c7b317f4: 24, #c68b4ed6: 3 },
                                   { #c68b4ed6: 66 })
                              },
                              [
                                <#d0cddcea:
                                   ({
                                      #d121c0bd: 81,
                                      #21793419:
                                        ({ #c68b4ed6: 23 }, { #c68b4ed6: 65 })
                                    },
                                    [
                                      <#c3b129f9:
                                         ({
                                            #d121c0bd: 82,
                                            #21793419:
                                              ({ #c68b4ed6: 23 },
                                               { #c68b4ed6: 65 })
                                          },
                                          [
                                            <#23214b43:
                                               ({
                                                  #d121c0bd: 83,
                                                  #21793419:
                                                    ({ #c68b4ed6: 23 },
                                                     { #c68b4ed6: 65 })
                                                },
                                                [
                                                  <#c59ea513:
                                                     ({
                                                        #d121c0bd: 84,
                                                        #21793419:
                                                          ({ #c68b4ed6: 51 },
                                                           { #c68b4ed6: 65 })
                                                      },
                                                      [
                                                        <#c3b129f9:
                                                           ({
                                                              #d121c0bd: 85,
                                                              #21793419:
                                                                ({
                                                                   #c68b4ed6:
                                                                    51
                                                                 },
                                                                 {
                                                                   #c68b4ed6:
                                                                    51
                                                                 })
                                                            },
                                                            [
                                                              <#e9db58be:
                                                                 ({
                                                                    #d121c0bd:
                                                                    86,
                                                                    #21793419:
                                                                    (
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    },
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    })
                                                                  },
                                                                  [],
                                                                  {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    71
                                                                    }
                                                                  },
                                                                  {
                                                                    #c369ebbe: {
                                                                    #c709e154:
                                                                    <#ee046738>,
                                                                    #ec05e4a8:
                                                                    70,
                                                                    #c8ff724b: {
                                                                    #c8ff724b:
                                                                    "ABFDataCreate",
                                                                    #2cdb06fb: [
                                                                    "ABFDataCreate"
                                                                    ]
                                                                    },
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    71
                                                                    }
                                                                    }
                                                                  })>
                                                            ],
                                                            {
                                                              #30e4876a: {
                                                                #c1127ea9: 87
                                                              }
                                                            },
                                                            {
                                                              #c91e0a14:
                                                                <#210490b0>,
                                                              #fa1a3bd3: []
                                                            })>
                                                      ],
                                                      {
                                                        #30e4876a: {
                                                          #c1127ea9: 88
                                                        }
                                                      })>
                                                ],
                                                {
                                                  #30e4876a: {
                                                    #c1127ea9: 89
                                                  }
                                                },
                                                {
                                                  #c91e0a14: <#eb29e9bb>,
                                                  #fa1a3bd3: []
                                                },
                                                { #c1127ea9: 89 },
                                                { #c91e0a14: <#34cf37c3> })>
                                          ],
                                          { #30e4876a: { #c1127ea9: 89 } },
                                          {
                                            #c91e0a14: <#38332009>,
                                            #fa1a3bd3: []
                                          })>
                                    ],
                                    { #30e4876a: { #c1127ea9: 89 } },
                                    { })>
                              ],
                              [
                                <#11c182d1:
                                   ({
                                      #d121c0bd: 90,
                                      #21793419:
                                        ({ #c68b4ed6: 3 }, { #c68b4ed6: 65 })
                                    },
                                    {
                                      #c8ff724b: "someData",
                                      #2cdb06fb: [ "someData" ]
                                    },
                                    { #c1127ea9: 89 },
                                    {
                                      #fe93c404:
                                        <#d0cddcea:
                                           ({
                                              #d121c0bd: 81,
                                              #21793419:
                                                ({ #c68b4ed6: 23 },
                                                 { #c68b4ed6: 65 })
                                            },
                                            [
                                              <#c3b129f9:
                                                 ({
                                                    #d121c0bd: 82,
                                                    #21793419:
                                                      ({ #c68b4ed6: 23 },
                                                       { #c68b4ed6: 65 })
                                                  },
                                                  [
                                                    <#23214b43:
                                                       ({
                                                          #d121c0bd: 83,
                                                          #21793419:
                                                            ({
                                                               #c68b4ed6: 23
                                                             },
                                                             {
                                                               #c68b4ed6: 65
                                                             })
                                                        },
                                                        [
                                                          <#c59ea513:
                                                             ({
                                                                #d121c0bd: 84,
                                                                #21793419:
                                                                  ({
                                                                    #c68b4ed6:
                                                                    51
                                                                   },
                                                                   {
                                                                    #c68b4ed6:
                                                                    65
                                                                   })
                                                              },
                                                              [
                                                                <#c3b129f9:
                                                                   ({
                                                                    #d121c0bd:
                                                                    85,
                                                                    #21793419:
                                                                    (
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    },
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    })
                                                                    },
                                                                    [
                                                                    <#e9db58be:
                                                                    ({
                                                                    #d121c0bd:
                                                                    86,
                                                                    #21793419:
                                                                    (
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    },
                                                                    {
                                                                    #c68b4ed6:
                                                                    51
                                                                    })
                                                                    },
                                                                    [],
                                                                    {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    71
                                                                    }
                                                                    },
                                                                    {
                                                                    #c369ebbe: {
                                                                    #c709e154:
                                                                    <#ee046738>,
                                                                    #ec05e4a8:
                                                                    70,
                                                                    #c8ff724b: {
                                                                    #c8ff724b:
                                                                    "ABFDataCreate",
                                                                    #2cdb06fb: [
                                                                    "ABFDataCreate"
                                                                    ]
                                                                    },
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    71
                                                                    }
                                                                    }
                                                                    })>
                                                                    ],
                                                                    {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    87
                                                                    }
                                                                    },
                                                                    {
                                                                    #c91e0a14:
                                                                    <#210490b0>,
                                                                    #fa1a3bd3:
                                                                    []
                                                                    })>
                                                              ],
                                                              {
                                                                #30e4876a: {
                                                                  #c1127ea9:
                                                                    88
                                                                }
                                                              })>
                                                        ],
                                                        {
                                                          #30e4876a: {
                                                            #c1127ea9: 89
                                                          }
                                                        },
                                                        {
                                                          #c91e0a14:
                                                            <#eb29e9bb>,
                                                          #fa1a3bd3: []
                                                        },
                                                        { #c1127ea9: 89 },
                                                        {
                                                          #c91e0a14:
                                                            <#34cf37c3>
                                                        })>
                                                  ],
                                                  {
                                                    #30e4876a: {
                                                      #c1127ea9: 89
                                                    }
                                                  },
                                                  {
                                                    #c91e0a14: <#38332009>,
                                                    #fa1a3bd3: []
                                                  })>
                                            ],
                                            { #30e4876a: { #c1127ea9: 89 } },
                                            { })>
                                    })>
                              ])>
                        ])>,
                  #d2e9b40c: "-[A bridge_transfer_example]"
                })>
          ],
          { },
          {
            #2ec29bb2: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 72,
              #c8ff724b: { #c8ff724b: "A", #2cdb06fb: [ "A" ] }
            }
          })>,
      <#0f3f4d35:
         ({ #d121c0bd: 91, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "instancetype", #2cdb06fb: [ "instancetype" ] },
          21,
          { })>
    ],
    { },
    {
      #e870593a: "tests/ObjCBridgeTransferTest.m",
      #e52854e9: <#3ff69d49>,
      #f81dea91: {
        #26452803: 8,
        #c674c89d: 16,
        #3569bf4a: 32,
        #d7cd079d: 64,
        #048ad2a1: 64
      },
      #247f0baa: true,
      #1acb7079: [
        <#22d546dd: ({ #d121c0bd: 75 }, <#392cef74>)>,
        <#22d546dd: ({ #d121c0bd: 92 }, <#2bf4b04a>)>,
        <#22d546dd: ({ #d121c0bd: 93 }, <#ec0a078a>)>,
        <#22d546dd: ({ #d121c0bd: 94 }, <#f6dab0c9>)>,
        <#22d546dd: ({ #d121c0bd: 95 }, <#0f54f45c>)>,
        <#22d546dd: ({ #d121c0bd: 37 }, <#0037c4cf>)>,
        <#22d546dd: ({ #d121c0bd: 96 }, <#3290d19c>)>,
        <#22d546dd: ({ #d121c0bd: 97 }, <#fee0a138>)>,
        <#22d546dd: ({ #d121c0bd: 98 }, <#1da7d9cb>)>,
        <#22d546dd: ({ #d121c0bd: 99 }, <#0baa9fe7>)>,
        <#22d546dd: ({ #d121c0bd: 53 }, <#3866e79a>)>,
        <#22d546dd: ({ #d121c0bd: 100 }, <#23a02071>)>,
        <#22d546dd: ({ #d121c0bd: 101 }, <#09087e8d>)>,
        <#22d546dd: ({ #d121c0bd: 102 }, <#15c4357c>)>,
        <#22d546dd: ({ #d121c0bd: 103 }, <#e75f9f31>)>,
        <#22d546dd: ({ #d121c0bd: 104 }, <#c2f78dcd>)>,
        <#22d546dd: ({ #d121c0bd: 105 }, <#3726ba3b>)>,
        <#22d546dd: ({ #d121c0bd: 106 }, <#3759b761>)>,
        <#22d546dd: ({ #d121c0bd: 107 }, <#ebd317dd>)>,
        <#22d546dd: ({ #d121c0bd: 108 }, <#2ec759b9>)>,
        <#22d546dd: ({ #d121c0bd: 109 }, <#284d329d>)>,
        <#22d546dd: ({ #d121c0bd: 110 }, <#35acb472>)>,
        <#22d546dd: ({ #d121c0bd: 111 }, <#2b1d0544>)>,
        <#22d546dd: ({ #d121c0bd: 112 }, <#0106ffa8>)>,
        <#22d546dd: ({ #d121c0bd: 113 }, <#d6bc9d8a>)>,
        <#22d546dd: ({ #d121c0bd: 114 }, <#19b0df66>)>,
        <#22d546dd: ({ #d121c0bd: 115 }, <#1336b84a>)>,
        <#22d546dd: ({ #d121c0bd: 116 }, <#20963a1f>)>,
        <#22d546dd: ({ #d121c0bd: 117 }, <#16068af1>)>,
        <#22d546dd: ({ #d121c0bd: 118 }, <#ebf08555>)>,
        <#22d546dd: ({ #d121c0bd: 119 }, <#d78ceb63>)>,
        <#22d546dd: ({ #d121c0bd: 120 }, <#dd2a33f3>)>,
        <#22d546dd: ({ #d121c0bd: 121 }, <#ef62b1d7>)>,
        <#22d546dd: ({ #d121c0bd: 122 }, <#0c8bf62c>)>,
        <#22d546dd: ({ #d121c0bd: 123 }, <#13391dca>)>,
        <#22d546dd: ({ #d121c0bd: 124 }, <#ecc0d32e>)>,
        <#22d546dd: ({ #d121c0bd: 125 }, <#c2767110>)>,
        <#22d546dd: ({ #d121c0bd: 126 }, <#c813b9a0>)>,
        <#22d546dd: ({ #d121c0bd: 127 }, <#da4c3784>)>,
        <#22d546dd: ({ #d121c0bd: 128 }, <#f7757bd9>)>,
        <#22d546dd: ({ #d121c0bd: 129 }, <#fe22a377>)>,
        <#22d546dd: ({ #d121c0bd: 130 }, <#d7aa58db>)>,
        <#22d546dd: ({ #d121c0bd: 131 }, <#d2f340c8>)>,
        <#22d546dd: ({ #d121c0bd: 132 }, <#2193aedd>)>,
        <#22d546dd: ({ #d121c0bd: 133 }, <#0dd56321>)>,
        <#22d546dd: ({ #d121c0bd: 134 }, <#d8e10c82>)>,
        <#22d546dd: ({ #d121c0bd: 135 }, <#c4f079df>)>,
        <#22d546dd: ({ #d121c0bd: 136 }, <#1ee7219a>)>,
        <#22d546dd: ({ #d121c0bd: 137 }, <#0d506118>)>,
        <#22d546dd: ({ #d121c0bd: 138 }, <#dec9bcfd>)>,
        <#22d546dd: ({ #d121c0bd: 139 }, <#f1f6e5a2>)>,
        <#22d546dd: ({ #d121c0bd: 140 }, <#d935d0cf>)>,
        <#22d546dd: ({ #d121c0bd: 141 }, <#d35a4eab>)>,
        <#2e6cf4ea: ({ #d121c0bd: 142 })>,
        <#2e6cf4ea: ({ #d121c0bd: 143 })>,
        <#2e6cf4ea: ({ #d121c0bd: 144 })>,
        <#2e6cf4ea: ({ #d121c0bd: 145 })>,
        <#22d546dd: ({ #d121c0bd: 146 }, <#c9ba0f87>)>,
        <#22d546dd: ({ #d121c0bd: 147 }, <#db21580c>)>,
        <#22d546dd: ({ #d121c0bd: 148 }, <#391b1e6e>)>,
        <#d3d219f7: ({ #d121c0bd: 149 }, { #c1127ea9: 75 })>,
        <#22d546dd: ({ #d121c0bd: 150 }, <#ea323187>)>,
        <#22d546dd: ({ #d121c0bd: 151 }, <#2fe155d3>)>,
        <#d3d219f7: ({ #d121c0bd: 152 }, { #c1127ea9: 148 })>,
        <#0098a8c5: ({ #d121c0bd: 153 }, { #fcd148e8: 146 })>,
        <#2e3d736c: ({ #d121c0bd: 154 }, { #c1127ea9: 153 })>,
        <#0098a8c5: ({ #d121c0bd: 155 }, { #fcd148e8: 147 })>,
        <#2e3d736c: ({ #d121c0bd: 156 }, { #c1127ea9: 155 })>,
        <#2374f4e7: ({ #d121c0bd: 157 }, 10)>,
        <#d80cb60b: ({ #d121c0bd: 158 }, 159)>,
        <#d3d219f7: ({ #d121c0bd: 160 }, { #c1127ea9: 37, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 161 }, { #c1127ea9: 93, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 162 }, { #c1127ea9: 93 })>,
        <#d80cb60b: ({ #d121c0bd: 163 }, 164)>,
        <#da0c5ecf:
           ({ #d121c0bd: 165 },
            { #cd26765d: { #c1127ea9: 163 }, #11302019: 24 },
            1)>,
        <#2374f4e7: ({ #d121c0bd: 166 }, 18)>,
        <#19e1ef85:
           ({ #d121c0bd: 7, #26f32be5: 154 },
            { #0b680f7d: { #c1127ea9: 154 }, #c3687459: 6 })>,
        <#19e1ef85:
           ({ #d121c0bd: 21, #26f32be5: 154 },
            { #0b680f7d: { #c1127ea9: 7 }, #c3687459: 91 })>,
        <#19e1ef85:
           ({ #d121c0bd: 9, #26f32be5: 156 },
            { #0b680f7d: { #c1127ea9: 156 }, #c3687459: 8 })>,
        <#19e1ef85:
           ({ #d121c0bd: 15, #26f32be5: 37 },
            { #0b680f7d: { #c1127ea9: 37 }, #c3687459: 14 })>,
        <#19e1ef85:
           ({ #d121c0bd: 5, #26f32be5: 152 },
            { #0b680f7d: { #c1127ea9: 152 }, #c3687459: 4 })>,
        <#2e3d736c: ({ #d121c0bd: 33 }, { #c1127ea9: 157 })>,
        <#2374f4e7: ({ #d121c0bd: 167 }, 34)>,
        <#2374f4e7: ({ #d121c0bd: 168 }, 38)>,
        <#19e1ef85:
           ({ #d121c0bd: 17, #26f32be5: 53 },
            { #0b680f7d: { #c1127ea9: 53 }, #c3687459: 16 })>,
        <#2374f4e7: ({ #d121c0bd: 169 }, 40)>,
        <#cd01b755:
           ({ #d121c0bd: 170 },
            { #cd26765d: { #c1127ea9: 154 }, #11302019: 8 })>,
        <#cd01b755:
           ({ #d121c0bd: 171 },
            { #cd26765d: { #c1127ea9: 7, #ea1a680e: true }, #11302019: 8 })>,
        <#cd01b755:
           ({ #d121c0bd: 172 },
            { #cd26765d: { #c1127ea9: 7, #ea1a680e: true }, #11302019: 8 })>,
        <#d3d219f7: ({ #d121c0bd: 173 }, { #c1127ea9: 154, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 174 }, { #c1127ea9: 7, #ea1a680e: true })>,
        <#2d935553: ({ #d121c0bd: 43, #26f32be5: 174 }, { #c1127ea9: 174 })>,
        <#2374f4e7: ({ #d121c0bd: 175 }, 48)>,
        <#d3d219f7: ({ #d121c0bd: 176 }, { #c1127ea9: 154 })>,
        <#d3d219f7: ({ #d121c0bd: 51 }, { #c1127ea9: 7 })>,
        <#2374f4e7: ({ #d121c0bd: 177 }, 56)>,
        <#2e3d736c: ({ #d121c0bd: 64 }, { #c1127ea9: 168 })>,
        <#26796f6a:
           ({ #d121c0bd: 178 },
            { #f9c96be9: { #c1127ea9: 75 } },
            { #08ec7593: [ { #c1127ea9: 64 } ] })>,
        <#26796f6a:
           ({ #d121c0bd: 179 },
            { #f9c96be9: { #c1127ea9: 75 } },
            { #08ec7593: [ { #c1127ea9: 64 } ] })>,
        <#26796f6a:
           ({ #d121c0bd: 180 },
            { #f9c96be9: { #c1127ea9: 75 } },
            { #08ec7593: [ { #c1127ea9: 154 } ] })>,
        <#26796f6a:
           ({ #d121c0bd: 59 },
            { #f9c96be9: { #c1127ea9: 75 } },
            { #08ec7593: [ { #c1127ea9: 7 } ] })>,
        <#d80cb60b: ({ #d121c0bd: 66 }, 65)>,
        <#263b5f37: ({ #d121c0bd: 181, #26f32be5: 66 })>,
        <#2374f4e7: ({ #d121c0bd: 182 }, 69)>,
        <#19e1ef85:
           ({ #d121c0bd: 68, #26f32be5: 66 },
            { #0b680f7d: { #c1127ea9: 181 }, #c3687459: 67 })>,
        <#d3d219f7: ({ #d121c0bd: 183 }, { #c1127ea9: 66 })>,
        <#d3d219f7: ({ #d121c0bd: 88 }, { #c1127ea9: 68 })>,
        <#01fe18e9: ({ #d121c0bd: 184 }, { #f9c96be9: { #c1127ea9: 183 } })>,
        <#01fe18e9: ({ #d121c0bd: 71 }, { #f9c96be9: { #c1127ea9: 88 } })>,
        <#2374f4e7: ({ #d121c0bd: 185 }, 72)>,
        <#2e3d736c: ({ #d121c0bd: 77 }, { #c1127ea9: 185 })>,
        <#2e3d736c: ({ #d121c0bd: 89 }, { #c1127ea9: 182 })>,
        <#d3d219f7: ({ #d121c0bd: 186 }, { #c1127ea9: 184 })>,
        <#d3d219f7: ({ #d121c0bd: 87 }, { #c1127ea9: 71 })>,
        <#cfc9a9b2: ({ #d121c0bd: 0 })>
      ]
    })>
