<#032016ff:
   ({ #d121c0bd: 1, #21793419: ({ }, { }) },
    [
      <#0f3f4d35:
         ({ #d121c0bd: 2, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "__int128_t", #2cdb06fb: [ "__int128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 3, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "__uint128_t", #2cdb06fb: [ "__uint128_t" ] },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 4, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "SEL", #2cdb06fb: [ "SEL" ] },
          5,
          { })>,
      <#0f3f4d35:
         ({
            #d121c0bd: 6,
            #21793419: ({ }, { }),
            #eb8a1f5a: true,
            #d3368c8a: true
          },
          { #c8ff724b: "id", #2cdb06fb: [ "id" ] },
          7,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 8, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "Class", #2cdb06fb: [ "Class" ] },
          0,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 9,
            #f9005968: 1,
            #21793419: ({ }, { }),
            #eb8a1f5a: true
          },
          { #c8ff724b: "Protocol", #2cdb06fb: [ "Protocol" ] },
          [],
          { },
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 10, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__NSConstantString",
            #2cdb06fb: [ "__NSConstantString" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 11, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__builtin_ms_va_list",
            #2cdb06fb: [ "__builtin_ms_va_list" ]
          },
          0,
          { })>,
      <#0f3f4d35:
         ({ #d121c0bd: 12, #21793419: ({ }, { }), #eb8a1f5a: true },
          {
            #c8ff724b: "__builtin_va_list",
            #2cdb06fb: [ "__builtin_va_list" ]
          },
          0,
          { })>,
      <#18d25297:
         ({
            #d121c0bd: 13,
            #f9005968: 1,
            #21793419:
              ({ #c3bbce7c: "tests/optional.m", #c7b317f4: 8, #c68b4ed6: 1 },
               { #c7b317f4: 9, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [],
          { },
          { })>,
      <#e1b0618e:
         ({
            #d121c0bd: 14,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 11, #c68b4ed6: 1 },
               { #c7b317f4: 12, #c68b4ed6: 2 })
          },
          { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] },
          [],
          { },
          { })>,
      <#e1b0618e:
         ({
            #d121c0bd: 15,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 14, #c68b4ed6: 1 },
               { #c7b317f4: 17, #c68b4ed6: 2 })
          },
          { #c8ff724b: "BarDelegate", #2cdb06fb: [ "BarDelegate" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 16,
                  #f9005968: 15,
                  #21793419:
                    ({ #c7b317f4: 16, #c68b4ed6: 1 }, { #c68b4ed6: 25 })
                },
                {
                  #c8ff724b: "optionalFunction",
                  #2cdb06fb: [ "optionalFunction", "BarDelegate" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 17 },
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 18,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 7, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 19,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #22b27dd5: true,
                  #d2e9b40c: "-[BarDelegate optionalFunction]"
                })>
          ],
          { },
          {
            #d688371b: [
              {
                #c709e154: <#cd511304>,
                #ec05e4a8: 14,
                #c8ff724b: {
                  #c8ff724b: "NSObject",
                  #2cdb06fb: [ "NSObject" ]
                }
              }
            ]
          })>,
      <#18d25297:
         ({
            #d121c0bd: 20,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 19, #c68b4ed6: 1 },
               { #c7b317f4: 21, #c68b4ed6: 2 })
          },
          { #c8ff724b: "Bar", #2cdb06fb: [ "Bar" ] },
          [
            <#c5b2960b:
               ({
                  #d121c0bd: 21,
                  #f9005968: 20,
                  #21793419:
                    ({ #c7b317f4: 20, #c68b4ed6: 1 }, { #c68b4ed6: 46 })
                },
                { #c8ff724b: "delegate", #2cdb06fb: [ "delegate", "Bar" ] },
                {
                  #30e4876a: { #c1127ea9: 22 },
                  #3106f0d5: {
                    #c709e154: <#e655f08d>,
                    #ec05e4a8: 23,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #f60cd2e1: {
                    #c709e154: <#e655f08d>,
                    #ec05e4a8: 24,
                    #c8ff724b: {
                      #c8ff724b: "setDelegate:",
                      #2cdb06fb: [ "setDelegate:", "Bar" ]
                    }
                  },
                  #2e0d396b: {
                    #c709e154: <#38103cca>,
                    #ec05e4a8: 25,
                    #c8ff724b: {
                      #c8ff724b: "_delegate",
                      #2cdb06fb: [ "_delegate", "Bar" ]
                    },
                    #30e4876a: { #c1127ea9: 22 }
                  },
                  #e42793c1: [
                    <#009aba4f>, <#2fe629a9>, <#cd718b98>, <#374fb956>
                  ]
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 23,
                  #f9005968: 20,
                  #21793419: ({ }, { }),
                  #eb8a1f5a: true
                },
                { #c8ff724b: "delegate", #2cdb06fb: [ "delegate", "Bar" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 22 },
                  #001e675c: true,
                  #2c8fcfd4: {
                    #c709e154: <#f9260501>,
                    #ec05e4a8: 21,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 26,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 27, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 28,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #d2e9b40c: "-[Bar delegate]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 24,
                  #f9005968: 20,
                  #21793419: ({ }, { }),
                  #eb8a1f5a: true
                },
                {
                  #c8ff724b: "setDelegate:",
                  #2cdb06fb: [ "setDelegate:", "Bar" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 17 },
                  #001e675c: true,
                  #2c8fcfd4: {
                    #c709e154: <#f9260501>,
                    #ec05e4a8: 21,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({ #d121c0bd: 29, #21793419: ({ }, { }) },
                        { #c8ff724b: "delegate", #2cdb06fb: [ "delegate" ] },
                        { #c1127ea9: 22 },
                        { #0370b1b2: 0 })>
                  ],
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 30,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 27, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 31,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #d2e9b40c: "-[Bar setDelegate:]"
                })>
          ],
          { },
          {
            #04c0017b: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 13,
              #c8ff724b: { #c8ff724b: "NSObject", #2cdb06fb: [ "NSObject" ] }
            },
            #d32dd232: {
              #c709e154: <#c37c57de>,
              #ec05e4a8: 32,
              #c8ff724b: { #c8ff724b: "Bar", #2cdb06fb: [ "Bar" ] }
            }
          })>,
      <#0e281b68:
         ({
            #d121c0bd: 32,
            #f9005968: 1,
            #21793419:
              ({ #c7b317f4: 23, #c68b4ed6: 1 },
               { #c7b317f4: 28, #c68b4ed6: 1 })
          },
          { #c8ff724b: "Bar", #2cdb06fb: [ "Bar" ] },
          [
            <#3ccd3797:
               ({
                  #d121c0bd: 33,
                  #f9005968: 32,
                  #21793419:
                    ({ #c7b317f4: 24, #c68b4ed6: 1 },
                     { #c7b317f4: 26, #c68b4ed6: 1 })
                },
                {
                  #c8ff724b: "unsafeAction",
                  #2cdb06fb: [ "unsafeAction", "Bar" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 17 },
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 34,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true,
                          #0a16e1f2: true,
                          #d3368c8a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 27, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 35,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #c11b7aa2:
                    <#d394bb73:
                       ({
                          #d121c0bd: 36,
                          #21793419:
                            ({ #c7b317f4: 24, #c68b4ed6: 22 },
                             { #c7b317f4: 26, #c68b4ed6: 1 })
                        },
                        [
                          <#d0cddcea:
                             ({
                                #d121c0bd: 37,
                                #21793419:
                                  ({ #c7b317f4: 25, #c68b4ed6: 3 },
                                   { #c68b4ed6: 34 })
                              },
                              [
                                <#f104c570:
                                   ({
                                      #d121c0bd: 38,
                                      #21793419:
                                        ({ #c68b4ed6: 3 }, { #c68b4ed6: 34 })
                                    },
                                    [
                                      <#26afa8d2:
                                         ({
                                            #d121c0bd: 39,
                                            #21793419:
                                              ({ #c68b4ed6: 4 },
                                               { #c68b4ed6: 9 })
                                          },
                                          [
                                            <#e9c8dd27:
                                               ({
                                                  #d121c0bd: 40,
                                                  #21793419:
                                                    ({ #c68b4ed6: 4 },
                                                     { #c68b4ed6: 9 })
                                                },
                                                [
                                                  <#0d679c05:
                                                     ({
                                                        #d121c0bd: 41,
                                                        #21793419:
                                                          ({ #c68b4ed6: 4 },
                                                           { })
                                                      },
                                                      [],
                                                      {
                                                        #30e4876a: {
                                                          #c1127ea9: 27
                                                        }
                                                      },
                                                      {
                                                        #12076e59:
                                                          <#c3b129f9:
                                                             ({
                                                                #d121c0bd: 42,
                                                                #21793419:
                                                                  ({ }, { })
                                                              },
                                                              [
                                                                <#e9db58be:
                                                                   ({
                                                                    #d121c0bd:
                                                                    43,
                                                                    #21793419:
                                                                    (
                                                                    { }, { })
                                                                    },
                                                                    [],
                                                                    {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    27,
                                                                    #ea1a680e:
                                                                    true
                                                                    },
                                                                    #0e89e422:
                                                                    <#28055b85>
                                                                    },
                                                                    {
                                                                    #c369ebbe: {
                                                                    #c709e154:
                                                                    <#c6dba908>,
                                                                    #ec05e4a8:
                                                                    34,
                                                                    #c8ff724b: {
                                                                    #c8ff724b:
                                                                    "self",
                                                                    #2cdb06fb: [
                                                                    "self"
                                                                    ]
                                                                    },
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    27,
                                                                    #ea1a680e:
                                                                    true
                                                                    }
                                                                    }
                                                                    })>
                                                              ],
                                                              {
                                                                #30e4876a: {
                                                                  #c1127ea9:
                                                                    27
                                                                }
                                                              },
                                                              {
                                                                #c91e0a14:
                                                                  <#f7495e1f>,
                                                                #fa1a3bd3: []
                                                              },
                                                              false)>
                                                      })>
                                                ],
                                                {
                                                  #30e4876a: {
                                                    #c1127ea9: 44
                                                  },
                                                  #0e89e422: <#28055b85>,
                                                  #d61caa14: <#f9260501>
                                                },
                                                {
                                                  #c709e154:
                                                    <#fac503de: {
                                                       #c709e154: <#f9260501>,
                                                       #ec05e4a8: 21,
                                                       #c8ff724b: {
                                                         #c8ff724b:
                                                           "delegate",
                                                         #2cdb06fb: [
                                                           "delegate", "Bar"
                                                         ]
                                                       }
                                                     }>,
                                                  #2827bd9b: true
                                                })>,
                                            <#0d679c05:
                                               ({
                                                  #d121c0bd: 41,
                                                  #21793419: ({ }, { })
                                                },
                                                [],
                                                {
                                                  #30e4876a: {
                                                    #c1127ea9: 27
                                                  }
                                                },
                                                {
                                                  #12076e59:
                                                    <#c3b129f9:
                                                       ({
                                                          #d121c0bd: 42,
                                                          #21793419:
                                                            ({ }, { })
                                                        },
                                                        [
                                                          <#e9db58be:
                                                             ({
                                                                #d121c0bd: 43,
                                                                #21793419:
                                                                  ({ }, { })
                                                              },
                                                              [],
                                                              {
                                                                #30e4876a: {
                                                                  #c1127ea9:
                                                                    27,
                                                                  #ea1a680e:
                                                                    true
                                                                },
                                                                #0e89e422:
                                                                  <#28055b85>
                                                              },
                                                              {
                                                                #c369ebbe: {
                                                                  #c709e154:
                                                                    <#c6dba908>,
                                                                  #ec05e4a8:
                                                                    34,
                                                                  #c8ff724b: {
                                                                    #c8ff724b:
                                                                    "self",
                                                                    #2cdb06fb: [
                                                                    "self"
                                                                    ]
                                                                  },
                                                                  #30e4876a: {
                                                                    #c1127ea9:
                                                                    27,
                                                                    #ea1a680e:
                                                                    true
                                                                  }
                                                                }
                                                              })>
                                                        ],
                                                        {
                                                          #30e4876a: {
                                                            #c1127ea9: 27
                                                          }
                                                        },
                                                        {
                                                          #c91e0a14:
                                                            <#f7495e1f>,
                                                          #fa1a3bd3: []
                                                        },
                                                        false)>
                                                })>,
                                            <#c3b129f9:
                                               ({
                                                  #d121c0bd: 45,
                                                  #21793419:
                                                    ({ #c68b4ed6: 9 }, { })
                                                },
                                                [
                                                  <#f104c570:
                                                     ({
                                                        #d121c0bd: 46,
                                                        #21793419: ({ }, { })
                                                      },
                                                      [
                                                        <#0d679c05:
                                                           ({
                                                              #d121c0bd: 41,
                                                              #21793419:
                                                                ({
                                                                   #c68b4ed6:
                                                                    4
                                                                 },
                                                                 { })
                                                            },
                                                            [],
                                                            {
                                                              #30e4876a: {
                                                                #c1127ea9: 27
                                                              }
                                                            },
                                                            {
                                                              #12076e59:
                                                                <#c3b129f9:
                                                                   ({
                                                                    #d121c0bd:
                                                                    42,
                                                                    #21793419:
                                                                    (
                                                                    { }, { })
                                                                    },
                                                                    [
                                                                    <#e9db58be:
                                                                    ({
                                                                    #d121c0bd:
                                                                    43,
                                                                    #21793419:
                                                                    (
                                                                    { }, { })
                                                                    },
                                                                    [],
                                                                    {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    27,
                                                                    #ea1a680e:
                                                                    true
                                                                    },
                                                                    #0e89e422:
                                                                    <#28055b85>
                                                                    },
                                                                    {
                                                                    #c369ebbe: {
                                                                    #c709e154:
                                                                    <#c6dba908>,
                                                                    #ec05e4a8:
                                                                    34,
                                                                    #c8ff724b: {
                                                                    #c8ff724b:
                                                                    "self",
                                                                    #2cdb06fb: [
                                                                    "self"
                                                                    ]
                                                                    },
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    27,
                                                                    #ea1a680e:
                                                                    true
                                                                    }
                                                                    }
                                                                    })>
                                                                    ],
                                                                    {
                                                                    #30e4876a: {
                                                                    #c1127ea9:
                                                                    27
                                                                    }
                                                                    },
                                                                    {
                                                                    #c91e0a14:
                                                                    <#f7495e1f>,
                                                                    #fa1a3bd3:
                                                                    []
                                                                    },
                                                                    false)>
                                                            })>
                                                      ],
                                                      {
                                                        #30e4876a: {
                                                          #c1127ea9: 22
                                                        }
                                                      },
                                                      {
                                                        #316d331f: "delegate",
                                                        #1ea99a8b: true,
                                                        #ec05e4a8: 47
                                                      })>
                                                ],
                                                {
                                                  #30e4876a: {
                                                    #c1127ea9: 22
                                                  }
                                                },
                                                {
                                                  #c91e0a14: <#e02d4a65>,
                                                  #fa1a3bd3: []
                                                },
                                                false)>
                                          ],
                                          { #30e4876a: { #c1127ea9: 22 } })>
                                    ],
                                    { #30e4876a: { #c1127ea9: 17 } },
                                    {
                                      #316d331f: "optionalFunction",
                                      #ec05e4a8: 16
                                    })>
                              ],
                              { #30e4876a: { #c1127ea9: 17 } },
                              { })>
                        ])>,
                  #d2e9b40c: "-[Bar unsafeAction]"
                })>,
            <#070ee654:
               ({
                  #d121c0bd: 25,
                  #f9005968: 32,
                  #21793419: ({ #c7b317f4: 20, #c68b4ed6: 46 }, { })
                },
                { #c8ff724b: "_delegate", #2cdb06fb: [ "_delegate", "Bar" ] },
                { #c1127ea9: 22 },
                { },
                { #015a971f: true, #f9049e82: <#d6c054e3> })>,
            <#c1a9158b:
               ({ #d121c0bd: 48, #21793419: ({ }, { }) },
                {
                  #d32dd232: <#009015ca>,
                  #2c8fcfd4: {
                    #c709e154: <#f9260501>,
                    #ec05e4a8: 21,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #2e0d396b: {
                    #c709e154: <#38103cca>,
                    #ec05e4a8: 25,
                    #c8ff724b: {
                      #c8ff724b: "_delegate",
                      #2cdb06fb: [ "_delegate", "Bar" ]
                    },
                    #30e4876a: { #c1127ea9: 22 }
                  }
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 47,
                  #f9005968: 32,
                  #21793419: ({ }, { }),
                  #eb8a1f5a: true
                },
                { #c8ff724b: "delegate", #2cdb06fb: [ "delegate", "Bar" ] },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 22 },
                  #001e675c: true,
                  #2c8fcfd4: {
                    #c709e154: <#f9260501>,
                    #ec05e4a8: 21,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 26,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 27, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 28,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #d2e9b40c: "-[Bar delegate]"
                })>,
            <#3ccd3797:
               ({
                  #d121c0bd: 49,
                  #f9005968: 32,
                  #21793419: ({ }, { }),
                  #eb8a1f5a: true
                },
                {
                  #c8ff724b: "setDelegate:",
                  #2cdb06fb: [ "setDelegate:", "Bar" ]
                },
                {
                  #3ba2c7f6: true,
                  #137b649c: { #c1127ea9: 17 },
                  #001e675c: true,
                  #2c8fcfd4: {
                    #c709e154: <#f9260501>,
                    #ec05e4a8: 21,
                    #c8ff724b: {
                      #c8ff724b: "delegate",
                      #2cdb06fb: [ "delegate", "Bar" ]
                    }
                  },
                  #d17ebeaa: [
                    <#fd75cc45:
                       ({ #d121c0bd: 29, #21793419: ({ }, { }) },
                        { #c8ff724b: "delegate", #2cdb06fb: [ "delegate" ] },
                        { #c1127ea9: 22 },
                        { #0370b1b2: 0 })>
                  ],
                  #28dcb2c4: [
                    <#d0d84992:
                       ({
                          #d121c0bd: 30,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "self", #2cdb06fb: [ "self" ] },
                        { #c1127ea9: 27, #ea1a680e: true },
                        { })>,
                    <#d0d84992:
                       ({
                          #d121c0bd: 31,
                          #21793419: ({ }, { }),
                          #eb8a1f5a: true
                        },
                        { #c8ff724b: "_cmd", #2cdb06fb: [ "_cmd" ] },
                        { #c1127ea9: 5 },
                        { })>
                  ],
                  #d2e9b40c: "-[Bar setDelegate:]"
                })>
          ],
          { },
          {
            #2ec29bb2: {
              #c709e154: <#3cf18b8d>,
              #ec05e4a8: 20,
              #c8ff724b: { #c8ff724b: "Bar", #2cdb06fb: [ "Bar" ] }
            }
          })>,
      <#0f3f4d35:
         ({ #d121c0bd: 50, #21793419: ({ }, { }), #eb8a1f5a: true },
          { #c8ff724b: "instancetype", #2cdb06fb: [ "instancetype" ] },
          51,
          { })>
    ],
    { },
    {
      #e870593a: "tests/optional.m",
      #e52854e9: <#3ff69d49>,
      #f81dea91: {
        #26452803: 8,
        #c674c89d: 16,
        #3569bf4a: 32,
        #d7cd079d: 64,
        #048ad2a1: 64
      },
      #247f0baa: true,
      #1acb7079: [
        <#22d546dd: ({ #d121c0bd: 17 }, <#392cef74>)>,
        <#22d546dd: ({ #d121c0bd: 52 }, <#2bf4b04a>)>,
        <#22d546dd: ({ #d121c0bd: 53 }, <#ec0a078a>)>,
        <#22d546dd: ({ #d121c0bd: 54 }, <#f6dab0c9>)>,
        <#22d546dd: ({ #d121c0bd: 55 }, <#0f54f45c>)>,
        <#22d546dd: ({ #d121c0bd: 56 }, <#0037c4cf>)>,
        <#22d546dd: ({ #d121c0bd: 57 }, <#3290d19c>)>,
        <#22d546dd: ({ #d121c0bd: 58 }, <#fee0a138>)>,
        <#22d546dd: ({ #d121c0bd: 59 }, <#1da7d9cb>)>,
        <#22d546dd: ({ #d121c0bd: 60 }, <#0baa9fe7>)>,
        <#22d546dd: ({ #d121c0bd: 61 }, <#3866e79a>)>,
        <#22d546dd: ({ #d121c0bd: 62 }, <#23a02071>)>,
        <#22d546dd: ({ #d121c0bd: 63 }, <#09087e8d>)>,
        <#22d546dd: ({ #d121c0bd: 64 }, <#15c4357c>)>,
        <#22d546dd: ({ #d121c0bd: 65 }, <#e75f9f31>)>,
        <#22d546dd: ({ #d121c0bd: 66 }, <#c2f78dcd>)>,
        <#22d546dd: ({ #d121c0bd: 67 }, <#3726ba3b>)>,
        <#22d546dd: ({ #d121c0bd: 68 }, <#e583cc63>)>,
        <#22d546dd: ({ #d121c0bd: 69 }, <#3759b761>)>,
        <#22d546dd: ({ #d121c0bd: 70 }, <#ebd317dd>)>,
        <#22d546dd: ({ #d121c0bd: 71 }, <#2ec759b9>)>,
        <#22d546dd: ({ #d121c0bd: 72 }, <#284d329d>)>,
        <#22d546dd: ({ #d121c0bd: 73 }, <#35acb472>)>,
        <#22d546dd: ({ #d121c0bd: 74 }, <#2b1d0544>)>,
        <#22d546dd: ({ #d121c0bd: 75 }, <#0106ffa8>)>,
        <#22d546dd: ({ #d121c0bd: 76 }, <#d6bc9d8a>)>,
        <#22d546dd: ({ #d121c0bd: 77 }, <#19b0df66>)>,
        <#22d546dd: ({ #d121c0bd: 78 }, <#1336b84a>)>,
        <#22d546dd: ({ #d121c0bd: 79 }, <#20963a1f>)>,
        <#22d546dd: ({ #d121c0bd: 80 }, <#16068af1>)>,
        <#22d546dd: ({ #d121c0bd: 81 }, <#ebf08555>)>,
        <#22d546dd: ({ #d121c0bd: 82 }, <#d78ceb63>)>,
        <#22d546dd: ({ #d121c0bd: 83 }, <#dd2a33f3>)>,
        <#22d546dd: ({ #d121c0bd: 84 }, <#ef62b1d7>)>,
        <#22d546dd: ({ #d121c0bd: 85 }, <#0c8bf62c>)>,
        <#22d546dd: ({ #d121c0bd: 86 }, <#13391dca>)>,
        <#22d546dd: ({ #d121c0bd: 87 }, <#ecc0d32e>)>,
        <#22d546dd: ({ #d121c0bd: 88 }, <#c2767110>)>,
        <#22d546dd: ({ #d121c0bd: 89 }, <#c813b9a0>)>,
        <#22d546dd: ({ #d121c0bd: 90 }, <#da4c3784>)>,
        <#22d546dd: ({ #d121c0bd: 91 }, <#f7757bd9>)>,
        <#22d546dd: ({ #d121c0bd: 92 }, <#fe22a377>)>,
        <#22d546dd: ({ #d121c0bd: 93 }, <#d7aa58db>)>,
        <#22d546dd: ({ #d121c0bd: 94 }, <#d2f340c8>)>,
        <#22d546dd: ({ #d121c0bd: 95 }, <#2193aedd>)>,
        <#22d546dd: ({ #d121c0bd: 96 }, <#0dd56321>)>,
        <#22d546dd: ({ #d121c0bd: 97 }, <#d8e10c82>)>,
        <#22d546dd: ({ #d121c0bd: 98 }, <#c4f079df>)>,
        <#22d546dd: ({ #d121c0bd: 99 }, <#1ee7219a>)>,
        <#22d546dd: ({ #d121c0bd: 100 }, <#0d506118>)>,
        <#22d546dd: ({ #d121c0bd: 44 }, <#dec9bcfd>)>,
        <#22d546dd: ({ #d121c0bd: 101 }, <#f1f6e5a2>)>,
        <#22d546dd: ({ #d121c0bd: 102 }, <#d935d0cf>)>,
        <#22d546dd: ({ #d121c0bd: 103 }, <#d35a4eab>)>,
        <#22d546dd: ({ #d121c0bd: 104 }, <#c9ba0f87>)>,
        <#22d546dd: ({ #d121c0bd: 105 }, <#db21580c>)>,
        <#22d546dd: ({ #d121c0bd: 106 }, <#391b1e6e>)>,
        <#d3d219f7: ({ #d121c0bd: 107 }, { #c1127ea9: 17 })>,
        <#22d546dd: ({ #d121c0bd: 108 }, <#ea323187>)>,
        <#22d546dd: ({ #d121c0bd: 109 }, <#2fe155d3>)>,
        <#22d546dd: ({ #d121c0bd: 110 }, <#f65b235f>)>,
        <#d3d219f7: ({ #d121c0bd: 111 }, { #c1127ea9: 106 })>,
        <#0098a8c5: ({ #d121c0bd: 112 }, { #fcd148e8: 104 })>,
        <#2e3d736c: ({ #d121c0bd: 113 }, { #c1127ea9: 112 })>,
        <#0098a8c5: ({ #d121c0bd: 114 }, { #fcd148e8: 105 })>,
        <#2e3d736c: ({ #d121c0bd: 115 }, { #c1127ea9: 114 })>,
        <#2374f4e7: ({ #d121c0bd: 116 }, 9)>,
        <#d80cb60b: ({ #d121c0bd: 117 }, 118)>,
        <#d3d219f7: ({ #d121c0bd: 119 }, { #c1127ea9: 56, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 120 }, { #c1127ea9: 53, #ea1a680e: true })>,
        <#d3d219f7: ({ #d121c0bd: 121 }, { #c1127ea9: 53 })>,
        <#d80cb60b: ({ #d121c0bd: 122 }, 123)>,
        <#da0c5ecf:
           ({ #d121c0bd: 124 },
            { #cd26765d: { #c1127ea9: 122 }, #11302019: 24 },
            1)>,
        <#2374f4e7: ({ #d121c0bd: 125 }, 13)>,
        <#19e1ef85:
           ({ #d121c0bd: 7, #26f32be5: 113 },
            { #0b680f7d: { #c1127ea9: 113 }, #c3687459: 6 })>,
        <#19e1ef85:
           ({ #d121c0bd: 51, #26f32be5: 113 },
            { #0b680f7d: { #c1127ea9: 7 }, #c3687459: 50 })>,
        <#19e1ef85:
           ({ #d121c0bd: 5, #26f32be5: 111 },
            { #0b680f7d: { #c1127ea9: 111 }, #c3687459: 4 })>,
        <#2374f4e7: ({ #d121c0bd: 126 }, 20)>,
        <#263b5f37: ({ #d121c0bd: 127, #26f32be5: 113 })>,
        <#0098a8c5:
           ({ #d121c0bd: 128 }, { #fcd148e8: 104, #0b037c51: [ 15 ] })>,
        <#2e3d736c: ({ #d121c0bd: 22 }, { #c1127ea9: 128 })>,
        <#2e3d736c: ({ #d121c0bd: 27 }, { #c1127ea9: 126 })>,
        <#cfc9a9b2: ({ #d121c0bd: 0 })>
      ]
    })>
