java_library(
    name='utils',
    srcs=glob(['**/*.java']),
    deps=[
        '//infer/lib/java/android:android',
        '//dependencies/java/guava:guava',
        '//dependencies/java/junit:hamcrest',
        '//dependencies/java/jackson:jackson',
        '//dependencies/java/jsr-305:jsr-305',
        '//dependencies/java/junit:junit',
        '//dependencies/java/opencsv:opencsv'
    ],
    visibility = [
        'PUBLIC',
    ],
    source='7',
    target='7',
)
