# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR = ../..

INFER_OPTIONS = --project-root src --no-keep-going --racerd-only --filtering
INFERPRINT_OPTIONS = --issues-tests

SOURCES = src/*.java

include $(TESTS_DIR)/javac.make
