/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// a header generated by the build, which has not run: this file includes
// widget.h but cannot be captured
#include "generated/version.h"
#include "widget.h"

int use_widget_in_generated_user() { return header_function_bad(); }
