# TODO: this file exists only to support buck integration in infer/tests/build_systems/build_integration_tests.py
java_test(
    name='infer',
    srcs=glob(['*.java']),
    deps=[
        '//dependencies/java/guava:guava',
        '//dependencies/java/junit:hamcrest',
        '//dependencies/java/junit:junit',
        '//infer/tests/utils:utils',
    ],
    resources=[
        '//infer/tests/codetoanalyze/java/infer:analyze',
    ],
    visibility=[
        'PUBLIC',
    ],
)
