NULLPTR_DEREFERENCE, no_bucket, src/com/example/DiffClass1.java, com.example.DiffClass1.triggerNpe():int, 1
PULSE_RESOURCE_LEAK, no_bucket, src/com/example/DiffClass2.java, com.example.DiffClass2.openResource():void, 8
NULLPTR_DEREFERENCE, no_bucket, src/com/example/DiffClass3.java, com.example.DiffClass3.doStuff3():int, 1
NULLPTR_DEREFERENCE, no_bucket, src/com/example/DiffClassUnchanged.java, com.example.DiffClassUnchanged.doWrongStuff():int, 1
