java_library(
    name = 'annotations',
    srcs = glob(['**/*.java']),
    deps = [
        '//dependencies/java/jsr-305:jsr-305',
    ],
    visibility = [
        'PUBLIC'
        // this is you u and me   pull things out.
    ]
)
