# Copyright (c) 2017 - present Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# This file exists to make opam happy, it should not do anything useful besides that.

.PHONY: install uninstall
install uninstall:
	@:
