/*
 * Copyright (c) 2015- Facebook.
 * All rights reserved.
 */

package codetoanalyze.java.infer;

/* @generated */

public class AutoGenerated {

  void npe() {
    String s = null;
    int n = s.length();
  }
}
