# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR = ../../..
BACKTRACK_LEVEL = 1

include $(TESTS_DIR)/build_systems/backtrack_level/backtrack_level.make
