codetoanalyze/java/topl/typeFilter/TypeFilter.java, TypeFilter.bBad(B):void, 0, TOPL_ERROR, no_bucket, ERROR, [call to void TypeFilter.f(Object)]
codetoanalyze/java/topl/typeFilter/TypeFilter.java, TypeFilter.cBad(LongBadName):void, 0, TOPL_ERROR, no_bucket, ERROR, [call to void TypeFilter.f(Object)]
codetoanalyze/java/topl/typeFilter/TypeFilter.java, TypeFilter.dBad():void, 0, TOPL_ERROR, no_bucket, ERROR, [call to void TypeFilter.f(Object)]
