build_systems/pulse_messages_objc/DerivedTaint.m, my_source, 44, 3, ERROR, NULLPTR_DEREFERENCE, `p` could be null (null value originating from line 43) and is dereferenced., 
build_systems/pulse_messages_objc/DerivedTaint.m, test_derived_taint_bad1, 51, 3, ERROR, TAINT_ERROR, Simple Test. `p.university` is tainted by value passed as argument `#0` to `my_source` with kind `SimpleSource` and `&p` flows to value passed as argument `#0` to `my_log` with kind `SimpleSink`., 
build_systems/pulse_messages_objc/DerivedTaint.m, test_derived_taint_bad2, 58, 3, ERROR, TAINT_ERROR, Simple Test. `p.university.name` is tainted by value passed as argument `#0` to `my_source` with kind `SimpleSource` and `&p` flows to value passed as argument `#0` to `my_log` with kind `SimpleSink`., 
build_systems/pulse_messages_objc/DerivedTaint.m, test_derived_taint_bad3, 65, 3, ERROR, TAINT_ERROR, Simple Test. `p.university.name` is tainted by value passed as argument `#0` to `my_source` with kind `SimpleSource` and `p.university` flows to value passed as argument `#0` to `my_log` with kind `SimpleSink`., 
build_systems/pulse_messages_objc/TaintBlocks.m, objc_block_TaintBlocks.m:20, 21, 5, ERROR, TAINT_ERROR, Simple Test. `source` is tainted by value passed as argument `#0` to a block passed to `InferTaint.callBlockUnknown:` with kind `SimpleSource` and flows to value passed as argument `#0` to `InferTaint.sink:` with kind `SimpleSink`., 
build_systems/pulse_messages_objc/nil_issues.mm, dereferenceNilBad, 48, 10, ERROR, NULLPTR_DEREFERENCE, `int_ptr` could be null (null value originating from line 47) and is dereferenced., 
build_systems/pulse_messages_objc/nil_issues.mm, testCallMethodReturnsnonPODBad, 53, 28, ERROR, NIL_MESSAGING_TO_NON_POD, The call to `SomeObject.returnsnonPOD` may trigger the following issue: `obj` could be nil (from the call to `SomeObject.returnsnonPOD()` on line 52) and is used to call a C++ method with a non-POD return type `std::shared_ptr<int>` in the call to `SomeObject.returnsnonPOD()`; nil messaging such methods is undefined behaviour., 
build_systems/pulse_messages_objc/nil_issues.mm, testNonPODTraceBad, 59, 33, ERROR, NIL_MESSAGING_TO_NON_POD, The call to `SomeObject.returnsnonPOD` may trigger the following issue: `obj` could be nil (from the call to `SomeObject.returnsnonPOD()` on line 58) and is used to call a C++ method with a non-POD return type `std::shared_ptr<int>` in the call to `SomeObject.returnsnonPOD()`; nil messaging such methods is undefined behaviour., 
build_systems/pulse_messages_objc/nil_issues.mm, testCallMethodReturnsnonPODLatent, 70, 28, ERROR, NIL_MESSAGING_TO_NON_POD_LATENT, The call to `SomeObject.returnsnonPOD` may trigger the following issue: `obj` could be nil (from the call to `SomeObject.returnsnonPOD()` on line 66) and is used to call a C++ method with a non-POD return type `std::shared_ptr<int>` in the call to `SomeObject.returnsnonPOD()`; nil messaging such methods is undefined behaviour., 
build_systems/pulse_messages_objc/nil_issues.mm, testCallMethodReturnsnonPODLatentBad, 75, 10, ERROR, NIL_MESSAGING_TO_NON_POD, The call to `testCallMethodReturnsnonPODLatent` in turn calls `SomeObject.returnsnonPOD` and may trigger the following issue: `obj` could be nil (from the call to `testCallMethodReturnsnonPODLatent()` on line 75) and is used to call a C++ method with a non-POD return type `std::shared_ptr<int>` in the call to `testCallMethodReturnsnonPODLatent()`; nil messaging such methods is undefined behaviour., 
build_systems/pulse_messages_objc/nil_issues.mm, testAccessPropertyAccessorBad, 80, 14, ERROR, NIL_MESSAGING_TO_NON_POD, The call to `SomeObject.ptr` may trigger the following issue: `obj` could be nil (from the call to `SomeObject.ptr()` on line 79) and is used to call a C++ method with a non-POD return type `std::shared_ptr<int>` in the call to `SomeObject.ptr()`; nil messaging such methods is undefined behaviour., 
build_systems/pulse_messages_objc/nil_issues.mm, testTraceBad, 86, 10, ERROR, NULLPTR_DEREFERENCE, `ptr` could be null (null value originating from line 84) and is dereferenced., 
build_systems/pulse_messages_objc/nil_issues.mm, testCallNullptrBad, 91, 3, ERROR, NULLPTR_DEREFERENCE, `f` could be null (null value originating from line 90) and is dereferenced., 
build_systems/pulse_messages_objc/nil_issues.mm, nilInsertionIntoCollectionBad, 98, 3, ERROR, NIL_INSERTION_INTO_COLLECTION, `object` could be nil (from the call to `returns_nil()` on line 97) and is used as a value when inserting into a collection, potentially causing a crash., 
build_systems/pulse_messages_objc/nil_issues.mm, nilInsertionIntoCollectionThroughCallBad, 102, 30, ERROR, NIL_INSERTION_INTO_COLLECTION, `returns_nil()` could be nil (from the call to `returns_nil()` on line 102) and is used as a value when inserting into a collection, potentially causing a crash., 
build_systems/pulse_messages_objc/nil_issues.mm, property_accessorBad, 107, 3, ERROR, NULLPTR_DEREFERENCE, `obj.x_ptr` could be null (null value originating from line 106) and is dereferenced., 
build_systems/pulse_messages_objc/retain_cycle.mm, RCBlock.retain_self_in_block_retain_cycle_bad, 49, 8, ERROR, RETAIN_CYCLE, Retain cycle found at line 49, column 8 between the following objects: 
  1) self->_handler, assigned on line 49
  2) self captured by block defined in retain_cycle.mm:49., 
build_systems/pulse_messages_objc/retain_cycle.mm, RCBlock.retain_self_in_block_with_store_retain_cycle_bad, 55, 3, ERROR, RETAIN_CYCLE, Retain cycle found at line 55, column 3 between the following objects: 
  1) self captured by block defined in retain_cycle.mm:55
  2) self->_handler, assigned on line 55., 
build_systems/pulse_messages_objc/retain_cycle.mm, retain_a_in_block_cycle_bad, 87, 5, ERROR, RETAIN_CYCLE, Retain cycle found at line 87, column 5 between the following objects: 
  1) a->_b, assigned on line 86
  2) b->_a_handler, assigned on line 87
  3) a captured by block defined in retain_cycle.mm:87., 
codetoanalyze/objc/pulse/retain_cycles/IvarInheritanceRetainCycle.m, field_superclass_main, 30, 3, ERROR, RETAIN_CYCLE, Retain cycle found at line 30, column 3 between the following objects: 
  1) b
  2) b->a, assigned on line 30., 
codetoanalyze/objc/pulse/retain_cycles/RetainCycleBlockAsParameter.m, FBSomeDataManager.fetchNewData_bad, 46, 14, ERROR, RETAIN_CYCLE, Retain cycle found at line 46, column 14 between the following objects: 
  1) self->_fetcher, assigned on line 46
  2) block defined in RetainCycleBlockAsParameter.m:46
  3) self captured by block defined in RetainCycleBlockAsParameter.m:46., 
codetoanalyze/objc/pulse/retain_cycles/RetainCycleDeduplication.m, CViewController.setCaptureInteractionController_bad:, 32, 24, ERROR, RETAIN_CYCLE, Retain cycle found at line 32, column 24 between the following objects: 
  1) self->_captureController, assigned on line 31
  2) self->_captureController->_delegate, assigned on line 32., 
