--capture-textual callingExternals_ret_null_TD.sil --capture-textual external_ret_null_t.sil --capture-doli external_ret_null_d.doli
callingExternals_ret_null_TD.sil, $TOPLEVEL$CLASS$.external_call_bad_t(ClassB):int, 4, NULLPTR_DEREFERENCE, no_bucket, ERROR, [in call to `ClassB ClassB.external_ret_null_t(ClassB)`,is assigned to the null pointer,returned,return from call to `ClassB ClassB.external_ret_null_t(ClassB)`,invalid access occurs here]
callingExternals_ret_null_TD.sil, $TOPLEVEL$CLASS$.external_call_bad_d(ClassB):int, 4, NULLPTR_DEREFERENCE, no_bucket, ERROR, [in call to `ClassB $TOPLEVEL$CLASS$.r388_a(ClassB)`,is assigned to the null pointer,returned,return from call to `ClassB $TOPLEVEL$CLASS$.r388_a(ClassB)`,invalid access occurs here]
____________________________________
--capture-textual callingExternals_Several.sil --capture-doli externals_Some.doli
callingExternals_Several.sil, ClassB.depends_on_two_bad(ClassB):ClassB, 13, NULLPTR_DEREFERENCE, no_bucket, ERROR, [in call to `ClassB ClassB.ret_null(ClassB)`,is assigned to the null pointer,returned,return from call to `ClassB ClassB.ret_null(ClassB)`,invalid access occurs here]
____________________________________
--capture-doli callingInternals.doli
____________________________________
--capture-textual external_ret_this.sil --capture-doli callingTextualFromDoli.doli
____________________________________
