<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/c_cast.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "column" : 9
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "i",
        "qual_name" : [
          "i"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "is_init_ice" : true,
        "init_expr" : <"IntegerLiteral" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
              },
              {
              }
            )
          },
          [
          ],
          {
            "qual_type" : {
              "type_ptr" : 8
            }
          },
          {
            "is_signed" : true,
            "bitwidth" : 32,
            "value" : "10"
          }
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 10,
        "source_range" : (
          {
            "line" : 8,
            "column" : 1
          },
          {
            "column" : 16
          }
        )
      },
      {
        "name" : "l",
        "qual_name" : [
          "l"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : <"CStyleCastExpr" : (
          {
            "pointer" : 12,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 16
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : 13,
                "source_range" : (
                  {
                  },
                  {
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 14,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 15,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 8
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 8
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  true
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              {
                "cast_kind" : <"IntegralCast">,
                "base_path" : [
                ]
              },
              true
            )>
          ],
          {
            "qual_type" : {
              "type_ptr" : 11
            }
          },
          {
            "cast_kind" : <"NoOp">,
            "base_path" : [
            ]
          },
          {
            "type_ptr" : 11
          }
        )>
      }
    )>,
    <"VarDecl" : (
      {
        "pointer" : 16,
        "source_range" : (
          {
            "line" : 9,
            "column" : 1
          },
          {
            "column" : 16
          }
        )
      },
      {
        "name" : "m",
        "qual_name" : [
          "m"
        ]
      },
      {
        "type_ptr" : 11
      },
      {
        "is_global" : true,
        "init_expr" : <"CXXFunctionalCastExpr" : (
          {
            "pointer" : 17,
            "source_range" : (
              {
                "column" : 10
              },
              {
                "column" : 16
              }
            )
          },
          [
            <"ImplicitCastExpr" : (
              {
                "pointer" : 18,
                "source_range" : (
                  {
                    "column" : 15
                  },
                  {
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 19,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 20,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 8
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 7,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 8
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  true
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 11
                }
              },
              {
                "cast_kind" : <"IntegralCast">,
                "base_path" : [
                ]
              },
              true
            )>
          ],
          {
            "qual_type" : {
              "type_ptr" : 11
            }
          },
          {
            "cast_kind" : <"NoOp">,
            "base_path" : [
            ]
          },
          {
            "type_ptr" : 11
          }
        )>
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 21,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      22,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/c_cast.cpp",
    "input_kind" : <"IK_CXX">,
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 23
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 24
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 25
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 26
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 27
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 8
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 11
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 28
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 29
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 30
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 31
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 32
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 33
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 34
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 35
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 36
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 37
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 38
        },
        <"Ibm128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 39
        },
        <"Float16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 40
        },
        <"ShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 41
        },
        <"Accum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 42
        },
        <"LongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 43
        },
        <"UShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 44
        },
        <"UAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 45
        },
        <"ULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 46
        },
        <"ShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 47
        },
        <"Fract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 48
        },
        <"LongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 49
        },
        <"UShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 50
        },
        <"UFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 51
        },
        <"ULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 52
        },
        <"SatShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 53
        },
        <"SatAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 54
        },
        <"SatLongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 55
        },
        <"SatUShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 56
        },
        <"SatUAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 57
        },
        <"SatULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 58
        },
        <"SatShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 59
        },
        <"SatFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 60
        },
        <"SatLongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 61
        },
        <"SatUShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 62
        },
        <"SatUFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 63
        },
        <"SatULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 64
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 65
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 66
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 67
        },
        <"Char8">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 68
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 69
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 70
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 71
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 72
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 73
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 74
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 75
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 76
        },
        <"BuiltinFn">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 77
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 78
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 79
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 80
        },
        {
          "type_ptr" : 23
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 81
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 82
        },
        <"Half">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 83
        },
        <"BFloat16">
      )>,
      <"RecordType" : (
        {
          "pointer" : 84
        },
        85
      )>,
      <"PointerType" : (
        {
          "pointer" : 86
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 87
        },
        {
          "type_ptr" : 25,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 88
        },
        {
          "type_ptr" : 25
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 89
        },
        90
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 91
        },
        {
          "element_type" : {
            "type_ptr" : 89
          },
          "stride" : 24
        },
        1
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 92
        },
        {
          "base_type" : 77
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 93
        },
        {
          "type_ptr" : 92
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 94,
          "desugared_type" : 93
        },
        {
          "child_type" : {
            "type_ptr" : 93
          },
          "decl_ptr" : 95
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 22,
          "desugared_type" : 93
        },
        {
          "child_type" : {
            "type_ptr" : 94
          },
          "decl_ptr" : 21
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
