<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
            "file" : "tests/generic_selector_expression.c",
            "line" : 9,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        )
      },
      {
        "name" : "test_typename",
        "qual_name" : [
          "test_typename"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "decl_ptr_with_body" : 7,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 9,
            "source_range" : (
              {
                "line" : 9,
                "column" : 25
              },
              {
                "line" : 15,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 10,
                "source_range" : (
                  {
                    "line" : 10,
                    "column" : 3
                  },
                  {
                    "column" : 9
                  }
                )
              },
              [
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 11,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 8
                      }
                    ),
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "s",
                    "qual_name" : [
                      "s"
                    ]
                  },
                  {
                    "type_ptr" : 12
                  },
                  {
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 13,
                "source_range" : (
                  {
                    "line" : 11,
                    "column" : 3
                  },
                  {
                    "column" : 8
                  }
                )
              },
              [
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 14,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 7
                      }
                    ),
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "y",
                    "qual_name" : [
                      "y"
                    ]
                  },
                  {
                    "type_ptr" : 15
                  },
                  {
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 16,
                "source_range" : (
                  {
                    "line" : 12,
                    "column" : 3
                  },
                  {
                    "column" : 18
                  }
                )
              },
              [
                <"GenericSelectionExpr" : (
                  {
                    "pointer" : 17,
                    "source_range" : (
                      {
                        "column" : 11
                      },
                      {
                        "column" : 11
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 18,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ParenExpr" : (
                          {
                            "pointer" : 19,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 20,
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 11
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 12
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : 11,
                                  "name" : {
                                    "name" : "s",
                                    "qual_name" : [
                                      "s"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 12
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 12
                            },
                            "value_kind" : <"LValue">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 12
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 21,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 22,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 23,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 24,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "4"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 15
                    }
                  },
                  {
                    "value" : <"IntegerLiteral" : (
                      {
                        "pointer" : 22,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 25,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 11
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "x",
                    "qual_name" : [
                      "x"
                    ]
                  },
                  {
                    "type_ptr" : 15
                  },
                  {
                    "init_expr" : <"GenericSelectionExpr" : (
                      {
                        "pointer" : 17,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 18,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                            <"ParenExpr" : (
                              {
                                "pointer" : 19,
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 11
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 20,
                                    "source_range" : (
                                      {
                                        "column" : 11
                                      },
                                      {
                                        "column" : 11
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 12
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : 11,
                                      "name" : {
                                        "name" : "s",
                                        "qual_name" : [
                                          "s"
                                        ]
                                      },
                                      "qual_type" : {
                                        "type_ptr" : 12
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 12
                                },
                                "value_kind" : <"LValue">
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 12
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 21,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 22,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 23,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 24,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "4"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "value" : <"IntegerLiteral" : (
                          {
                            "pointer" : 22,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 26,
                "source_range" : (
                  {
                    "line" : 13,
                    "column" : 3
                  },
                  {
                    "column" : 18
                  }
                )
              },
              [
                <"GenericSelectionExpr" : (
                  {
                    "pointer" : 27,
                    "source_range" : (
                      {
                        "column" : 11
                      },
                      {
                        "column" : 11
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 28,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ParenExpr" : (
                          {
                            "pointer" : 29,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 30,
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 11
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 15
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : 14,
                                  "name" : {
                                    "name" : "y",
                                    "qual_name" : [
                                      "y"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 15
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            },
                            "value_kind" : <"LValue">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 31,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 32,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 33,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>,
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 34,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "4"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 15
                    }
                  },
                  {
                    "value" : <"IntegerLiteral" : (
                      {
                        "pointer" : 33,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "3"
                      }
                    )>
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 35,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 11
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "z",
                    "qual_name" : [
                      "z"
                    ]
                  },
                  {
                    "type_ptr" : 15
                  },
                  {
                    "init_expr" : <"GenericSelectionExpr" : (
                      {
                        "pointer" : 27,
                        "source_range" : (
                          {
                            "column" : 11
                          },
                          {
                            "column" : 11
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 28,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                            <"ParenExpr" : (
                              {
                                "pointer" : 29,
                                "source_range" : (
                                  {
                                    "column" : 11
                                  },
                                  {
                                    "column" : 11
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 30,
                                    "source_range" : (
                                      {
                                        "column" : 11
                                      },
                                      {
                                        "column" : 11
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 15
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : 14,
                                      "name" : {
                                        "name" : "y",
                                        "qual_name" : [
                                          "y"
                                        ]
                                      },
                                      "qual_type" : {
                                        "type_ptr" : 15
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 15
                                },
                                "value_kind" : <"LValue">
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 31,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 32,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 33,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 34,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "4"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "value" : <"IntegerLiteral" : (
                          {
                            "pointer" : 33,
                            "source_range" : (
                              {
                                "column" : 11
                              },
                              {
                                "column" : 11
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"ReturnStmt" : (
              {
                "pointer" : 36,
                "source_range" : (
                  {
                    "line" : 14,
                    "column" : 3
                  },
                  {
                    "column" : 14
                  }
                )
              },
              [
                <"BinaryOperator" : (
                  {
                    "pointer" : 37,
                    "source_range" : (
                      {
                        "column" : 10
                      },
                      {
                        "column" : 14
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 38,
                        "source_range" : (
                          {
                            "column" : 10
                          },
                          {
                            "column" : 10
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 39,
                            "source_range" : (
                              {
                                "column" : 10
                              },
                              {
                                "column" : 10
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : 25,
                              "name" : {
                                "name" : "x",
                                "qual_name" : [
                                  "x"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 15
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 40,
                        "source_range" : (
                          {
                            "column" : 14
                          },
                          {
                            "column" : 14
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 41,
                            "source_range" : (
                              {
                                "column" : 14
                              },
                              {
                                "column" : 14
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 15
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"Var">,
                              "decl_pointer" : 35,
                              "name" : {
                                "name" : "z",
                                "qual_name" : [
                                  "z"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 15
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 15
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 15
                    }
                  },
                  {
                    "kind" : <"Add">
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"EmptyDecl" : (
      {
        "pointer" : 42,
        "source_range" : (
          {
            "line" : 15,
            "column" : 2
          },
          {
            "column" : 2
          }
        )
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 43,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      44,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/generic_selector_expression.c",
    "input_kind" : <"IK_C">,
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 45
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 46
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 12
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 47
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 48
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 15
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 49
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 50
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 51
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 52
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 53
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 54
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 55
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 56
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 57
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 58
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 59
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 60
        },
        <"Float16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 61
        },
        <"ShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 62
        },
        <"Accum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 63
        },
        <"LongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 64
        },
        <"UShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 65
        },
        <"UAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 66
        },
        <"ULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 67
        },
        <"ShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 68
        },
        <"Fract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 69
        },
        <"LongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 70
        },
        <"UShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 71
        },
        <"UFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 72
        },
        <"ULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 73
        },
        <"SatShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 74
        },
        <"SatAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 75
        },
        <"SatLongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 76
        },
        <"SatUShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 77
        },
        <"SatUAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 78
        },
        <"SatULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 79
        },
        <"SatShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 80
        },
        <"SatFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 81
        },
        <"SatLongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 82
        },
        <"SatUShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 83
        },
        <"SatUFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 84
        },
        <"SatULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 85
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 86
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 87
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 88
        },
        <"Char8">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 89
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 90
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 91
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 92
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 93
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 94
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 95
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 96
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 97
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 98
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 99
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 100
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 101
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 102
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 103
        },
        {
          "type_ptr" : 45
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 104
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 105
        },
        <"Half">
      )>,
      <"RecordType" : (
        {
          "pointer" : 106
        },
        107
      )>,
      <"PointerType" : (
        {
          "pointer" : 108
        },
        {
          "type_ptr" : 15,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 109
        },
        {
          "type_ptr" : 12,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 110
        },
        {
          "type_ptr" : 12
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 111
        },
        112
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 113
        },
        {
          "element_type" : {
            "type_ptr" : 111
          },
          "stride" : 24
        },
        1
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 8
        },
        {
          "return_type" : {
            "type_ptr" : 15
          }
        },
        {
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 114
        },
        {
          "base_type" : 100
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 115
        },
        {
          "type_ptr" : 114
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 116,
          "desugared_type" : 115
        },
        {
          "child_type" : {
            "type_ptr" : 115
          },
          "decl_ptr" : 117
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 44,
          "desugared_type" : 115
        },
        {
          "child_type" : {
            "type_ptr" : 116
          },
          "decl_ptr" : 43
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
