<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 6,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 7,
        "parent_pointer" : 1,
        "source_range" : (
          {
            "file" : "tests/new.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 9,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "pod",
        "qual_name" : [
          "pod"
        ]
      },
      8,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 9,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 7,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          8,
          [
          ],
          {
          },
          <"TTK_Struct">,
          {
            "definition_ptr" : 0
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "a",
            "qual_name" : [
              "a",
              "pod"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 12,
            "parent_pointer" : 7,
            "source_range" : (
              {
                "line" : 7,
                "column" : 8
              },
              {
              }
            ),
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "7740115901201927888",
            "is_cpp" : true,
            "is_inline" : true,
            "decl_ptr_with_body" : 12,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 14,
                "source_range" : (
                  {
                  },
                  {
                  }
                )
              },
              [
              ]
            )>
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 15,
            "parent_pointer" : 7,
            "source_range" : (
              {
              },
              {
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 16
          },
          {
            "mangled_name" : "12480848167264656407",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 17,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 18
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
            "is_copy_constructor" : true
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 19,
            "parent_pointer" : 7,
            "source_range" : (
              {
              },
              {
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "pod",
            "qual_name" : [
              "pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 20
          },
          {
            "mangled_name" : "6070336924810484949",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 21,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 22
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
            "is_move_constructor" : true
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 23,
            "parent_pointer" : 7,
            "source_range" : (
              {
              },
              {
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "~pod",
            "qual_name" : [
              "~pod",
              "pod"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "5472746887547415783",
            "is_cpp" : true,
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      <"TTK_Struct">,
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
        "is_pod" : true,
        "is_trivially_copyable" : true,
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 23,
          "name" : {
            "name" : "~pod",
            "qual_name" : [
              "~pod",
              "pod"
            ]
          },
          "qual_type" : {
            "type_ptr" : 13
          }
        }
      }
    )>,
    <"CXXRecordDecl" : (
      {
        "pointer" : 24,
        "parent_pointer" : 1,
        "source_range" : (
          {
            "line" : 11,
            "column" : 1
          },
          {
            "line" : 17,
            "column" : 1
          }
        ),
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "cpplike",
        "qual_name" : [
          "cpplike"
        ]
      },
      25,
      [
        <"CXXRecordDecl" : (
          {
            "pointer" : 26,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 11,
                "column" : 1
              },
              {
                "column" : 8
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          25,
          [
          ],
          {
          },
          <"TTK_Struct">,
          {
            "definition_ptr" : 0
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 27,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 12,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "a",
            "qual_name" : [
              "a",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 28,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 13,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "b",
            "qual_name" : [
              "b",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
          }
        )>,
        <"FieldDecl" : (
          {
            "pointer" : 29,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 14,
                "column" : 3
              },
              {
                "column" : 7
              }
            ),
            "access" : <"Public">
          },
          {
            "name" : "c",
            "qual_name" : [
              "c",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 30
          },
          {
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 31,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 15,
                "column" : 3
              },
              {
                "column" : 28
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 32
          },
          {
            "mangled_name" : "1603213277834459133",
            "is_cpp" : true,
            "decl_ptr_with_body" : 31,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 33,
                "source_range" : (
                  {
                    "column" : 27
                  },
                  {
                    "column" : 28
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 27,
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 11
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 15
                  },
                  {
                    "column" : 19
                  }
                ),
                "init_expr" : <"IntegerLiteral" : (
                  {
                    "pointer" : 34,
                    "source_range" : (
                      {
                        "column" : 17
                      },
                      {
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    }
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "10"
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 28,
                  "name" : {
                    "name" : "b",
                    "qual_name" : [
                      "b",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 11
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 22
                  },
                  {
                    "column" : 25
                  }
                ),
                "init_expr" : <"IntegerLiteral" : (
                  {
                    "pointer" : 35,
                    "source_range" : (
                      {
                        "column" : 24
                      },
                      {
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    }
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "2"
                  }
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 29,
                  "name" : {
                    "name" : "c",
                    "qual_name" : [
                      "c",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 30
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 3
                  },
                  {
                  }
                ),
                "init_expr" : <"CXXConstructExpr" : (
                  {
                    "pointer" : 36,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 30
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : 12,
                      "name" : {
                        "name" : "pod",
                        "qual_name" : [
                          "pod",
                          "pod"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 13
                      }
                    }
                  }
                )>
              }
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 37,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 16,
                "column" : 3
              },
              {
                "column" : 39
              }
            ),
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 38
          },
          {
            "mangled_name" : "5877806831249345467",
            "is_cpp" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 39,
                  "source_range" : (
                    {
                      "column" : 11
                    },
                    {
                      "column" : 15
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "a",
                  "qual_name" : [
                    "a"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 0
                }
              )>,
              <"ParmVarDecl" : (
                {
                  "pointer" : 40,
                  "source_range" : (
                    {
                      "column" : 18
                    },
                    {
                      "column" : 22
                    }
                  ),
                  "is_used" : true,
                  "is_this_declaration_referenced" : true
                },
                {
                  "name" : "b",
                  "qual_name" : [
                    "b"
                  ]
                },
                {
                  "type_ptr" : 11
                },
                {
                  "parm_index_in_function" : 1
                }
              )>
            ],
            "decl_ptr_with_body" : 37,
            "body" : <"CompoundStmt" : (
              {
                "pointer" : 41,
                "source_range" : (
                  {
                    "column" : 38
                  },
                  {
                    "column" : 39
                  }
                )
              },
              [
              ]
            )>
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 27,
                  "name" : {
                    "name" : "a",
                    "qual_name" : [
                      "a",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 11
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 27
                  },
                  {
                    "column" : 30
                  }
                ),
                "init_expr" : <"ImplicitCastExpr" : (
                  {
                    "pointer" : 42,
                    "source_range" : (
                      {
                        "column" : 29
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 43,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 39,
                          "name" : {
                            "name" : "a",
                            "qual_name" : [
                              "a"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 11
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 28,
                  "name" : {
                    "name" : "b",
                    "qual_name" : [
                      "b",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 11
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 33
                  },
                  {
                    "column" : 36
                  }
                ),
                "init_expr" : <"ImplicitCastExpr" : (
                  {
                    "pointer" : 44,
                    "source_range" : (
                      {
                        "column" : 35
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 45,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 40,
                          "name" : {
                            "name" : "b",
                            "qual_name" : [
                              "b"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 11
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              },
              {
                "subject" : <"Member" : {
                  "kind" : <"Field">,
                  "decl_pointer" : 29,
                  "name" : {
                    "name" : "c",
                    "qual_name" : [
                      "c",
                      "cpplike"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 30
                  }
                }>,
                "source_range" : (
                  {
                    "column" : 3
                  },
                  {
                  }
                ),
                "init_expr" : <"CXXConstructExpr" : (
                  {
                    "pointer" : 46,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 30
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : <"CXXConstructor">,
                      "decl_pointer" : 12,
                      "name" : {
                        "name" : "pod",
                        "qual_name" : [
                          "pod",
                          "pod"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 13
                      }
                    }
                  }
                )>
              }
            ]
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 47,
            "parent_pointer" : 24,
            "source_range" : (
              {
                "line" : 11,
                "column" : 8
              },
              {
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 48
          },
          {
            "mangled_name" : "17833126256375871848",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 49,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 50
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
            "is_copy_constructor" : true
          }
        )>,
        <"CXXConstructorDecl" : (
          {
            "pointer" : 51,
            "parent_pointer" : 24,
            "source_range" : (
              {
              },
              {
              }
            ),
            "is_implicit" : true,
            "access" : <"Public">
          },
          {
            "name" : "cpplike",
            "qual_name" : [
              "cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 52
          },
          {
            "mangled_name" : "16041718976592305524",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              <"ParmVarDecl" : (
                {
                  "pointer" : 53,
                  "source_range" : (
                    {
                    },
                    {
                    }
                  )
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 54
                },
                {
                  "parm_index_in_function" : 0
                }
              )>
            ]
          },
          {
            "is_move_constructor" : true
          }
        )>,
        <"CXXDestructorDecl" : (
          {
            "pointer" : 55,
            "parent_pointer" : 24,
            "source_range" : (
              {
              },
              {
              }
            ),
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : <"Public">
          },
          {
            "name" : "~cpplike",
            "qual_name" : [
              "~cpplike",
              "cpplike"
            ]
          },
          {
            "type_ptr" : 13
          },
          {
            "mangled_name" : "11561666268372582658",
            "is_cpp" : true,
            "is_inline" : true
          },
          {
          }
        )>
      ],
      {
      },
      <"TTK_Struct">,
      {
        "definition_ptr" : 24,
        "is_complete_definition" : true
      },
      {
        "is_trivially_copyable" : true,
        "destructor" : {
          "kind" : <"CXXDestructor">,
          "decl_pointer" : 55,
          "name" : {
            "name" : "~cpplike",
            "qual_name" : [
              "~cpplike",
              "cpplike"
            ]
          },
          "qual_type" : {
            "type_ptr" : 13
          }
        }
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 56,
        "source_range" : (
          {
            "line" : 19,
            "column" : 1
          },
          {
            "line" : 35,
            "column" : 1
          }
        )
      },
      {
        "name" : "test",
        "qual_name" : [
          "test"
        ]
      },
      {
        "type_ptr" : 32
      },
      {
        "mangled_name" : "18241244337164948030",
        "is_cpp" : true,
        "decl_ptr_with_body" : 56,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 57,
            "source_range" : (
              {
                "line" : 19,
                "column" : 13
              },
              {
                "line" : 35,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 58,
                "source_range" : (
                  {
                    "line" : 20,
                    "column" : 3
                  },
                  {
                    "column" : 23
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 59,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 22
                      }
                    )
                  },
                  [
                    <"IntegerLiteral" : (
                      {
                        "pointer" : 60,
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "2"
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 61
                    }
                  },
                  {
                    "initializer_expr" : 60
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 62,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 22
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "i",
                    "qual_name" : [
                      "i"
                    ]
                  },
                  {
                    "type_ptr" : 63
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 59,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 22
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 60,
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 61
                        }
                      },
                      {
                        "initializer_expr" : 60
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 64,
                "source_range" : (
                  {
                    "line" : 21,
                    "column" : 3
                  },
                  {
                    "column" : 26
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 65,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 25
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 66,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 67,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 68
                        }
                      },
                      {
                        "cast_kind" : <"IntegralCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 61
                    }
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 66
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 69,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 25
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "i_a",
                    "qual_name" : [
                      "i_a"
                    ]
                  },
                  {
                    "type_ptr" : 63
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 65,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 25
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 66,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 67,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 68
                            }
                          },
                          {
                            "cast_kind" : <"IntegralCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 61
                        }
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 66
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 70,
                "source_range" : (
                  {
                    "line" : 23,
                    "column" : 3
                  },
                  {
                    "column" : 20
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 71,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 17
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 72,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 30
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 12,
                          "name" : {
                            "name" : "pod",
                            "qual_name" : [
                              "pod",
                              "pod"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 13
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 73
                    }
                  },
                  {
                    "initializer_expr" : 72
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 74,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 17
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "p",
                    "qual_name" : [
                      "p"
                    ]
                  },
                  {
                    "type_ptr" : 75
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 71,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 17
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 72,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 30
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 12,
                              "name" : {
                                "name" : "pod",
                                "qual_name" : [
                                  "pod",
                                  "pod"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 13
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 73
                        }
                      },
                      {
                        "initializer_expr" : 72
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 76,
                "source_range" : (
                  {
                    "line" : 24,
                    "column" : 3
                  },
                  {
                    "column" : 26
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 77,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 25
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 78,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 79,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 68
                        }
                      },
                      {
                        "cast_kind" : <"IntegralCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>,
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 80,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 81
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 12,
                          "name" : {
                            "name" : "pod",
                            "qual_name" : [
                              "pod",
                              "pod"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 13
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 73
                    }
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 78,
                    "initializer_expr" : 80
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 82,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 25
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "p_a",
                    "qual_name" : [
                      "p_a"
                    ]
                  },
                  {
                    "type_ptr" : 75
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 77,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 25
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 78,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 79,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 68
                            }
                          },
                          {
                            "cast_kind" : <"IntegralCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 80,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 81
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 12,
                              "name" : {
                                "name" : "pod",
                                "qual_name" : [
                                  "pod",
                                  "pod"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 13
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 73
                        }
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 78,
                        "initializer_expr" : 80
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 83,
                "source_range" : (
                  {
                    "line" : 26,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 84,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 85,
                        "source_range" : (
                          {
                            "column" : 17
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 86,
                            "source_range" : (
                              {
                                "column" : 25
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 87,
                            "source_range" : (
                              {
                                "column" : 28
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 88
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 37,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 38
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 89
                    }
                  },
                  {
                    "initializer_expr" : 85
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 90,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "type_ptr" : 91
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 84,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 85,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 86,
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 87,
                                "source_range" : (
                                  {
                                    "column" : 28
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 88
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 38
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 89
                        }
                      },
                      {
                        "initializer_expr" : 85
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 92,
                "source_range" : (
                  {
                    "line" : 27,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 93,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 94,
                        "source_range" : (
                          {
                            "column" : 27
                          },
                          {
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 95,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "10"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 68
                        }
                      },
                      {
                        "cast_kind" : <"IntegralCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>,
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 96,
                        "source_range" : (
                          {
                            "column" : 19
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 97
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 31,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 32
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 89
                    }
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 94,
                    "initializer_expr" : 96
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 98,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "c_a",
                    "qual_name" : [
                      "c_a"
                    ]
                  },
                  {
                    "type_ptr" : 91
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 93,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 94,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 95,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "10"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 68
                            }
                          },
                          {
                            "cast_kind" : <"IntegralCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 96,
                            "source_range" : (
                              {
                                "column" : 19
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 97
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 31,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 32
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 89
                        }
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 94,
                        "initializer_expr" : 96
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 99,
                "source_range" : (
                  {
                    "line" : 29,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 100,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 101,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 63
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 62,
                          "name" : {
                            "name" : "i",
                            "qual_name" : [
                              "i"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 63
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 63
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "destroyed_type" : {
                  "type_ptr" : 103
                }
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 104,
                "source_range" : (
                  {
                    "line" : 30,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 105,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 106,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 63
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 69,
                          "name" : {
                            "name" : "i_a",
                            "qual_name" : [
                              "i_a"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 63
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 63
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "is_array" : true,
                "destroyed_type" : {
                  "type_ptr" : 103
                }
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 107,
                "source_range" : (
                  {
                    "line" : 31,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 108,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 109,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 75
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 74,
                          "name" : {
                            "name" : "p",
                            "qual_name" : [
                              "p"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 75
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 75
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "destroyed_type" : {
                  "type_ptr" : 110
                }
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 111,
                "source_range" : (
                  {
                    "line" : 32,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 112,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 113,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 75
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 82,
                          "name" : {
                            "name" : "p_a",
                            "qual_name" : [
                              "p_a"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 75
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 75
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "is_array" : true,
                "destroyed_type" : {
                  "type_ptr" : 110
                }
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 114,
                "source_range" : (
                  {
                    "line" : 33,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 115,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 116,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 91
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 90,
                          "name" : {
                            "name" : "c",
                            "qual_name" : [
                              "c"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 91
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 91
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "destroyed_type" : {
                  "type_ptr" : 117
                }
              }
            )>,
            <"CXXDeleteExpr" : (
              {
                "pointer" : 118,
                "source_range" : (
                  {
                    "line" : 34,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 119,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 120,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 91
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"Var">,
                          "decl_pointer" : 98,
                          "name" : {
                            "name" : "c_a",
                            "qual_name" : [
                              "c_a"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 91
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 91
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ],
              {
                "qual_type" : {
                  "type_ptr" : 102
                }
              },
              {
                "is_array" : true,
                "destroyed_type" : {
                  "type_ptr" : 117
                }
              }
            )>
          ]
        )>
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 121,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : (
            {
              "pointer" : 122,
              "source_range" : (
                {
                },
                {
                }
              )
            },
            <"DefaultVisibility">
          )>,
          <"ReturnsNonNullAttr" : (
            {
              "pointer" : 123,
              "source_range" : (
                {
                },
                {
                }
              )
            }
          )>,
          <"AllocSizeAttr" : (
            {
              "pointer" : 124,
              "source_range" : (
                {
                },
                {
                }
              )
            }
          )>
        ]
      },
      {
        "name" : "operator new",
        "qual_name" : [
          "operator new"
        ]
      },
      {
        "type_ptr" : 125
      },
      {
        "mangled_name" : "5103882463850428890",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 126,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 68
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 127,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : (
            {
              "pointer" : 128,
              "source_range" : (
                {
                },
                {
                }
              )
            },
            <"DefaultVisibility">
          )>,
          <"ReturnsNonNullAttr" : (
            {
              "pointer" : 129,
              "source_range" : (
                {
                },
                {
                }
              )
            }
          )>,
          <"AllocSizeAttr" : (
            {
              "pointer" : 130,
              "source_range" : (
                {
                },
                {
                }
              )
            }
          )>
        ]
      },
      {
        "name" : "operator new[]",
        "qual_name" : [
          "operator new[]"
        ]
      },
      {
        "type_ptr" : 125
      },
      {
        "mangled_name" : "5124988689061404296",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 131,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 68
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 132,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : (
            {
              "pointer" : 133,
              "source_range" : (
                {
                },
                {
                }
              )
            },
            <"DefaultVisibility">
          )>
        ]
      },
      {
        "name" : "operator delete",
        "qual_name" : [
          "operator delete"
        ]
      },
      {
        "type_ptr" : 134
      },
      {
        "mangled_name" : "9332647001762808742",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 135,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 136
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 137,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true,
        "is_used" : true,
        "is_this_declaration_referenced" : true,
        "attributes" : [
          <"VisibilityAttr" : (
            {
              "pointer" : 138,
              "source_range" : (
                {
                },
                {
                }
              )
            },
            <"DefaultVisibility">
          )>
        ]
      },
      {
        "name" : "operator delete[]",
        "qual_name" : [
          "operator delete[]"
        ]
      },
      {
        "type_ptr" : 134
      },
      {
        "mangled_name" : "12453587667872411061",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 139,
              "source_range" : (
                {
                },
                {
                }
              ),
              "is_implicit" : true
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 136
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ]
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 140,
        "source_range" : (
          {
            "line" : 38,
            "column" : 1
          },
          {
            "line" : 43,
            "column" : 1
          }
        )
      },
      {
        "name" : "test_c11",
        "qual_name" : [
          "test_c11"
        ]
      },
      {
        "type_ptr" : 32
      },
      {
        "mangled_name" : "6095890702841955930",
        "is_cpp" : true,
        "decl_ptr_with_body" : 140,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 141,
            "source_range" : (
              {
                "line" : 38,
                "column" : 17
              },
              {
                "line" : 43,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 142,
                "source_range" : (
                  {
                    "line" : 39,
                    "column" : 3
                  },
                  {
                    "column" : 32
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 143,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 31
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 144,
                        "source_range" : (
                          {
                            "column" : 21
                          },
                          {
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 145,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 68
                        }
                      },
                      {
                        "cast_kind" : <"IntegralCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>,
                    <"InitListExpr" : (
                      {
                        "pointer" : 146,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 31
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 147,
                            "source_range" : (
                              {
                                "column" : 24
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 148,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 149,
                            "source_range" : (
                              {
                                "column" : 30
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "3"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 150
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 61
                    }
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 144,
                    "initializer_expr" : 146
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 151,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 31
                      }
                    )
                  },
                  {
                    "name" : "i",
                    "qual_name" : [
                      "i"
                    ]
                  },
                  {
                    "type_ptr" : 63
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 143,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 31
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 144,
                            "source_range" : (
                              {
                                "column" : 21
                              },
                              {
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 145,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "3"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 68
                            }
                          },
                          {
                            "cast_kind" : <"IntegralCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>,
                        <"InitListExpr" : (
                          {
                            "pointer" : 146,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                                "column" : 31
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 147,
                                "source_range" : (
                                  {
                                    "column" : 24
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 148,
                                "source_range" : (
                                  {
                                    "column" : 27
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 149,
                                "source_range" : (
                                  {
                                    "column" : 30
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "3"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 150
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 61
                        }
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 144,
                        "initializer_expr" : 146
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 152,
                "source_range" : (
                  {
                    "line" : 40,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 153,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 154,
                        "source_range" : (
                          {
                            "column" : 17
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 155,
                            "source_range" : (
                              {
                                "column" : 25
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "1"
                          }
                        )>,
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 156,
                            "source_range" : (
                              {
                                "column" : 28
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "2"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 88
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 37,
                          "name" : {
                            "name" : "cpplike",
                            "qual_name" : [
                              "cpplike",
                              "cpplike"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 38
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 89
                    }
                  },
                  {
                    "initializer_expr" : 154
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 157,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 29
                      }
                    )
                  },
                  {
                    "name" : "c",
                    "qual_name" : [
                      "c"
                    ]
                  },
                  {
                    "type_ptr" : 91
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 153,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 29
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 154,
                            "source_range" : (
                              {
                                "column" : 17
                              },
                              {
                                "column" : 29
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 155,
                                "source_range" : (
                                  {
                                    "column" : 25
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 156,
                                "source_range" : (
                                  {
                                    "column" : 28
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 88
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 38
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 89
                        }
                      },
                      {
                        "initializer_expr" : 154
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 158,
                "source_range" : (
                  {
                    "line" : 41,
                    "column" : 3
                  },
                  {
                    "column" : 53
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 159,
                    "source_range" : (
                      {
                        "column" : 15
                      },
                      {
                        "column" : 52
                      }
                    )
                  },
                  [
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 160,
                        "source_range" : (
                          {
                            "column" : 27
                          },
                          {
                          }
                        )
                      },
                      [
                        <"IntegerLiteral" : (
                          {
                            "pointer" : 161,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 11
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "4"
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 68
                        }
                      },
                      {
                        "cast_kind" : <"IntegralCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>,
                    <"InitListExpr" : (
                      {
                        "pointer" : 162,
                        "source_range" : (
                          {
                            "column" : 29
                          },
                          {
                            "column" : 52
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 163,
                            "source_range" : (
                              {
                                "column" : 30
                              },
                              {
                                "column" : 35
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 164,
                                "source_range" : (
                                  {
                                    "column" : 31
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "1"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 165,
                                "source_range" : (
                                  {
                                    "column" : 34
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "2"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 88
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 38
                              }
                            }
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 166,
                            "source_range" : (
                              {
                                "column" : 38
                              },
                              {
                                "column" : 43
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 167,
                                "source_range" : (
                                  {
                                    "column" : 39
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "3"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 168,
                                "source_range" : (
                                  {
                                    "column" : 42
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "4"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 88
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 38
                              }
                            }
                          }
                        )>,
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 169,
                            "source_range" : (
                              {
                                "column" : 46
                              },
                              {
                                "column" : 51
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 170,
                                "source_range" : (
                                  {
                                    "column" : 47
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "5"
                              }
                            )>,
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 171,
                                "source_range" : (
                                  {
                                    "column" : 50
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "6"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 88
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 37,
                              "name" : {
                                "name" : "cpplike",
                                "qual_name" : [
                                  "cpplike",
                                  "cpplike"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 38
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 172
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 89
                    }
                  },
                  {
                    "is_array" : true,
                    "array_size_expr" : 160,
                    "initializer_expr" : 162
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 173,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 52
                      }
                    )
                  },
                  {
                    "name" : "c_a",
                    "qual_name" : [
                      "c_a"
                    ]
                  },
                  {
                    "type_ptr" : 91
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 159,
                        "source_range" : (
                          {
                            "column" : 15
                          },
                          {
                            "column" : 52
                          }
                        )
                      },
                      [
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 160,
                            "source_range" : (
                              {
                                "column" : 27
                              },
                              {
                              }
                            )
                          },
                          [
                            <"IntegerLiteral" : (
                              {
                                "pointer" : 161,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                }
                              },
                              {
                                "is_signed" : true,
                                "bitwidth" : 32,
                                "value" : "4"
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 68
                            }
                          },
                          {
                            "cast_kind" : <"IntegralCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>,
                        <"InitListExpr" : (
                          {
                            "pointer" : 162,
                            "source_range" : (
                              {
                                "column" : 29
                              },
                              {
                                "column" : 52
                              }
                            )
                          },
                          [
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 163,
                                "source_range" : (
                                  {
                                    "column" : 30
                                  },
                                  {
                                    "column" : 35
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 164,
                                    "source_range" : (
                                      {
                                        "column" : 31
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "1"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 165,
                                    "source_range" : (
                                      {
                                        "column" : 34
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "2"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 88
                                }
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 38
                                  }
                                }
                              }
                            )>,
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 166,
                                "source_range" : (
                                  {
                                    "column" : 38
                                  },
                                  {
                                    "column" : 43
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 167,
                                    "source_range" : (
                                      {
                                        "column" : 39
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "3"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 168,
                                    "source_range" : (
                                      {
                                        "column" : 42
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "4"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 88
                                }
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 38
                                  }
                                }
                              }
                            )>,
                            <"CXXConstructExpr" : (
                              {
                                "pointer" : 169,
                                "source_range" : (
                                  {
                                    "column" : 46
                                  },
                                  {
                                    "column" : 51
                                  }
                                )
                              },
                              [
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 170,
                                    "source_range" : (
                                      {
                                        "column" : 47
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "5"
                                  }
                                )>,
                                <"IntegerLiteral" : (
                                  {
                                    "pointer" : 171,
                                    "source_range" : (
                                      {
                                        "column" : 50
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    }
                                  },
                                  {
                                    "is_signed" : true,
                                    "bitwidth" : 32,
                                    "value" : "6"
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 88
                                }
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"CXXConstructor">,
                                  "decl_pointer" : 37,
                                  "name" : {
                                    "name" : "cpplike",
                                    "qual_name" : [
                                      "cpplike",
                                      "cpplike"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 38
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 172
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 89
                        }
                      },
                      {
                        "is_array" : true,
                        "array_size_expr" : 160,
                        "initializer_expr" : 162
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 174,
        "source_range" : (
          {
            "line" : 45,
            "column" : 1
          },
          {
            "line" : 47,
            "column" : 1
          }
        ),
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "operator new",
        "qual_name" : [
          "operator new"
        ]
      },
      {
        "type_ptr" : 175
      },
      {
        "mangled_name" : "13351464032276683690",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 176,
              "source_range" : (
                {
                  "line" : 45,
                  "column" : 20
                },
                {
                  "column" : 34
                }
              )
            },
            {
              "name" : "size",
              "qual_name" : [
                "size"
              ]
            },
            {
              "type_ptr" : 68
            },
            {
              "parm_index_in_function" : 0
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : 177,
              "source_range" : (
                {
                  "column" : 40
                },
                {
                  "column" : 46
                }
              )
            },
            {
              "name" : "ptr",
              "qual_name" : [
                "ptr"
              ]
            },
            {
              "type_ptr" : 136
            },
            {
              "parm_index_in_function" : 1
            }
          )>,
          <"ParmVarDecl" : (
            {
              "pointer" : 178,
              "source_range" : (
                {
                  "column" : 51
                },
                {
                  "column" : 57
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "ptr2",
              "qual_name" : [
                "ptr2"
              ]
            },
            {
              "type_ptr" : 136
            },
            {
              "parm_index_in_function" : 2
            }
          )>
        ],
        "decl_ptr_with_body" : 174,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 179,
            "source_range" : (
              {
                "column" : 72
              },
              {
                "line" : 47,
                "column" : 1
              }
            )
          },
          [
            <"ReturnStmt" : (
              {
                "pointer" : 180,
                "source_range" : (
                  {
                    "line" : 46,
                    "column" : 3
                  },
                  {
                    "column" : 10
                  }
                )
              },
              [
                <"ImplicitCastExpr" : (
                  {
                    "pointer" : 181,
                    "source_range" : (
                      {
                      },
                      {
                      }
                    )
                  },
                  [
                    <"DeclRefExpr" : (
                      {
                        "pointer" : 182,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 136
                        },
                        "value_kind" : <"LValue">
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"ParmVar">,
                          "decl_pointer" : 178,
                          "name" : {
                            "name" : "ptr2",
                            "qual_name" : [
                              "ptr2"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 136
                          }
                        }
                      }
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 136
                    }
                  },
                  {
                    "cast_kind" : <"LValueToRValue">,
                    "base_path" : [
                    ]
                  },
                  false
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"EmptyDecl" : (
      {
        "pointer" : 183,
        "source_range" : (
          {
            "line" : 47,
            "column" : 2
          },
          {
          }
        )
      }
    )>,
    <"FunctionDecl" : (
      {
        "pointer" : 184,
        "source_range" : (
          {
            "line" : 49,
            "column" : 1
          },
          {
            "line" : 52,
            "column" : 1
          }
        )
      },
      {
        "name" : "test_placement",
        "qual_name" : [
          "test_placement"
        ]
      },
      {
        "type_ptr" : 185
      },
      {
        "mangled_name" : "1553186570458038035",
        "is_cpp" : true,
        "parameters" : [
          <"ParmVarDecl" : (
            {
              "pointer" : 186,
              "source_range" : (
                {
                  "line" : 49,
                  "column" : 21
                },
                {
                  "column" : 27
                }
              ),
              "is_used" : true,
              "is_this_declaration_referenced" : true
            },
            {
              "name" : "ptr",
              "qual_name" : [
                "ptr"
              ]
            },
            {
              "type_ptr" : 136
            },
            {
              "parm_index_in_function" : 0
            }
          )>
        ],
        "decl_ptr_with_body" : 184,
        "body" : <"CompoundStmt" : (
          {
            "pointer" : 187,
            "source_range" : (
              {
                "column" : 32
              },
              {
                "line" : 52,
                "column" : 1
              }
            )
          },
          [
            <"DeclStmt" : (
              {
                "pointer" : 188,
                "source_range" : (
                  {
                    "line" : 50,
                    "column" : 3
                  },
                  {
                    "column" : 12
                  }
                )
              },
              [
                <"IntegerLiteral" : (
                  {
                    "pointer" : 189,
                    "source_range" : (
                      {
                        "column" : 11
                      },
                      {
                      }
                    )
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 11
                    }
                  },
                  {
                    "is_signed" : true,
                    "bitwidth" : 32,
                    "value" : "1"
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 190,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 11
                      }
                    ),
                    "is_used" : true,
                    "is_this_declaration_referenced" : true
                  },
                  {
                    "name" : "i",
                    "qual_name" : [
                      "i"
                    ]
                  },
                  {
                    "type_ptr" : 11
                  },
                  {
                    "is_init_ice" : true,
                    "init_expr" : <"IntegerLiteral" : (
                      {
                        "pointer" : 189,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 11
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "1"
                      }
                    )>
                  }
                )>
              ]
            )>,
            <"DeclStmt" : (
              {
                "pointer" : 191,
                "source_range" : (
                  {
                    "line" : 51,
                    "column" : 3
                  },
                  {
                    "column" : 30
                  }
                )
              },
              [
                <"CXXNewExpr" : (
                  {
                    "pointer" : 192,
                    "source_range" : (
                      {
                        "column" : 13
                      },
                      {
                        "column" : 27
                      }
                    )
                  },
                  [
                    <"CXXConstructExpr" : (
                      {
                        "pointer" : 193,
                        "source_range" : (
                          {
                          },
                          {
                          }
                        )
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 30
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : <"CXXConstructor">,
                          "decl_pointer" : 12,
                          "name" : {
                            "name" : "pod",
                            "qual_name" : [
                              "pod",
                              "pod"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 13
                          }
                        }
                      }
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 194,
                        "source_range" : (
                          {
                            "column" : 18
                          },
                          {
                          }
                        )
                      },
                      [
                        <"DeclRefExpr" : (
                          {
                            "pointer" : 195,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 136
                            },
                            "value_kind" : <"LValue">
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"ParmVar">,
                              "decl_pointer" : 186,
                              "name" : {
                                "name" : "ptr",
                                "qual_name" : [
                                  "ptr"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 136
                              }
                            }
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 136
                        }
                      },
                      {
                        "cast_kind" : <"LValueToRValue">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>,
                    <"ImplicitCastExpr" : (
                      {
                        "pointer" : 196,
                        "source_range" : (
                          {
                            "column" : 23
                          },
                          {
                            "column" : 24
                          }
                        )
                      },
                      [
                        <"UnaryOperator" : (
                          {
                            "pointer" : 197,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                                "column" : 24
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 198,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 11
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"Var">,
                                  "decl_pointer" : 190,
                                  "name" : {
                                    "name" : "i",
                                    "qual_name" : [
                                      "i"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 11
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 61
                            }
                          },
                          {
                            "kind" : <"AddrOf">
                          }
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 136
                        }
                      },
                      {
                        "cast_kind" : <"BitCast">,
                        "base_path" : [
                        ]
                      },
                      false
                    )>
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 73
                    }
                  },
                  {
                    "initializer_expr" : 193,
                    "placement_args" : [
                      194,
                      196
                    ]
                  }
                )>
              ],
              [
                <"VarDecl" : (
                  {
                    "pointer" : 199,
                    "source_range" : (
                      {
                        "column" : 3
                      },
                      {
                        "column" : 27
                      }
                    )
                  },
                  {
                    "name" : "p",
                    "qual_name" : [
                      "p"
                    ]
                  },
                  {
                    "type_ptr" : 75
                  },
                  {
                    "init_expr" : <"CXXNewExpr" : (
                      {
                        "pointer" : 192,
                        "source_range" : (
                          {
                            "column" : 13
                          },
                          {
                            "column" : 27
                          }
                        )
                      },
                      [
                        <"CXXConstructExpr" : (
                          {
                            "pointer" : 193,
                            "source_range" : (
                              {
                              },
                              {
                              }
                            )
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 30
                            }
                          },
                          {
                            "decl_ref" : {
                              "kind" : <"CXXConstructor">,
                              "decl_pointer" : 12,
                              "name" : {
                                "name" : "pod",
                                "qual_name" : [
                                  "pod",
                                  "pod"
                                ]
                              },
                              "qual_type" : {
                                "type_ptr" : 13
                              }
                            }
                          }
                        )>,
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 194,
                            "source_range" : (
                              {
                                "column" : 18
                              },
                              {
                              }
                            )
                          },
                          [
                            <"DeclRefExpr" : (
                              {
                                "pointer" : 195,
                                "source_range" : (
                                  {
                                  },
                                  {
                                  }
                                )
                              },
                              [
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 136
                                },
                                "value_kind" : <"LValue">
                              },
                              {
                                "decl_ref" : {
                                  "kind" : <"ParmVar">,
                                  "decl_pointer" : 186,
                                  "name" : {
                                    "name" : "ptr",
                                    "qual_name" : [
                                      "ptr"
                                    ]
                                  },
                                  "qual_type" : {
                                    "type_ptr" : 136
                                  }
                                }
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 136
                            }
                          },
                          {
                            "cast_kind" : <"LValueToRValue">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>,
                        <"ImplicitCastExpr" : (
                          {
                            "pointer" : 196,
                            "source_range" : (
                              {
                                "column" : 23
                              },
                              {
                                "column" : 24
                              }
                            )
                          },
                          [
                            <"UnaryOperator" : (
                              {
                                "pointer" : 197,
                                "source_range" : (
                                  {
                                    "column" : 23
                                  },
                                  {
                                    "column" : 24
                                  }
                                )
                              },
                              [
                                <"DeclRefExpr" : (
                                  {
                                    "pointer" : 198,
                                    "source_range" : (
                                      {
                                      },
                                      {
                                      }
                                    )
                                  },
                                  [
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 11
                                    },
                                    "value_kind" : <"LValue">
                                  },
                                  {
                                    "decl_ref" : {
                                      "kind" : <"Var">,
                                      "decl_pointer" : 190,
                                      "name" : {
                                        "name" : "i",
                                        "qual_name" : [
                                          "i"
                                        ]
                                      },
                                      "qual_type" : {
                                        "type_ptr" : 11
                                      }
                                    }
                                  }
                                )>
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 61
                                }
                              },
                              {
                                "kind" : <"AddrOf">
                              }
                            )>
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 136
                            }
                          },
                          {
                            "cast_kind" : <"BitCast">,
                            "base_path" : [
                            ]
                          },
                          false
                        )>
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 73
                        }
                      },
                      {
                        "initializer_expr" : 193,
                        "placement_args" : [
                          194,
                          196
                        ]
                      }
                    )>
                  }
                )>
              ]
            )>
          ]
        )>
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 200,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      201,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/new.cpp",
    "input_kind" : <"IK_CXX">,
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 102
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 202
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 203
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 204
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 205
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 11
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 206
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 207
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 208
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 209
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 210
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 68
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 211
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 212
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 213
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 214
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 215
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 216
        },
        <"Ibm128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 217
        },
        <"Float16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 218
        },
        <"ShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 219
        },
        <"Accum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 220
        },
        <"LongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 221
        },
        <"UShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 222
        },
        <"UAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 223
        },
        <"ULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 224
        },
        <"ShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 225
        },
        <"Fract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 226
        },
        <"LongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 227
        },
        <"UShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 228
        },
        <"UFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 229
        },
        <"ULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 230
        },
        <"SatShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 231
        },
        <"SatAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 232
        },
        <"SatLongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 233
        },
        <"SatUShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 234
        },
        <"SatUAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 235
        },
        <"SatULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 236
        },
        <"SatShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 237
        },
        <"SatFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 238
        },
        <"SatLongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 239
        },
        <"SatUShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 240
        },
        <"SatUFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 241
        },
        <"SatULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 242
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 243
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 244
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 245
        },
        <"Char8">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 246
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 247
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 248
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 249
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 250
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 251
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 252
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 253
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 254
        },
        <"BuiltinFn">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 255
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 256
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 257
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 136
        },
        {
          "type_ptr" : 102
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 258
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 259
        },
        <"Half">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 260
        },
        <"BFloat16">
      )>,
      <"RecordType" : (
        {
          "pointer" : 261
        },
        262
      )>,
      <"PointerType" : (
        {
          "pointer" : 263
        },
        {
          "type_ptr" : 11,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 264
        },
        {
          "type_ptr" : 203,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 265
        },
        {
          "type_ptr" : 203
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 266
        },
        267
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 268
        },
        {
          "element_type" : {
            "type_ptr" : 266
          },
          "stride" : 24
        },
        1
      )>,
      <"RecordType" : (
        {
          "pointer" : 8
        },
        7
      )>,
      <"RecordType" : (
        {
          "pointer" : 25
        },
        24
      )>,
      <"ElaboratedType" : (
        {
          "pointer" : 30,
          "desugared_type" : 8
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 269
        },
        {
          "type_ptr" : 25
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 32
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 38
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 11
            },
            {
              "type_ptr" : 11
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 270
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 271
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 18
        },
        {
          "type_ptr" : 30,
          "is_const" : true
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 272
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 271
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 16
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 18
            }
          ]
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 273
        },
        {
          "type_ptr" : 8
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 22
        },
        {
          "type_ptr" : 30
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 274
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 273
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 20
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 22
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 13
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 275
        },
        {
          "type_ptr" : 8
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 73
        },
        {
          "type_ptr" : 30
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 276
        },
        {
          "type_ptr" : 8
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 277
        },
        {
          "type_ptr" : 278
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 61
        },
        {
          "type_ptr" : 11
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 125
        },
        {
          "return_type" : {
            "type_ptr" : 136
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 185
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 136
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 134
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 136
            }
          ]
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 279
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 280
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 281,
          "desugared_type" : 280
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 282
        },
        {
          "type_ptr" : 279
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 283
        },
        {
          "type_ptr" : 281
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 103,
          "desugared_type" : 11
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 63
        },
        {
          "type_ptr" : 103
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 284
        },
        {
          "element_type" : {
            "type_ptr" : 11
          },
          "stride" : 4
        },
        10
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 285
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 286,
          "desugared_type" : 285
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 287
        },
        {
          "type_ptr" : 286
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 288
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 289,
          "desugared_type" : 288
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 290
        },
        {
          "type_ptr" : 289
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 110,
          "desugared_type" : 8
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 75
        },
        {
          "type_ptr" : 110
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 291
        },
        {
          "element_type" : {
            "type_ptr" : 8
          },
          "stride" : 4
        },
        10
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 81
        },
        {
          "element_type" : {
            "type_ptr" : 30
          },
          "stride" : 4
        },
        10
      )>,
      <"PointerType" : (
        {
          "pointer" : 292
        },
        {
          "type_ptr" : 291
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 293
        },
        {
          "type_ptr" : 81
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 294
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 295
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 296,
          "desugared_type" : 295
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 297
        },
        {
          "type_ptr" : 296
        }
      )>,
      <"ElaboratedType" : (
        {
          "pointer" : 88,
          "desugared_type" : 25
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 89
        },
        {
          "type_ptr" : 88
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 298
        },
        {
          "type_ptr" : 25,
          "is_const" : true
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 50
        },
        {
          "type_ptr" : 88,
          "is_const" : true
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 299
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 298
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 48
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 50
            }
          ]
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 300
        },
        {
          "type_ptr" : 25
        }
      )>,
      <"RValueReferenceType" : (
        {
          "pointer" : 54
        },
        {
          "type_ptr" : 88
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 301
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 300
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 52
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 54
            }
          ]
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 302
        },
        {
          "type_ptr" : 25
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 303
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 304,
          "desugared_type" : 303
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 305
        },
        {
          "type_ptr" : 304
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 117,
          "desugared_type" : 25
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 91
        },
        {
          "type_ptr" : 117
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 306
        },
        {
          "element_type" : {
            "type_ptr" : 25
          },
          "stride" : 12
        },
        10
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 97
        },
        {
          "element_type" : {
            "type_ptr" : 88
          },
          "stride" : 12
        },
        10
      )>,
      <"PointerType" : (
        {
          "pointer" : 307
        },
        {
          "type_ptr" : 306
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 308
        },
        {
          "type_ptr" : 97
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 309
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 310
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 311,
          "desugared_type" : 310
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 312
        },
        {
          "type_ptr" : 311
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 150
        },
        {
          "element_type" : {
            "type_ptr" : 11
          },
          "stride" : 4
        },
        3
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 313
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 314,
          "desugared_type" : 313
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 315
        },
        {
          "type_ptr" : 314
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 316
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 317,
          "desugared_type" : 316
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 318
        },
        {
          "type_ptr" : 317
        }
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 319
        },
        {
          "element_type" : {
            "type_ptr" : 25
          },
          "stride" : 12
        },
        4
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 172
        },
        {
          "element_type" : {
            "type_ptr" : 88
          },
          "stride" : 12
        },
        4
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 320
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 321,
          "desugared_type" : 320
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 322
        },
        {
          "type_ptr" : 321
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 323
        },
        {
          "return_type" : {
            "type_ptr" : 136
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            },
            {
              "type_ptr" : 136
            },
            {
              "type_ptr" : 136
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 175
        },
        {
          "return_type" : {
            "type_ptr" : 136
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            },
            {
              "type_ptr" : 136
            },
            {
              "type_ptr" : 136
            }
          ]
        }
      )>,
      <"LValueReferenceType" : (
        {
          "pointer" : 324
        },
        {
          "type_ptr" : 11
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 325
        },
        {
          "return_type" : {
            "type_ptr" : 102
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 136
            },
            {
              "type_ptr" : 136
            },
            {
              "type_ptr" : 136
            }
          ]
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 326
        }
      )>,
      <"AutoType" : (
        {
          "pointer" : 327,
          "desugared_type" : 326
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 328
        },
        {
          "type_ptr" : 327
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 329
        },
        {
          "base_type" : 255
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 330
        },
        {
          "type_ptr" : 329
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 331,
          "desugared_type" : 330
        },
        {
          "child_type" : {
            "type_ptr" : 330
          },
          "decl_ptr" : 332
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 201,
          "desugared_type" : 330
        },
        {
          "child_type" : {
            "type_ptr" : 331
          },
          "decl_ptr" : 200
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
