<"TranslationUnitDecl" : (
  {
    "pointer" : 1,
    "source_range" : (
      {
      },
      {
      }
    )
  },
  [
    <"TypedefDecl" : (
      {
        "pointer" : 2,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 3,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 4,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 5,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      6,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 7,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      0,
      {
      }
    )>,
    <"ObjCInterfaceDecl" : (
      {
        "pointer" : 8,
        "parent_pointer" : 1,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 9,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 10,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 11,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    )>,
    <"FunctionTemplateDecl" : (
      {
        "pointer" : 12,
        "source_range" : (
          {
            "file" : "tests/objcpp_template_unboxing.mm",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        )
      },
      {
        "name" : "box",
        "qual_name" : [
          "box"
        ]
      },
      {
      }
    )>,
    <"TypedefDecl" : (
      {
        "pointer" : 13,
        "source_range" : (
          {
          },
          {
          }
        ),
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      14,
      {
      }
    )>
  ],
  {
  },
  {
    "input_path" : "tests/objcpp_template_unboxing.mm",
    "input_kind" : <"IK_ObjCXX">,
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "is_objc_arc_on" : true,
    "types" : [
      <"BuiltinType" : (
        {
          "pointer" : 15
        },
        <"Void">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 16
        },
        <"Bool">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 17
        },
        <"Char_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 18
        },
        <"SChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 19
        },
        <"Short">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 20
        },
        <"Int">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 21
        },
        <"Long">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 22
        },
        <"LongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 23
        },
        <"UChar">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 24
        },
        <"UShort">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 25
        },
        <"UInt">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 26
        },
        <"ULong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 27
        },
        <"ULongLong">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 28
        },
        <"Float">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 29
        },
        <"Double">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 30
        },
        <"LongDouble">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 31
        },
        <"Float128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 32
        },
        <"Float16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 33
        },
        <"ShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 34
        },
        <"Accum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 35
        },
        <"LongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 36
        },
        <"UShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 37
        },
        <"UAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 38
        },
        <"ULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 39
        },
        <"ShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 40
        },
        <"Fract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 41
        },
        <"LongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 42
        },
        <"UShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 43
        },
        <"UFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 44
        },
        <"ULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 45
        },
        <"SatShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 46
        },
        <"SatAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 47
        },
        <"SatLongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 48
        },
        <"SatUShortAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 49
        },
        <"SatUAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 50
        },
        <"SatULongAccum">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 51
        },
        <"SatShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 52
        },
        <"SatFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 53
        },
        <"SatLongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 54
        },
        <"SatUShortFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 55
        },
        <"SatUFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 56
        },
        <"SatULongFract">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 57
        },
        <"Int128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 58
        },
        <"UInt128">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 59
        },
        <"WChar_S">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 60
        },
        <"Char8">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 61
        },
        <"Char16">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 62
        },
        <"Char32">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 63
        },
        <"Dependent">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 64
        },
        <"Overload">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 65
        },
        <"BoundMember">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 66
        },
        <"PseudoObject">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 67
        },
        <"UnknownAny">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 68
        },
        <"ARCUnbridgedCast">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 69
        },
        <"BuiltinFn">
      )>,
      <"ComplexType" : (
        {
          "pointer" : 70
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 71
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 72
        }
      )>,
      <"ComplexType" : (
        {
          "pointer" : 73
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 74
        },
        <"ObjCId">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 75
        },
        <"ObjCClass">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 76
        },
        <"ObjCSel">
      )>,
      <"PointerType" : (
        {
          "pointer" : 77
        },
        {
          "type_ptr" : 15
        }
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 78
        },
        <"NullPtr">
      )>,
      <"BuiltinType" : (
        {
          "pointer" : 79
        },
        <"Half">
      )>,
      <"PointerType" : (
        {
          "pointer" : 80
        },
        {
          "type_ptr" : 76
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 81
        },
        {
          "base_type" : 74
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 82
        },
        {
          "type_ptr" : 81
        }
      )>,
      <"ObjCObjectType" : (
        {
          "pointer" : 83
        },
        {
          "base_type" : 75
        }
      )>,
      <"ObjCObjectPointerType" : (
        {
          "pointer" : 84
        },
        {
          "type_ptr" : 83
        }
      )>,
      <"ObjCInterfaceType" : (
        {
          "pointer" : 85
        },
        8
      )>,
      <"RecordType" : (
        {
          "pointer" : 86
        },
        87
      )>,
      <"PointerType" : (
        {
          "pointer" : 88
        },
        {
          "type_ptr" : 20,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 89
        },
        {
          "type_ptr" : 17,
          "is_const" : true
        }
      )>,
      <"PointerType" : (
        {
          "pointer" : 90
        },
        {
          "type_ptr" : 17
        }
      )>,
      <"RecordType" : (
        {
          "pointer" : 91
        },
        92
      )>,
      <"ConstantArrayType" : (
        {
          "pointer" : 93
        },
        {
          "element_type" : {
            "type_ptr" : 91
          },
          "stride" : 24
        },
        1
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 94
        }
      )>,
      <"TemplateTypeParmType" : (
        {
          "pointer" : 95
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 96
        },
        {
          "return_type" : {
            "type_ptr" : 77
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 94
            }
          ]
        }
      )>,
      <"FunctionProtoType" : (
        {
          "pointer" : 97
        },
        {
          "return_type" : {
            "type_ptr" : 77
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 95
            }
          ]
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 6,
          "desugared_type" : 82
        },
        {
          "child_type" : {
            "type_ptr" : 82
          },
          "decl_ptr" : 5
        }
      )>,
      <"TypedefType" : (
        {
          "pointer" : 14,
          "desugared_type" : 82
        },
        {
          "child_type" : {
            "type_ptr" : 6
          },
          "decl_ptr" : 13
        }
      )>,
      <"NoneType" : (
        {
          "pointer" : 0
        }
      )>
    ]
  }
)>
