tests_dependencies = [
    '//infer/lib/java/android:android',
    '//dependencies/java/guava:guava',
    '//dependencies/java/junit:hamcrest',
    '//dependencies/java/jackson:jackson',
    '//dependencies/java/jsr-305:jsr-305',
    '//dependencies/java/junit:junit',
    '//dependencies/java/opencsv:opencsv',
    '//infer/tests/utils:utils',
    '//infer/tests/codetoanalyze/java/crashcontext:crashcontext',
    '//infer/tests/codetoanalyze/java/infer:infer',
]

# ############### ObjC endtoend tests ########################
java_test(
  name='objc_endtoend_tests',
  deps=[
      '//infer/tests/endtoend/objc/infer:infer',
      '//infer/tests/endtoend/objc/linters:linters',
  ],
  visibility=[
    'PUBLIC',
  ],
)

# ############### ObjCpp endtoend tests ########################
java_test(
  name='objcpp_endtoend_tests',
  deps=[
      '//infer/tests/endtoend/objcpp/infer:infer',
      '//infer/tests/endtoend/objcpp/linters:linters',
      '//infer/tests/endtoend/objcpp/componentkit:componentkit',
  ],
  visibility=[
    'PUBLIC',
  ],
)

# ############### Java endtoend tests ########################
java_test(
    name='java_endtoend_tests',
    deps=[
        '//infer/tests/endtoend/java/infer:infer',
        '//infer/tests/endtoend/java/crashcontext:crashcontext',
        '//infer/tests/endtoend/java/harness:harness',
    ],
    visibility=[
        'PUBLIC',
    ],
)

# ############### Linters tests ########################

java_test(
    name='linters',
    deps=[
        '//infer/tests/endtoend/objc/linters:linters',
        '//infer/tests/endtoend/objcpp/linters:linters',
    ],
)

# ############### ComponentKit tests ########################

java_test(
    name='componentkit',
    deps=[
        '//infer/tests/endtoend/objcpp/componentkit:componentkit',
    ],
)
