# Copyright (c) 2016 - present Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

TESTS_DIR = ../..
ROOT_DIR = $(TESTS_DIR)/../..

ANALYZER = checkers
INFER_OPTIONS =
INFERPRINT_OPTIONS = --issues-tests

PROJECT_ROOT = $(ROOT_DIR)/examples
SOURCES = $(PROJECT_ROOT)/Hello.java

include $(TESTS_DIR)/javac.make
