# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR = ../..
ROOT_DIR = $(TESTS_DIR)/../..

INFER_OPTIONS =
INFERPRINT_OPTIONS = --issues-tests

PROJECT_ROOT = $(ROOT_DIR)/examples
SOURCES = $(PROJECT_ROOT)/Hello.java
TEST_CLASSPATH = $(JAVA_BUILTINS_DIR)

include $(TESTS_DIR)/javac.make
