codetoanalyze/erlang/topl/less/topl_less.erl, test_b_Bad/0, 0, TOPL_ERROR, no_bucket, ERROR, [[0] call to topl_less:bar/1 (codetoanalyze/erlang/topl/less/property.topl:3:3-92)]
codetoanalyze/erlang/topl/less/topl_less.erl, test_c_Bad/0, 0, TOPL_ERROR, no_bucket, ERROR, [[0] call to topl_less:bar/1 (codetoanalyze/erlang/topl/less/property.topl:3:3-92)]
codetoanalyze/erlang/topl/less/topl_less.erl, test_e_Bad/0, 0, TOPL_ERROR, no_bucket, ERROR, [[0] call to topl_less:bar/1 (codetoanalyze/erlang/topl/less/property.topl:3:3-92)]
