/hello/Hello.class, hello.Hello.mayCauseNPE():void, 3, NULL_DEREFERENCE, no_bucket, ERROR, [start of procedure mayCauseNPE()]
/hello/Hello.class, hello.Hello.mayLeakResource():void, 6, RESOURCE_LEAK, no_bucket, ERROR, [start of procedure mayLeakResource(),Taking false branch]
/hello/Hello.class, hello.Hello.twoResources():void, 14, RESOURCE_LEAK, no_bucket, ERROR, [start of procedure twoResources(),Taking true branch,exception java.io.IOException]
