# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

build/%.o: %.cpp $(HEADERS) $(CLANG)
	@mkdir -p $$(dirname $@)
	$(CXX) $(CFLAGS) -c $< -o $@
