# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR = ../../..
INFER_OPTIONS = --datalog-only
INFERPRINT_OPTIONS = --issues-tests-fields=file,line,bug_type,qualifier --issues-tests
SOURCES = $(wildcard *.java)

include $(TESTS_DIR)/javac.make
