# Copyright (c) 2016-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR=../../..

CLANG_OPTIONS = -c
INFER_OPTIONS =

SOURCES = \
  $(wildcard */*.c) \
  $(wildcard */*.cpp) \

include $(TESTS_DIR)/clang-frontend.make
