["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/comments.c",
            "line" : 8,
            "column" : 1
          },
          {
            "line" : 11,
            "column" : 1
          }
        ]
      },
      {
        "name" : "foo",
        "qual_name" : [
          "foo"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "decl_ptr_with_body" : 7,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 8,
                "column" : 12
              },
              {
                "line" : 11,
                "column" : 1
              }
            ]
          },
          [
          ]
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 10,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      11,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/comments.c",
    "input_kind" : "IK_C",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 12
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 13
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 14
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 15
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 16
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 51
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 57
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 65
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 66
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 67
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 68
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 72
        },
        {
          "type_ptr" : 12
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 73
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 74
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 75
        },
        76
      ]],
      ["PointerType" , [
        {
          "pointer" : 77
        },
        {
          "type_ptr" : 17,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 78
        },
        {
          "type_ptr" : 14,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 79
        },
        {
          "type_ptr" : 14
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 80
        },
        81
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 82
        },
        {
          "element_type" : {
            "type_ptr" : 80
          },
          "stride" : 24
        },
        1
      ]],
      ["FunctionNoProtoType" , [
        {
          "pointer" : 8
        },
        {
          "return_type" : {
            "type_ptr" : 12
          }
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 83
        },
        {
          "base_type" : 69
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 84
        },
        {
          "type_ptr" : 83
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 85,
          "desugared_type" : 84
        },
        {
          "child_type" : {
            "type_ptr" : 84
          },
          "decl_ptr" : 86
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 11,
          "desugared_type" : 84
        },
        {
          "child_type" : {
            "type_ptr" : 85
          },
          "decl_ptr" : 10
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
