["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 7,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "file" : "tests/inheriting_constructor.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      8,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 9,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 7,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          8,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 11
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "16649826940628685907",
            "is_cpp" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 12,
                  "source_range" : [
                    {
                      "column" : 5
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 13,
                  "is_trivially_copyable" : true
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "decl_ptr_with_body" : 10,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 14,
                "source_range" : [
                  {
                    "column" : 10
                  },
                  {
                    "column" : 11
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 15,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 14
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "foo",
            "qual_name" : [
              "foo",
              "A"
            ]
          },
          {
            "type_ptr" : 16
          },
          {
            "mangled_name" : "11285596688767843576",
            "is_cpp" : true,
            "decl_ptr_with_body" : 15,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 17,
                "source_range" : [
                  {
                    "column" : 13
                  },
                  {
                    "column" : 14
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 18,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 7,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 19
          },
          {
            "mangled_name" : "6367731417382615745",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 20,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 21
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 22,
            "parent_pointer" : 7,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 23
          },
          {
            "mangled_name" : "17956886967408801671",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 24,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 25
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 26,
            "parent_pointer" : 7,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          {
            "type_ptr" : 27
          },
          {
            "mangled_name" : "6691652126532499765",
            "is_cpp" : true,
            "is_inline" : true
          },
          {
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 26,
          "name" : {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          "qual_type" : {
            "type_ptr" : 27
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 28,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 12,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      29,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 30,
            "parent_pointer" : 28,
            "source_range" : [
              {
                "line" : 12,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          29,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["UsingDecl" , [
          {
            "pointer" : 31,
            "source_range" : [
              {
                "line" : 13,
                "column" : 3
              },
              {
                "column" : 12
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          }
        ]],
        ["ConstructorUsingShadowDecl" , [
          {
            "pointer" : 32,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          }
        ]],
        ["ConstructorUsingShadowDecl" , [
          {
            "pointer" : 33,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          }
        ]],
        ["ConstructorUsingShadowDecl" , [
          {
            "pointer" : 34,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 35,
            "parent_pointer" : 28,
            "source_range" : [
              {
                "line" : 12,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 36
          },
          {
            "mangled_name" : "8928078380412315851",
            "is_cpp" : true,
            "is_inline" : true,
            "is_deleted" : true
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 37,
            "parent_pointer" : 28,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 38
          },
          {
            "mangled_name" : "6925252787601137710",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 39,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 40
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 41,
            "parent_pointer" : 28,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 42
          },
          {
            "mangled_name" : "17350102287109130674",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 43,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 44
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 45,
            "parent_pointer" : 28,
            "source_range" : [
              {
                "line" : 13,
                "column" : 12
              },
              {
              }
            ],
            "is_implicit" : true,
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "B"
            ]
          },
          {
            "type_ptr" : 46
          },
          {
            "mangled_name" : "5352909623164416057",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 47,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 13,
                  "is_trivially_copyable" : true
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "decl_ptr_with_body" : 45,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 48,
                "source_range" : [
                  {
                  },
                  {
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  8,
                  false
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXInheritedCtorInitExpr" , [
                  {
                    "pointer" : 49,
                    "source_range" : [
                      {
                      },
                      {
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 8,
                      "is_trivially_copyable" : true
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 10,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "A"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              }
            ]
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 28,
        "is_complete_definition" : true
      },
      {
        "bases" : [
          8
        ]
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 50,
        "source_range" : [
          {
            "line" : 16,
            "column" : 1
          },
          {
            "column" : 22
          }
        ]
      },
      {
        "name" : "main",
        "qual_name" : [
          "main"
        ]
      },
      {
        "type_ptr" : 51
      },
      {
        "is_cpp" : true,
        "decl_ptr_with_body" : 50,
        "body" : ["CompoundStmt" , [
          {
            "pointer" : 52,
            "source_range" : [
              {
                "column" : 12
              },
              {
                "column" : 22
              }
            ]
          },
          [
            ["DeclStmt" , [
              {
                "pointer" : 53,
                "source_range" : [
                  {
                    "column" : 14
                  },
                  {
                    "column" : 20
                  }
                ]
              },
              [
                ["CXXConstructExpr" , [
                  {
                    "pointer" : 54,
                    "source_range" : [
                      {
                        "column" : 16
                      },
                      {
                        "column" : 19
                      }
                    ]
                  },
                  [
                    ["IntegerLiteral" , [
                      {
                        "pointer" : 55,
                        "source_range" : [
                          {
                            "column" : 18
                          },
                          {
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 13,
                          "is_trivially_copyable" : true
                        }
                      },
                      {
                        "is_signed" : true,
                        "bitwidth" : 32,
                        "value" : "5"
                      }
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 29,
                      "is_trivially_copyable" : true
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 45,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "B"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 46
                      }
                    }
                  }
                ]]
              ],
              [
                ["VarDecl" , [
                  {
                    "pointer" : 56,
                    "source_range" : [
                      {
                        "column" : 14
                      },
                      {
                        "column" : 19
                      }
                    ]
                  },
                  {
                    "name" : "b",
                    "qual_name" : [
                      "b"
                    ]
                  },
                  {
                    "type_ptr" : 29,
                    "is_trivially_copyable" : true
                  },
                  {
                    "init_expr" : ["CXXConstructExpr" , [
                      {
                        "pointer" : 54,
                        "source_range" : [
                          {
                            "column" : 16
                          },
                          {
                            "column" : 19
                          }
                        ]
                      },
                      [
                        ["IntegerLiteral" , [
                          {
                            "pointer" : 55,
                            "source_range" : [
                              {
                                "column" : 18
                              },
                              {
                              }
                            ]
                          },
                          [
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 13,
                              "is_trivially_copyable" : true
                            }
                          },
                          {
                            "is_signed" : true,
                            "bitwidth" : 32,
                            "value" : "5"
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 29,
                          "is_trivially_copyable" : true
                        }
                      },
                      {
                        "decl_ref" : {
                          "kind" : "CXXConstructor",
                          "decl_pointer" : 45,
                          "name" : {
                            "name" : "A",
                            "qual_name" : [
                              "A",
                              "B"
                            ]
                          },
                          "qual_type" : {
                            "type_ptr" : 46
                          }
                        }
                      }
                    ]]
                  }
                ]]
              ]
            ]]
          ]
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 57,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      58,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/inheriting_constructor.cpp",
    "input_kind" : "IK_CXX",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 13
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 65
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 66
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 67
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 68
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 72
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 73
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 74
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "Ibm128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 76
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 78
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 80
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 81
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 82
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 83
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 84
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 85
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 86
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 87
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 88
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 89
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 90
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 91
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 92
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 93
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 94
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 95
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 96
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 97
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 98
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 99
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 100
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 101
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 102
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 103
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 104
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 105
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 106
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 107
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 108
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 109
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 110
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 111
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 112
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 113
        },
        "BuiltinFn"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 114
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 115
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 116
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 117
        },
        {
          "type_ptr" : 59
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 118
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 119
        },
        "Half"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 120
        },
        "BFloat16"
      ]],
      ["RecordType" , [
        {
          "pointer" : 121
        },
        122
      ]],
      ["PointerType" , [
        {
          "pointer" : 123
        },
        {
          "type_ptr" : 13,
          "is_const" : true,
          "is_trivially_copyable" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 124
        },
        {
          "type_ptr" : 61,
          "is_const" : true,
          "is_trivially_copyable" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 125
        },
        {
          "type_ptr" : 61,
          "is_trivially_copyable" : true
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 126
        },
        127
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 128
        },
        {
          "element_type" : {
            "type_ptr" : 126,
            "is_trivially_copyable" : true
          },
          "stride" : 24
        },
        1
      ]],
      ["RecordType" , [
        {
          "pointer" : 8
        },
        7
      ]],
      ["PointerType" , [
        {
          "pointer" : 129
        },
        {
          "type_ptr" : 8,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 11
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 13,
              "is_trivially_copyable" : true
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 16
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 29
        },
        28
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 21
        },
        {
          "type_ptr" : 8,
          "is_const" : true,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 130
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 21
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 19
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 21
            }
          ]
        }
      ]],
      ["RValueReferenceType" , [
        {
          "pointer" : 25
        },
        {
          "type_ptr" : 8,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 131
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 25
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 23
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 25
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 36
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 40
        },
        {
          "type_ptr" : 29,
          "is_const" : true,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 132
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 40
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 38
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 40
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 27
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
        }
      ]],
      ["RValueReferenceType" , [
        {
          "pointer" : 44
        },
        {
          "type_ptr" : 29,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 133
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 44
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 42
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 44
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 51
        },
        {
          "return_type" : {
            "type_ptr" : 13,
            "is_trivially_copyable" : true
          }
        },
        {
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 134
        },
        {
          "type_ptr" : 125,
          "is_trivially_copyable" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 135
        },
        {
          "type_ptr" : 29,
          "is_trivially_copyable" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 136
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 13,
              "is_trivially_copyable" : true
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 46
        },
        {
          "return_type" : {
            "type_ptr" : 59
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 13,
              "is_trivially_copyable" : true
            }
          ]
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 137
        },
        {
          "base_type" : 114
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 138
        },
        {
          "type_ptr" : 137
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 139,
          "desugared_type" : 138
        },
        {
          "child_type" : {
            "type_ptr" : 138,
            "is_trivially_copyable" : true
          },
          "decl_ptr" : 140
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 58,
          "desugared_type" : 138
        },
        {
          "child_type" : {
            "type_ptr" : 139,
            "is_trivially_copyable" : true
          },
          "decl_ptr" : 57
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
