["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["VarDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/materialize_temporary.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "column" : 16
          }
        ]
      },
      {
        "name" : "r",
        "qual_name" : [
          "r"
        ]
      },
      {
        "type_ptr" : 8
      },
      {
        "is_global" : true,
        "is_init_ice" : true,
        "init_expr" : ["ExprWithCleanups" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
              },
              {
              }
            ]
          },
          [
            ["MaterializeTemporaryExpr" , [
              {
                "pointer" : 10,
                "source_range" : [
                  {
                  },
                  {
                  }
                ]
              },
              [
                ["ImplicitCastExpr" , [
                  {
                    "pointer" : 11,
                    "source_range" : [
                      {
                      },
                      {
                      }
                    ]
                  },
                  [
                    ["FloatingLiteral" , [
                      {
                        "pointer" : 12,
                        "source_range" : [
                          {
                          },
                          {
                          }
                        ]
                      },
                      [
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 13
                        }
                      },
                      "1"
                    ]]
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 14,
                      "is_const" : true
                    }
                  },
                  {
                    "cast_kind" : "FloatingToIntegral",
                    "base_path" : [
                    ]
                  },
                  false
                ]]
              ],
              {
                "qual_type" : {
                  "type_ptr" : 14,
                  "is_const" : true
                },
                "value_kind" : "LValue"
              },
              {
                "decl_ref" : {
                  "kind" : "Var",
                  "decl_pointer" : 7,
                  "name" : {
                    "name" : "r",
                    "qual_name" : [
                      "r"
                    ]
                  },
                  "qual_type" : {
                    "type_ptr" : 8
                  }
                }
              }
            ]]
          ],
          {
            "qual_type" : {
              "type_ptr" : 14,
              "is_const" : true
            },
            "value_kind" : "LValue"
          },
          {
          }
        ]]
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 15,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      16,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/materialize_temporary.cpp",
    "input_kind" : "IK_CXX",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 14
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 13
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "Ibm128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 51
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 57
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 65
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 66
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 67
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 68
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "BuiltinFn"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 72
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 73
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 74
        },
        {
          "type_ptr" : 17
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 76
        },
        "Half"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "BFloat16"
      ]],
      ["RecordType" , [
        {
          "pointer" : 78
        },
        79
      ]],
      ["PointerType" , [
        {
          "pointer" : 80
        },
        {
          "type_ptr" : 14,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 81
        },
        {
          "type_ptr" : 19,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 82
        },
        {
          "type_ptr" : 19
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 83
        },
        84
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 85
        },
        {
          "element_type" : {
            "type_ptr" : 83
          },
          "stride" : 24
        },
        1
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 8
        },
        {
          "type_ptr" : 14,
          "is_const" : true
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 86
        },
        {
          "base_type" : 71
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 87
        },
        {
          "type_ptr" : 86
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 88,
          "desugared_type" : 87
        },
        {
          "child_type" : {
            "type_ptr" : 87
          },
          "decl_ptr" : 89
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 16,
          "desugared_type" : 87
        },
        {
          "child_type" : {
            "type_ptr" : 88
          },
          "decl_ptr" : 15
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
