["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["NamespaceDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/namespace_decl.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        ]
      },
      {
        "name" : "Q",
        "qual_name" : [
          "Q"
        ]
      },
      [
        ["NamespaceDecl" , [
          {
            "pointer" : 8,
            "source_range" : [
              {
                "line" : 8,
                "column" : 1
              },
              {
                "line" : 9,
                "column" : 1
              }
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
          }
        ]],
        ["NamespaceDecl" , [
          {
            "pointer" : 9,
            "source_range" : [
              {
                "line" : 10,
                "column" : 1
              },
              {
                "line" : 11,
                "column" : 1
              }
            ]
          },
          {
            "name" : "V",
            "qual_name" : [
              "V",
              "Q"
            ]
          },
          [
          ],
          {
          },
          {
            "original_namespace" : {
              "kind" : "Namespace",
              "decl_pointer" : 8,
              "name" : {
                "name" : "V",
                "qual_name" : [
                  "V",
                  "Q"
                ]
              }
            }
          }
        ]],
        ["NamespaceDecl" , [
          {
            "pointer" : 10,
            "source_range" : [
              {
                "line" : 12,
                "column" : 1
              },
              {
                "line" : 14,
                "column" : 1
              }
            ]
          },
          {
            "name" : "I",
            "qual_name" : [
              "I",
              "Q"
            ]
          },
          [
            ["VarDecl" , [
              {
                "pointer" : 11,
                "source_range" : [
                  {
                    "line" : 13,
                    "column" : 1
                  },
                  {
                    "column" : 5
                  }
                ]
              },
              {
                "name" : "i",
                "qual_name" : [
                  "i",
                  "Q"
                ]
              },
              {
                "type_ptr" : 12
              },
              {
                "is_global" : true
              }
            ]]
          ],
          {
          },
          {
            "is_inline" : true
          }
        ]]
      ],
      {
      },
      {
      }
    ]],
    ["NamespaceDecl" , [
      {
        "pointer" : 13,
        "source_range" : [
          {
            "line" : 17,
            "column" : 1
          },
          {
            "line" : 19,
            "column" : 1
          }
        ]
      },
      {
        "name" : "",
        "qual_name" : [
          "anonymous_namespace_tests/namespace_decl.cpp"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["UsingDirectiveDecl" , [
      {
        "pointer" : 14,
        "source_range" : [
          {
            "line" : 17,
            "column" : 11
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "<using-directive>",
        "qual_name" : [
          "<using-directive>"
        ]
      },
      {
        "using_location" : {
          "column" : 11
        },
        "namespace_key_location" : {
        },
        "nested_name_specifier_locs" : [
        ],
        "nominated_namespace" : {
          "kind" : "Namespace",
          "decl_pointer" : 13,
          "name" : {
            "name" : "",
            "qual_name" : [
              "anonymous_namespace_tests/namespace_decl.cpp"
            ]
          }
        }
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 15,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      16,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/namespace_decl.cpp",
    "input_kind" : "IK_CXX",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 12
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 51
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 57
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 65
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 66
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 67
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 68
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 71
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 72
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 73
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 74
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 76
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 78
        },
        {
          "type_ptr" : 17
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 80
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 81
        },
        82
      ]],
      ["PointerType" , [
        {
          "pointer" : 83
        },
        {
          "type_ptr" : 12,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 84
        },
        {
          "type_ptr" : 19,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 85
        },
        {
          "type_ptr" : 19
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 86
        },
        87
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 88
        },
        {
          "element_type" : {
            "type_ptr" : 86
          },
          "stride" : 24
        },
        1
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 89
        },
        {
          "base_type" : 75
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 90
        },
        {
          "type_ptr" : 89
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 91,
          "desugared_type" : 90
        },
        {
          "child_type" : {
            "type_ptr" : 90
          },
          "decl_ptr" : 92
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 16,
          "desugared_type" : 90
        },
        {
          "child_type" : {
            "type_ptr" : 91
          },
          "decl_ptr" : 15
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
