["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "SEL",
        "qual_name" : [
          "SEL"
        ]
      },
      5,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "id",
        "qual_name" : [
          "id"
        ]
      },
      7,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "Class",
        "qual_name" : [
          "Class"
        ]
      },
      9,
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 10,
        "parent_pointer" : 1,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "Protocol",
        "qual_name" : [
          "Protocol"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 11,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 12,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 13,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 14,
        "source_range" : [
          {
            "file" : "tests/FoundationStub.h",
            "line" : 8,
            "column" : 1
          },
          {
            "column" : 13
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "BOOL",
        "qual_name" : [
          "BOOL"
        ]
      },
      15,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 16,
        "source_range" : [
          {
            "line" : 9,
            "column" : 1
          },
          {
            "column" : 22
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "NSUInteger",
        "qual_name" : [
          "NSUInteger"
        ]
      },
      17,
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 18,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 16,
            "column" : 1
          },
          {
            "line" : 27,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSObject",
        "qual_name" : [
          "NSObject"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 19,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 18,
                "column" : 1
              },
              {
                "column" : 22
              }
            ],
            "attributes" : [
              ["NSReturnsRetainedAttr" , [
                {
                  "pointer" : 20,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                }
              ]]
            ]
          },
          {
            "name" : "alloc",
            "qual_name" : [
              "alloc",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "type_ptr" : 21
            },
            "mangled_name" : "+[NSObject alloc]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 22,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 19,
                "column" : 1
              },
              {
                "column" : 20
              }
            ],
            "attributes" : [
              ["NSReturnsRetainedAttr" , [
                {
                  "pointer" : 23,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                }
              ]]
            ]
          },
          {
            "name" : "new",
            "qual_name" : [
              "new",
              "NSObject"
            ]
          },
          {
            "result_type" : {
              "type_ptr" : 21
            },
            "mangled_name" : "+[NSObject new]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 24,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 20,
                "column" : 1
              },
              {
                "column" : 28
              }
            ]
          },
          {
            "name" : "autorelease",
            "qual_name" : [
              "autorelease",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 21
            },
            "mangled_name" : "-[NSObject autorelease]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 25,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 21,
                "column" : 1
              },
              {
                "column" : 21
              }
            ],
            "attributes" : [
              ["NSConsumesSelfAttr" , [
                {
                  "pointer" : 26,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                }
              ]],
              ["NSReturnsRetainedAttr" , [
                {
                  "pointer" : 27,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                }
              ]]
            ]
          },
          {
            "name" : "init",
            "qual_name" : [
              "init",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 21
            },
            "mangled_name" : "-[NSObject init]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 28,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 22,
                "column" : 1
              },
              {
                "column" : 15
              }
            ]
          },
          {
            "name" : "class",
            "qual_name" : [
              "class",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 9
            },
            "mangled_name" : "-[NSObject class]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 29,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 24,
                "column" : 1
              },
              {
                "column" : 34
              }
            ]
          },
          {
            "name" : "respondsToSelector:",
            "qual_name" : [
              "respondsToSelector:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 15
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 30,
                  "source_range" : [
                    {
                      "column" : 29
                    },
                    {
                      "column" : 33
                    }
                  ]
                },
                {
                  "name" : "s",
                  "qual_name" : [
                    "s"
                  ]
                },
                {
                  "type_ptr" : 5
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "mangled_name" : "-[NSObject respondsToSelector:]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 31,
            "parent_pointer" : 18,
            "source_range" : [
              {
                "line" : 25,
                "column" : 1
              },
              {
                "column" : 41
              }
            ]
          },
          {
            "name" : "conformsToProtocol:",
            "qual_name" : [
              "conformsToProtocol:",
              "NSObject"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 15
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 32,
                  "source_range" : [
                    {
                      "column" : 29
                    },
                    {
                      "column" : 40
                    }
                  ]
                },
                {
                  "name" : "p",
                  "qual_name" : [
                    "p"
                  ]
                },
                {
                  "type_ptr" : 33
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "mangled_name" : "-[NSObject conformsToProtocol:]"
          }
        ]]
      ],
      {
      },
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 34,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 29,
            "column" : 1
          },
          {
            "line" : 31,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSNumber",
        "qual_name" : [
          "NSNumber"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 35,
            "parent_pointer" : 34,
            "source_range" : [
              {
                "line" : 30,
                "column" : 1
              },
              {
                "column" : 37
              }
            ]
          },
          {
            "name" : "numberWithInt:",
            "qual_name" : [
              "numberWithInt:",
              "NSNumber"
            ]
          },
          {
            "result_type" : {
              "type_ptr" : 21
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 36,
                  "source_range" : [
                    {
                      "column" : 32
                    },
                    {
                      "column" : 36
                    }
                  ]
                },
                {
                  "name" : "x",
                  "qual_name" : [
                    "x"
                  ]
                },
                {
                  "type_ptr" : 37
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "mangled_name" : "+[NSNumber numberWithInt:]"
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 38,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 33,
            "column" : 1
          },
          {
            "line" : 35,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSString",
        "qual_name" : [
          "NSString"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 39,
            "parent_pointer" : 38,
            "source_range" : [
              {
                "line" : 34,
                "column" : 1
              },
              {
                "column" : 21
              }
            ]
          },
          {
            "name" : "length",
            "qual_name" : [
              "length",
              "NSString"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 17
            },
            "mangled_name" : "-[NSString length]"
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 40,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 37,
            "column" : 1
          },
          {
            "line" : 42,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSDictionary",
        "qual_name" : [
          "NSDictionary"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 41,
            "parent_pointer" : 40,
            "source_range" : [
              {
                "line" : 38,
                "column" : 1
              },
              {
                "line" : 40,
                "column" : 56
              }
            ]
          },
          {
            "name" : "dictionaryWithObjects:forKeys:count:",
            "qual_name" : [
              "dictionaryWithObjects:forKeys:count:",
              "NSDictionary"
            ]
          },
          {
            "result_type" : {
              "type_ptr" : 21
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 42,
                  "source_range" : [
                    {
                      "line" : 38,
                      "column" : 46
                    },
                    {
                      "column" : 51
                    }
                  ]
                },
                {
                  "name" : "objects",
                  "qual_name" : [
                    "objects"
                  ]
                },
                {
                  "type_ptr" : 43
                },
                {
                  "parm_index_in_function" : 0
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : 44,
                  "source_range" : [
                    {
                      "line" : 39,
                      "column" : 46
                    },
                    {
                      "column" : 51
                    }
                  ]
                },
                {
                  "name" : "keys",
                  "qual_name" : [
                    "keys"
                  ]
                },
                {
                  "type_ptr" : 43
                },
                {
                  "parm_index_in_function" : 1
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : 45,
                  "source_range" : [
                    {
                      "line" : 40,
                      "column" : 40
                    },
                    {
                      "column" : 51
                    }
                  ]
                },
                {
                  "name" : "count",
                  "qual_name" : [
                    "count"
                  ]
                },
                {
                  "type_ptr" : 17
                },
                {
                  "parm_index_in_function" : 2
                }
              ]]
            ],
            "mangled_name" : "+[NSDictionary dictionaryWithObjects:forKeys:count:]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 46,
            "parent_pointer" : 40,
            "source_range" : [
              {
                "line" : 41,
                "column" : 1
              },
              {
                "column" : 38
              }
            ]
          },
          {
            "name" : "objectForKeyedSubscript:",
            "qual_name" : [
              "objectForKeyedSubscript:",
              "NSDictionary"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 7
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 47,
                  "source_range" : [
                    {
                      "column" : 32
                    },
                    {
                      "column" : 35
                    }
                  ]
                },
                {
                  "name" : "key",
                  "qual_name" : [
                    "key"
                  ]
                },
                {
                  "type_ptr" : 7
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "mangled_name" : "-[NSDictionary objectForKeyedSubscript:]"
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 48,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 44,
            "column" : 1
          },
          {
            "line" : 47,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSArray",
        "qual_name" : [
          "NSArray"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 49,
            "parent_pointer" : 48,
            "source_range" : [
              {
                "line" : 45,
                "column" : 1
              },
              {
                "column" : 64
              }
            ]
          },
          {
            "name" : "arrayWithObjects:count:",
            "qual_name" : [
              "arrayWithObjects:count:",
              "NSArray"
            ]
          },
          {
            "result_type" : {
              "type_ptr" : 21
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 50,
                  "source_range" : [
                    {
                      "column" : 35
                    },
                    {
                      "column" : 40
                    }
                  ]
                },
                {
                  "name" : "objs",
                  "qual_name" : [
                    "objs"
                  ]
                },
                {
                  "type_ptr" : 51
                },
                {
                  "parm_index_in_function" : 0
                }
              ]],
              ["ParmVarDecl" , [
                {
                  "pointer" : 52,
                  "source_range" : [
                    {
                      "column" : 52
                    },
                    {
                      "column" : 61
                    }
                  ]
                },
                {
                  "name" : "cnt",
                  "qual_name" : [
                    "cnt"
                  ]
                },
                {
                  "type_ptr" : 53
                },
                {
                  "parm_index_in_function" : 1
                }
              ]]
            ],
            "mangled_name" : "+[NSArray arrayWithObjects:count:]"
          }
        ]],
        ["ObjCMethodDecl" , [
          {
            "pointer" : 54,
            "parent_pointer" : 48,
            "source_range" : [
              {
                "line" : 46,
                "column" : 1
              },
              {
                "column" : 49
              }
            ]
          },
          {
            "name" : "objectAtIndexedSubscript:",
            "qual_name" : [
              "objectAtIndexedSubscript:",
              "NSArray"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 7
            },
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 55,
                  "source_range" : [
                    {
                      "column" : 33
                    },
                    {
                      "column" : 44
                    }
                  ]
                },
                {
                  "name" : "index",
                  "qual_name" : [
                    "index"
                  ]
                },
                {
                  "type_ptr" : 17
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ],
            "mangled_name" : "-[NSArray objectAtIndexedSubscript:]"
          }
        ]]
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 56,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 49,
            "column" : 1
          },
          {
            "line" : 50,
            "column" : 2
          }
        ]
      },
      {
        "name" : "NSException",
        "qual_name" : [
          "NSException"
        ]
      },
      [
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        }
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 57,
        "source_range" : [
          {
            "line" : 52,
            "column" : 13
          },
          {
            "column" : 13
          }
        ],
        "is_implicit" : true,
        "attributes" : [
          ["FormatAttr" , [
            {
              "pointer" : 58,
              "source_range" : [
                {
                  "column" : 13
                },
                {
                  "column" : 13
                }
              ]
            }
          ]]
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "type_ptr" : 59
      },
      {
        "is_variadic" : true,
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 60,
              "source_range" : [
                {
                },
                {
                }
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 7
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ]
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 61,
        "source_range" : [
          {
            "column" : 1
          },
          {
            "column" : 34
          }
        ],
        "attributes" : [
          ["FormatAttr" , [
            {
              "pointer" : 62,
              "source_range" : [
                {
                  "column" : 13
                },
                {
                  "column" : 13
                }
              ]
            }
          ]]
        ]
      },
      {
        "name" : "NSLog",
        "qual_name" : [
          "NSLog"
        ]
      },
      {
        "type_ptr" : 59
      },
      {
        "is_variadic" : true,
        "parameters" : [
          ["ParmVarDecl" , [
            {
              "pointer" : 63,
              "source_range" : [
                {
                  "column" : 19
                },
                {
                  "column" : 28
                }
              ]
            },
            {
              "name" : "",
              "qual_name" : [
                ""
              ]
            },
            {
              "type_ptr" : 64
            },
            {
              "parm_index_in_function" : 0
            }
          ]]
        ]
      }
    ]],
    ["RecordDecl" , [
      {
        "pointer" : 65,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "file" : "tests/ObjCBridgeTransferTest.m",
            "line" : 10,
            "column" : 9
          },
          {
            "line" : 11,
            "column" : 1
          }
        ]
      },
      {
        "name" : "ABFDataRef",
        "qual_name" : [
          "ABFDataRef"
        ]
      },
      66,
      [
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 65,
        "is_complete_definition" : true
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 67,
        "source_range" : [
          {
            "line" : 10,
            "column" : 1
          },
          {
            "line" : 11,
            "column" : 3
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "ABFDataRef",
        "qual_name" : [
          "ABFDataRef"
        ]
      },
      68,
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 69,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 13,
            "column" : 1
          },
          {
            "line" : 14,
            "column" : 2
          }
        ]
      },
      {
        "name" : "ABFData",
        "qual_name" : [
          "ABFData"
        ]
      },
      [
      ],
      {
      },
      {
      }
    ]],
    ["FunctionDecl" , [
      {
        "pointer" : 70,
        "source_range" : [
          {
            "line" : 16,
            "column" : 1
          },
          {
            "column" : 27
          }
        ],
        "is_used" : true,
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "ABFDataCreate",
        "qual_name" : [
          "ABFDataCreate"
        ]
      },
      {
        "type_ptr" : 71
      },
      {
      }
    ]],
    ["ObjCInterfaceDecl" , [
      {
        "pointer" : 72,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 18,
            "column" : 1
          },
          {
            "line" : 19,
            "column" : 2
          }
        ]
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      [
      ],
      {
      },
      {
        "super" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 18,
          "name" : {
            "name" : "NSObject",
            "qual_name" : [
              "NSObject"
            ]
          }
        },
        "implementation" : {
          "kind" : "ObjCImplementation",
          "decl_pointer" : 73,
          "name" : {
            "name" : "A",
            "qual_name" : [
              "A"
            ]
          }
        }
      }
    ]],
    ["ObjCImplementationDecl" , [
      {
        "pointer" : 73,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 21,
            "column" : 1
          },
          {
            "line" : 27,
            "column" : 1
          }
        ]
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      [
        ["ObjCMethodDecl" , [
          {
            "pointer" : 74,
            "parent_pointer" : 73,
            "source_range" : [
              {
                "line" : 23,
                "column" : 1
              },
              {
                "line" : 25,
                "column" : 1
              }
            ]
          },
          {
            "name" : "bridge_transfer_example",
            "qual_name" : [
              "bridge_transfer_example",
              "A"
            ]
          },
          {
            "is_instance_method" : true,
            "result_type" : {
              "type_ptr" : 75
            },
            "implicit_parameters" : [
              ["ImplicitParamDecl" , [
                {
                  "pointer" : 76,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "self",
                  "qual_name" : [
                    "self"
                  ]
                },
                {
                  "type_ptr" : 77,
                  "is_const" : true
                },
                {
                }
              ]],
              ["ImplicitParamDecl" , [
                {
                  "pointer" : 78,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ],
                  "is_implicit" : true
                },
                {
                  "name" : "_cmd",
                  "qual_name" : [
                    "_cmd"
                  ]
                },
                {
                  "type_ptr" : 5
                },
                {
                }
              ]]
            ],
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 79,
                "source_range" : [
                  {
                    "line" : 23,
                    "column" : 33
                  },
                  {
                    "line" : 25,
                    "column" : 1
                  }
                ]
              },
              [
                ["DeclStmt" , [
                  {
                    "pointer" : 80,
                    "source_range" : [
                      {
                        "line" : 24,
                        "column" : 3
                      },
                      {
                        "column" : 66
                      }
                    ]
                  },
                  [
                    ["ExprWithCleanups" , [
                      {
                        "pointer" : 81,
                        "source_range" : [
                          {
                            "column" : 23
                          },
                          {
                            "column" : 65
                          }
                        ]
                      },
                      [
                        ["ImplicitCastExpr" , [
                          {
                            "pointer" : 82,
                            "source_range" : [
                              {
                                "column" : 23
                              },
                              {
                                "column" : 65
                              }
                            ]
                          },
                          [
                            ["ObjCBridgedCastExpr" , [
                              {
                                "pointer" : 83,
                                "source_range" : [
                                  {
                                    "column" : 23
                                  },
                                  {
                                    "column" : 65
                                  }
                                ]
                              },
                              [
                                ["CallExpr" , [
                                  {
                                    "pointer" : 84,
                                    "source_range" : [
                                      {
                                        "column" : 51
                                      },
                                      {
                                        "column" : 65
                                      }
                                    ]
                                  },
                                  [
                                    ["ImplicitCastExpr" , [
                                      {
                                        "pointer" : 85,
                                        "source_range" : [
                                          {
                                            "column" : 51
                                          },
                                          {
                                            "column" : 51
                                          }
                                        ]
                                      },
                                      [
                                        ["DeclRefExpr" , [
                                          {
                                            "pointer" : 86,
                                            "source_range" : [
                                              {
                                                "column" : 51
                                              },
                                              {
                                                "column" : 51
                                              }
                                            ]
                                          },
                                          [
                                          ],
                                          {
                                            "qual_type" : {
                                              "type_ptr" : 71
                                            }
                                          },
                                          {
                                            "decl_ref" : {
                                              "kind" : "Function",
                                              "decl_pointer" : 70,
                                              "name" : {
                                                "name" : "ABFDataCreate",
                                                "qual_name" : [
                                                  "ABFDataCreate"
                                                ]
                                              },
                                              "qual_type" : {
                                                "type_ptr" : 71
                                              }
                                            }
                                          }
                                        ]]
                                      ],
                                      {
                                        "qual_type" : {
                                          "type_ptr" : 87
                                        }
                                      },
                                      {
                                        "cast_kind" : "FunctionToPointerDecay",
                                        "base_path" : [
                                        ]
                                      }
                                    ]]
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 88
                                    }
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 89
                                }
                              },
                              {
                                "cast_kind" : "CPointerToObjCPointerCast",
                                "base_path" : [
                                ]
                              },
                              {
                                "type_ptr" : 89
                              },
                              {
                                "cast_kind" : "OBC_BridgeTransfer"
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 89
                            }
                          },
                          {
                            "cast_kind" : "ARCConsumeObject",
                            "base_path" : [
                            ]
                          }
                        ]]
                      ],
                      {
                        "qual_type" : {
                          "type_ptr" : 89
                        }
                      },
                      {
                      }
                    ]]
                  ],
                  [
                    ["VarDecl" , [
                      {
                        "pointer" : 90,
                        "source_range" : [
                          {
                            "column" : 3
                          },
                          {
                            "column" : 65
                          }
                        ]
                      },
                      {
                        "name" : "someData",
                        "qual_name" : [
                          "someData"
                        ]
                      },
                      {
                        "type_ptr" : 89
                      },
                      {
                        "init_expr" : ["ExprWithCleanups" , [
                          {
                            "pointer" : 81,
                            "source_range" : [
                              {
                                "column" : 23
                              },
                              {
                                "column" : 65
                              }
                            ]
                          },
                          [
                            ["ImplicitCastExpr" , [
                              {
                                "pointer" : 82,
                                "source_range" : [
                                  {
                                    "column" : 23
                                  },
                                  {
                                    "column" : 65
                                  }
                                ]
                              },
                              [
                                ["ObjCBridgedCastExpr" , [
                                  {
                                    "pointer" : 83,
                                    "source_range" : [
                                      {
                                        "column" : 23
                                      },
                                      {
                                        "column" : 65
                                      }
                                    ]
                                  },
                                  [
                                    ["CallExpr" , [
                                      {
                                        "pointer" : 84,
                                        "source_range" : [
                                          {
                                            "column" : 51
                                          },
                                          {
                                            "column" : 65
                                          }
                                        ]
                                      },
                                      [
                                        ["ImplicitCastExpr" , [
                                          {
                                            "pointer" : 85,
                                            "source_range" : [
                                              {
                                                "column" : 51
                                              },
                                              {
                                                "column" : 51
                                              }
                                            ]
                                          },
                                          [
                                            ["DeclRefExpr" , [
                                              {
                                                "pointer" : 86,
                                                "source_range" : [
                                                  {
                                                    "column" : 51
                                                  },
                                                  {
                                                    "column" : 51
                                                  }
                                                ]
                                              },
                                              [
                                              ],
                                              {
                                                "qual_type" : {
                                                  "type_ptr" : 71
                                                }
                                              },
                                              {
                                                "decl_ref" : {
                                                  "kind" : "Function",
                                                  "decl_pointer" : 70,
                                                  "name" : {
                                                    "name" : "ABFDataCreate",
                                                    "qual_name" : [
                                                      "ABFDataCreate"
                                                    ]
                                                  },
                                                  "qual_type" : {
                                                    "type_ptr" : 71
                                                  }
                                                }
                                              }
                                            ]]
                                          ],
                                          {
                                            "qual_type" : {
                                              "type_ptr" : 87
                                            }
                                          },
                                          {
                                            "cast_kind" : "FunctionToPointerDecay",
                                            "base_path" : [
                                            ]
                                          }
                                        ]]
                                      ],
                                      {
                                        "qual_type" : {
                                          "type_ptr" : 88
                                        }
                                      }
                                    ]]
                                  ],
                                  {
                                    "qual_type" : {
                                      "type_ptr" : 89
                                    }
                                  },
                                  {
                                    "cast_kind" : "CPointerToObjCPointerCast",
                                    "base_path" : [
                                    ]
                                  },
                                  {
                                    "type_ptr" : 89
                                  },
                                  {
                                    "cast_kind" : "OBC_BridgeTransfer"
                                  }
                                ]]
                              ],
                              {
                                "qual_type" : {
                                  "type_ptr" : 89
                                }
                              },
                              {
                                "cast_kind" : "ARCConsumeObject",
                                "base_path" : [
                                ]
                              }
                            ]]
                          ],
                          {
                            "qual_type" : {
                              "type_ptr" : 89
                            }
                          },
                          {
                          }
                        ]]
                      }
                    ]]
                  ]
                ]]
              ]
            ]],
            "mangled_name" : "-[A bridge_transfer_example]"
          }
        ]]
      ],
      {
      },
      {
        "class_interface" : {
          "kind" : "ObjCInterface",
          "decl_pointer" : 72,
          "name" : {
            "name" : "A",
            "qual_name" : [
              "A"
            ]
          }
        }
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 91,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      21,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/ObjCBridgeTransferTest.m",
    "input_kind" : "IK_ObjC",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "is_objc_arc_on" : true,
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 92
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 93
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 94
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 95
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 96
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 97
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 98
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 99
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 100
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 101
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 102
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 103
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 104
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 105
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 106
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 107
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 108
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 109
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 110
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 111
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 112
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 113
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 114
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 115
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 116
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 117
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 118
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 119
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 120
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 121
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 122
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 123
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 124
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 125
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 126
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 127
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 128
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 129
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 130
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 131
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 132
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 133
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 134
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 135
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 136
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 137
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 138
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 139
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 140
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 141
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 142
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 143
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 144
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 145
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 146
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 147
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 148
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 149
        },
        {
          "type_ptr" : 75
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 150
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 151
        },
        "Half"
      ]],
      ["PointerType" , [
        {
          "pointer" : 152
        },
        {
          "type_ptr" : 148
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 153
        },
        {
          "base_type" : 146
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 154
        },
        {
          "type_ptr" : 153
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 155
        },
        {
          "base_type" : 147
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 156
        },
        {
          "type_ptr" : 155
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 157
        },
        10
      ]],
      ["RecordType" , [
        {
          "pointer" : 158
        },
        159
      ]],
      ["PointerType" , [
        {
          "pointer" : 160
        },
        {
          "type_ptr" : 37,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 161
        },
        {
          "type_ptr" : 93,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 162
        },
        {
          "type_ptr" : 93
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 163
        },
        164
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 165
        },
        {
          "element_type" : {
            "type_ptr" : 163
          },
          "stride" : 24
        },
        1
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 166
        },
        18
      ]],
      ["TypedefType" , [
        {
          "pointer" : 7,
          "desugared_type" : 154
        },
        {
          "child_type" : {
            "type_ptr" : 154
          },
          "decl_ptr" : 6
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 21,
          "desugared_type" : 154
        },
        {
          "child_type" : {
            "type_ptr" : 7
          },
          "decl_ptr" : 91
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 9,
          "desugared_type" : 156
        },
        {
          "child_type" : {
            "type_ptr" : 156
          },
          "decl_ptr" : 8
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 15,
          "desugared_type" : 37
        },
        {
          "child_type" : {
            "type_ptr" : 37
          },
          "decl_ptr" : 14
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 5,
          "desugared_type" : 152
        },
        {
          "child_type" : {
            "type_ptr" : 152
          },
          "decl_ptr" : 4
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 33
        },
        {
          "type_ptr" : 157
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 167
        },
        34
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 168
        },
        38
      ]],
      ["TypedefType" , [
        {
          "pointer" : 17,
          "desugared_type" : 53
        },
        {
          "child_type" : {
            "type_ptr" : 53
          },
          "decl_ptr" : 16
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 169
        },
        40
      ]],
      ["IncompleteArrayType" , [
        {
          "pointer" : 170
        },
        {
          "element_type" : {
            "type_ptr" : 154
          },
          "stride" : 8
        }
      ]],
      ["IncompleteArrayType" , [
        {
          "pointer" : 171
        },
        {
          "element_type" : {
            "type_ptr" : 7,
            "is_const" : true
          },
          "stride" : 8
        }
      ]],
      ["IncompleteArrayType" , [
        {
          "pointer" : 172
        },
        {
          "element_type" : {
            "type_ptr" : 7,
            "is_const" : true
          },
          "stride" : 8
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 173
        },
        {
          "type_ptr" : 154,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 174
        },
        {
          "type_ptr" : 7,
          "is_const" : true
        }
      ]],
      ["DecayedType" , [
        {
          "pointer" : 43,
          "desugared_type" : 174
        },
        {
          "type_ptr" : 174
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 175
        },
        48
      ]],
      ["PointerType" , [
        {
          "pointer" : 176
        },
        {
          "type_ptr" : 154
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 51
        },
        {
          "type_ptr" : 7
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 177
        },
        56
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 64
        },
        {
          "type_ptr" : 168
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 178
        },
        {
          "return_type" : {
            "type_ptr" : 75
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 64
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 179
        },
        {
          "return_type" : {
            "type_ptr" : 75
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 64
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 180
        },
        {
          "return_type" : {
            "type_ptr" : 75
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 154
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 59
        },
        {
          "return_type" : {
            "type_ptr" : 75
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 7
            }
          ]
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 66
        },
        65
      ]],
      ["ElaboratedType" , [
        {
          "pointer" : 181,
          "desugared_type" : 66
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 182
        },
        69
      ]],
      ["TypedefType" , [
        {
          "pointer" : 68,
          "desugared_type" : 66
        },
        {
          "child_type" : {
            "type_ptr" : 181
          },
          "decl_ptr" : 67
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 183
        },
        {
          "type_ptr" : 66
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 88
        },
        {
          "type_ptr" : 68
        }
      ]],
      ["FunctionNoProtoType" , [
        {
          "pointer" : 184
        },
        {
          "return_type" : {
            "type_ptr" : 183
          }
        }
      ]],
      ["FunctionNoProtoType" , [
        {
          "pointer" : 71
        },
        {
          "return_type" : {
            "type_ptr" : 88
          }
        }
      ]],
      ["ObjCInterfaceType" , [
        {
          "pointer" : 185
        },
        72
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 77
        },
        {
          "type_ptr" : 185
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 89
        },
        {
          "type_ptr" : 182
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 186
        },
        {
          "type_ptr" : 184
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 87
        },
        {
          "type_ptr" : 71
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
