["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["ClassTemplateDecl" , [
      {
        "pointer" : 7,
        "source_range" : [
          {
            "file" : "tests/unresolved_lookup.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 12,
            "column" : 1
          }
        ]
      },
      {
        "name" : "S",
        "qual_name" : [
          "S"
        ]
      },
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 8,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      9,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/unresolved_lookup.cpp",
    "input_kind" : "IK_CXX",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 10
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 11
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 12
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 13
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 14
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 15
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 16
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 17
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 18
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 19
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 20
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 21
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 22
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 23
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 24
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 25
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 26
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 27
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 28
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 29
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 30
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 31
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 32
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 33
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 34
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 35
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 36
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 37
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 38
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 39
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 40
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 41
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 42
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 43
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 44
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 45
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 46
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 47
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 48
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 49
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 50
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 51
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 52
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 53
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 54
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 55
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 56
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 57
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 58
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 59
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 60
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 61
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 62
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 63
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 64
        },
        "BuiltinFn"
      ]],
      ["ComplexType" , [
        {
          "pointer" : 65
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 66
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 67
        }
      ]],
      ["ComplexType" , [
        {
          "pointer" : 68
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 69
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 70
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 71
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 72
        },
        {
          "type_ptr" : 10
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 73
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 74
        },
        "Half"
      ]],
      ["RecordType" , [
        {
          "pointer" : 75
        },
        76
      ]],
      ["PointerType" , [
        {
          "pointer" : 77
        },
        {
          "type_ptr" : 15,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 78
        },
        {
          "type_ptr" : 12,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 79
        },
        {
          "type_ptr" : 12
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 80
        },
        81
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 82
        },
        {
          "element_type" : {
            "type_ptr" : 80
          },
          "stride" : 24
        },
        1
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 83
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 84
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 85
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 86
        }
      ]],
      ["InjectedClassNameType" , [
        {
          "pointer" : 87
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 88
        }
      ]],
      ["TemplateTypeParmType" , [
        {
          "pointer" : 89
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 90
        },
        {
          "type_ptr" : 88
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 91
        },
        {
          "type_ptr" : 89
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 92
        },
        {
          "type_ptr" : 87
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 93
        },
        {
          "return_type" : {
            "type_ptr" : 15
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 90
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 94
        },
        {
          "return_type" : {
            "type_ptr" : 15
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 91
            }
          ]
        }
      ]],
      ["TemplateSpecializationType" , [
        {
          "pointer" : 95,
          "desugared_type" : 87
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 96
        },
        {
          "base_type" : 69
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 97
        },
        {
          "type_ptr" : 96
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 98,
          "desugared_type" : 97
        },
        {
          "child_type" : {
            "type_ptr" : 97
          },
          "decl_ptr" : 99
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 9,
          "desugared_type" : 97
        },
        {
          "child_type" : {
            "type_ptr" : 98
          },
          "decl_ptr" : 8
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
