["TranslationUnitDecl" , [
  {
    "pointer" : 1,
    "source_range" : [
      {
      },
      {
      }
    ]
  },
  [
    ["TypedefDecl" , [
      {
        "pointer" : 2,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__int128_t",
        "qual_name" : [
          "__int128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 3,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__uint128_t",
        "qual_name" : [
          "__uint128_t"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 4,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__NSConstantString",
        "qual_name" : [
          "__NSConstantString"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 5,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_ms_va_list",
        "qual_name" : [
          "__builtin_ms_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 6,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "__builtin_va_list",
        "qual_name" : [
          "__builtin_va_list"
        ]
      },
      0,
      {
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 7,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "file" : "tests/virtual_bases.cpp",
            "line" : 7,
            "column" : 1
          },
          {
            "line" : 10,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "A",
        "qual_name" : [
          "A"
        ]
      },
      8,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 9,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 7,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          8,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 10,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 8,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "16649858826465904026",
            "is_cpp" : true,
            "decl_ptr_with_body" : 10,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 12,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 13,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 9,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "6691652126532499765",
            "is_cpp" : true,
            "decl_ptr_with_body" : 13,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 15,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 16,
            "parent_pointer" : 7,
            "source_range" : [
              {
                "line" : 7,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "A",
            "qual_name" : [
              "A",
              "A"
            ]
          },
          {
            "type_ptr" : 17
          },
          {
            "mangled_name" : "6367731417382615745",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 18,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 19
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 20,
            "parent_pointer" : 7,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "A"
            ]
          },
          {
            "type_ptr" : 21
          },
          {
            "mangled_name" : "4916027756641681778",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 22,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 19
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_assignment" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 7,
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 13,
          "name" : {
            "name" : "~A",
            "qual_name" : [
              "~A",
              "A"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 23,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 12,
            "column" : 1
          },
          {
            "line" : 15,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "B",
        "qual_name" : [
          "B"
        ]
      },
      24,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 25,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 12,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          24,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 26,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 13,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "8928078380412315851",
            "is_cpp" : true,
            "decl_ptr_with_body" : 26,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 27,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  28,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 29,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 28
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 10,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "A"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              }
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 30,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 14,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "6627935060446176348",
            "is_cpp" : true,
            "decl_ptr_with_body" : 30,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 31,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 32,
            "parent_pointer" : 23,
            "source_range" : [
              {
                "line" : 12,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "B",
            "qual_name" : [
              "B",
              "B"
            ]
          },
          {
            "type_ptr" : 33
          },
          {
            "mangled_name" : "6925252787601137710",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 34,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 35
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 36,
            "parent_pointer" : 23,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "B"
            ]
          },
          {
            "type_ptr" : 37
          },
          {
            "mangled_name" : "12683202677887858481",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 38,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 35
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_assignment" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 23,
        "is_complete_definition" : true
      },
      {
        "vbases" : [
          28
        ],
        "transitive_vbases" : [
          28
        ],
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 30,
          "name" : {
            "name" : "~B",
            "qual_name" : [
              "~B",
              "B"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 39,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 17,
            "column" : 1
          },
          {
            "line" : 20,
            "column" : 1
          }
        ],
        "is_this_declaration_referenced" : true
      },
      {
        "name" : "C",
        "qual_name" : [
          "C"
        ]
      },
      40,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 41,
            "parent_pointer" : 39,
            "source_range" : [
              {
                "line" : 17,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          40,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 42,
            "parent_pointer" : 39,
            "source_range" : [
              {
                "line" : 18,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "5244587546945854124",
            "is_cpp" : true,
            "decl_ptr_with_body" : 42,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 43,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 44,
            "parent_pointer" : 39,
            "source_range" : [
              {
                "line" : 19,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "is_used" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "~C",
            "qual_name" : [
              "~C",
              "C"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "7422570726995459483",
            "is_cpp" : true,
            "decl_ptr_with_body" : 44,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 45,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 46,
            "parent_pointer" : 39,
            "source_range" : [
              {
                "line" : 17,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "C",
            "qual_name" : [
              "C",
              "C"
            ]
          },
          {
            "type_ptr" : 47
          },
          {
            "mangled_name" : "7407813062435547771",
            "is_cpp" : true,
            "is_inline" : true,
            "is_constexpr" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 48,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 49
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 50,
            "parent_pointer" : 39,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "C"
            ]
          },
          {
            "type_ptr" : 51
          },
          {
            "mangled_name" : "2982129361942595904",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 52,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 49
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_assignment" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 39,
        "is_complete_definition" : true
      },
      {
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 44,
          "name" : {
            "name" : "~C",
            "qual_name" : [
              "~C",
              "C"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["CXXRecordDecl" , [
      {
        "pointer" : 53,
        "parent_pointer" : 1,
        "source_range" : [
          {
            "line" : 22,
            "column" : 1
          },
          {
            "line" : 25,
            "column" : 1
          }
        ]
      },
      {
        "name" : "E",
        "qual_name" : [
          "E"
        ]
      },
      54,
      [
        ["CXXRecordDecl" , [
          {
            "pointer" : 55,
            "parent_pointer" : 53,
            "source_range" : [
              {
                "line" : 22,
                "column" : 1
              },
              {
                "column" : 8
              }
            ],
            "is_implicit" : true,
            "is_this_declaration_referenced" : true,
            "access" : "Public"
          },
          {
            "name" : "E",
            "qual_name" : [
              "E",
              "E"
            ]
          },
          54,
          [
          ],
          {
          },
          "TTK_Struct",
          {
            "definition_ptr" : 0
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 56,
            "parent_pointer" : 53,
            "source_range" : [
              {
                "line" : 23,
                "column" : 3
              },
              {
                "column" : 7
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "E",
            "qual_name" : [
              "E",
              "E"
            ]
          },
          {
            "type_ptr" : 11
          },
          {
            "mangled_name" : "9756747202958380830",
            "is_cpp" : true,
            "decl_ptr_with_body" : 56,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 57,
                "source_range" : [
                  {
                    "column" : 6
                  },
                  {
                    "column" : 7
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
            "cxx_ctor_initializers" : [
              {
                "subject" : ["BaseClass" , [
                  28,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 58,
                    "source_range" : [
                      {
                        "column" : 3
                      },
                      {
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 28
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 10,
                      "name" : {
                        "name" : "A",
                        "qual_name" : [
                          "A",
                          "A"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              },
              {
                "subject" : ["BaseClass" , [
                  59,
                  true
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 60,
                    "source_range" : [
                      {
                      },
                      {
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 59
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 42,
                      "name" : {
                        "name" : "C",
                        "qual_name" : [
                          "C",
                          "C"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              },
              {
                "subject" : ["BaseClass" , [
                  61,
                  false
                ]],
                "source_range" : [
                  {
                  },
                  {
                  }
                ],
                "init_expr" : ["CXXConstructExpr" , [
                  {
                    "pointer" : 62,
                    "source_range" : [
                      {
                      },
                      {
                      }
                    ]
                  },
                  [
                  ],
                  {
                    "qual_type" : {
                      "type_ptr" : 61
                    }
                  },
                  {
                    "decl_ref" : {
                      "kind" : "CXXConstructor",
                      "decl_pointer" : 26,
                      "name" : {
                        "name" : "B",
                        "qual_name" : [
                          "B",
                          "B"
                        ]
                      },
                      "qual_type" : {
                        "type_ptr" : 11
                      }
                    }
                  }
                ]]
              }
            ]
          }
        ]],
        ["CXXDestructorDecl" , [
          {
            "pointer" : 63,
            "parent_pointer" : 53,
            "source_range" : [
              {
                "line" : 24,
                "column" : 3
              },
              {
                "column" : 8
              }
            ],
            "access" : "Public"
          },
          {
            "name" : "~E",
            "qual_name" : [
              "~E",
              "E"
            ]
          },
          {
            "type_ptr" : 14
          },
          {
            "mangled_name" : "4366070428831679553",
            "is_cpp" : true,
            "decl_ptr_with_body" : 63,
            "body" : ["CompoundStmt" , [
              {
                "pointer" : 64,
                "source_range" : [
                  {
                    "column" : 7
                  },
                  {
                    "column" : 8
                  }
                ]
              },
              [
              ]
            ]]
          },
          {
          }
        ]],
        ["CXXConstructorDecl" , [
          {
            "pointer" : 65,
            "parent_pointer" : 53,
            "source_range" : [
              {
                "line" : 22,
                "column" : 8
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "E",
            "qual_name" : [
              "E",
              "E"
            ]
          },
          {
            "type_ptr" : 66
          },
          {
            "mangled_name" : "1943152130981189005",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 67,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 68
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_constructor" : true
          }
        ]],
        ["CXXMethodDecl" , [
          {
            "pointer" : 69,
            "parent_pointer" : 53,
            "source_range" : [
              {
              },
              {
              }
            ],
            "is_implicit" : true,
            "access" : "Public"
          },
          {
            "name" : "operator=",
            "qual_name" : [
              "operator=",
              "E"
            ]
          },
          {
            "type_ptr" : 70
          },
          {
            "mangled_name" : "14000323037812966926",
            "is_cpp" : true,
            "is_inline" : true,
            "parameters" : [
              ["ParmVarDecl" , [
                {
                  "pointer" : 71,
                  "source_range" : [
                    {
                    },
                    {
                    }
                  ]
                },
                {
                  "name" : "",
                  "qual_name" : [
                    ""
                  ]
                },
                {
                  "type_ptr" : 68
                },
                {
                  "parm_index_in_function" : 0
                }
              ]]
            ]
          },
          {
            "is_copy_assignment" : true
          }
        ]]
      ],
      {
      },
      "TTK_Struct",
      {
        "definition_ptr" : 53,
        "is_complete_definition" : true
      },
      {
        "bases" : [
          61
        ],
        "vbases" : [
          59
        ],
        "transitive_vbases" : [
          28,
          59
        ],
        "destructor" : {
          "kind" : "CXXDestructor",
          "decl_pointer" : 63,
          "name" : {
            "name" : "~E",
            "qual_name" : [
              "~E",
              "E"
            ]
          },
          "qual_type" : {
            "type_ptr" : 14
          }
        }
      }
    ]],
    ["TypedefDecl" , [
      {
        "pointer" : 72,
        "source_range" : [
          {
          },
          {
          }
        ],
        "is_implicit" : true
      },
      {
        "name" : "instancetype",
        "qual_name" : [
          "instancetype"
        ]
      },
      73,
      {
      }
    ]]
  ],
  {
  },
  {
    "input_path" : "tests/virtual_bases.cpp",
    "input_kind" : "IK_CXX",
    "integer_type_widths" : {
      "char_type" : 8,
      "short_type" : 16,
      "int_type" : 32,
      "long_type" : 64,
      "longlong_type" : 64
    },
    "types" : [
      ["BuiltinType" , [
        {
          "pointer" : 74
        },
        "Void"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 75
        },
        "Bool"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 76
        },
        "Char_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 77
        },
        "SChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 78
        },
        "Short"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 79
        },
        "Int"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 80
        },
        "Long"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 81
        },
        "LongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 82
        },
        "UChar"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 83
        },
        "UShort"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 84
        },
        "UInt"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 85
        },
        "ULong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 86
        },
        "ULongLong"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 87
        },
        "Float"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 88
        },
        "Double"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 89
        },
        "LongDouble"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 90
        },
        "Float128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 91
        },
        "Ibm128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 92
        },
        "Float16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 93
        },
        "ShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 94
        },
        "Accum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 95
        },
        "LongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 96
        },
        "UShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 97
        },
        "UAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 98
        },
        "ULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 99
        },
        "ShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 100
        },
        "Fract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 101
        },
        "LongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 102
        },
        "UShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 103
        },
        "UFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 104
        },
        "ULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 105
        },
        "SatShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 106
        },
        "SatAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 107
        },
        "SatLongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 108
        },
        "SatUShortAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 109
        },
        "SatUAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 110
        },
        "SatULongAccum"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 111
        },
        "SatShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 112
        },
        "SatFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 113
        },
        "SatLongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 114
        },
        "SatUShortFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 115
        },
        "SatUFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 116
        },
        "SatULongFract"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 117
        },
        "Int128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 118
        },
        "UInt128"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 119
        },
        "WChar_S"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 120
        },
        "Char8"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 121
        },
        "Char16"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 122
        },
        "Char32"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 123
        },
        "Dependent"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 124
        },
        "Overload"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 125
        },
        "BoundMember"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 126
        },
        "PseudoObject"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 127
        },
        "UnknownAny"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 128
        },
        "ARCUnbridgedCast"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 129
        },
        "BuiltinFn"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 130
        },
        "ObjCId"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 131
        },
        "ObjCClass"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 132
        },
        "ObjCSel"
      ]],
      ["PointerType" , [
        {
          "pointer" : 133
        },
        {
          "type_ptr" : 74
        }
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 134
        },
        "NullPtr"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 135
        },
        "Half"
      ]],
      ["BuiltinType" , [
        {
          "pointer" : 136
        },
        "BFloat16"
      ]],
      ["RecordType" , [
        {
          "pointer" : 137
        },
        138
      ]],
      ["PointerType" , [
        {
          "pointer" : 139
        },
        {
          "type_ptr" : 79,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 140
        },
        {
          "type_ptr" : 76,
          "is_const" : true
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 141
        },
        {
          "type_ptr" : 76
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 142
        },
        143
      ]],
      ["ConstantArrayType" , [
        {
          "pointer" : 144
        },
        {
          "element_type" : {
            "type_ptr" : 142
          },
          "stride" : 24
        },
        1
      ]],
      ["RecordType" , [
        {
          "pointer" : 8
        },
        7
      ]],
      ["PointerType" , [
        {
          "pointer" : 145
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 11
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["ElaboratedType" , [
        {
          "pointer" : 28,
          "desugared_type" : 8
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 146
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 14
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 24
        },
        23
      ]],
      ["PointerType" , [
        {
          "pointer" : 147
        },
        {
          "type_ptr" : 24
        }
      ]],
      ["ElaboratedType" , [
        {
          "pointer" : 61,
          "desugared_type" : 24
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 148
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 149
        },
        {
          "type_ptr" : 24,
          "is_const" : true
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 35
        },
        {
          "type_ptr" : 61,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 150
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 149
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 33
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 35
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 151
        },
        {
          "type_ptr" : 8,
          "is_const" : true
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 19
        },
        {
          "type_ptr" : 28,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 152
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 151
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 17
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 153
        },
        {
          "type_ptr" : 24
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 154
        },
        {
          "type_ptr" : 61
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 155
        },
        {
          "return_type" : {
            "type_ptr" : 153
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 149
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 37
        },
        {
          "return_type" : {
            "type_ptr" : 154
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 35
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 156
        },
        {
          "type_ptr" : 8
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 157
        },
        {
          "type_ptr" : 28
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 158
        },
        {
          "return_type" : {
            "type_ptr" : 156
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 151
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 21
        },
        {
          "return_type" : {
            "type_ptr" : 157
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 19
            }
          ]
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 159
        },
        {
          "type_ptr" : 28
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 40
        },
        39
      ]],
      ["PointerType" , [
        {
          "pointer" : 160
        },
        {
          "type_ptr" : 40
        }
      ]],
      ["ElaboratedType" , [
        {
          "pointer" : 59,
          "desugared_type" : 40
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 161
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["RecordType" , [
        {
          "pointer" : 54
        },
        53
      ]],
      ["PointerType" , [
        {
          "pointer" : 162
        },
        {
          "type_ptr" : 54
        }
      ]],
      ["ElaboratedType" , [
        {
          "pointer" : 163,
          "desugared_type" : 54
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 164
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 165
        },
        {
          "type_ptr" : 54,
          "is_const" : true
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 68
        },
        {
          "type_ptr" : 163,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 166
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 165
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 66
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 167
        },
        {
          "type_ptr" : 40,
          "is_const" : true
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 49
        },
        {
          "type_ptr" : 59,
          "is_const" : true
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 168
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 167
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 47
        },
        {
          "return_type" : {
            "type_ptr" : 74
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 49
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 169
        },
        {
          "type_ptr" : 54
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 170
        },
        {
          "type_ptr" : 163
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 171
        },
        {
          "return_type" : {
            "type_ptr" : 169
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 165
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 70
        },
        {
          "return_type" : {
            "type_ptr" : 170
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 68
            }
          ]
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 172
        },
        {
          "type_ptr" : 40
        }
      ]],
      ["LValueReferenceType" , [
        {
          "pointer" : 173
        },
        {
          "type_ptr" : 59
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 174
        },
        {
          "return_type" : {
            "type_ptr" : 172
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 167
            }
          ]
        }
      ]],
      ["FunctionProtoType" , [
        {
          "pointer" : 51
        },
        {
          "return_type" : {
            "type_ptr" : 173
          }
        },
        {
          "params_type" : [
            {
              "type_ptr" : 49
            }
          ]
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 175
        },
        {
          "type_ptr" : 59
        }
      ]],
      ["PointerType" , [
        {
          "pointer" : 176
        },
        {
          "type_ptr" : 61
        }
      ]],
      ["ObjCObjectType" , [
        {
          "pointer" : 177
        },
        {
          "base_type" : 130
        }
      ]],
      ["ObjCObjectPointerType" , [
        {
          "pointer" : 178
        },
        {
          "type_ptr" : 177
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 179,
          "desugared_type" : 178
        },
        {
          "child_type" : {
            "type_ptr" : 178
          },
          "decl_ptr" : 180
        }
      ]],
      ["TypedefType" , [
        {
          "pointer" : 73,
          "desugared_type" : 178
        },
        {
          "child_type" : {
            "type_ptr" : 179
          },
          "decl_ptr" : 72
        }
      ]],
      ["NoneType" , [
        {
          "pointer" : 0
        }
      ]]
    ]
  }
]]
