
all:
	make -C arithmetic
	make -C assertions
	make -C attributes
	make -C custom_error
	make -C initialization
	make -C local_vars
	make -C null_dereference
	make -C resource_leaks
	make -C memory_leaks
	make -C lists
	make -C dangling_deref

clean:
	make -C arithmetic clean
	make -C assertions clean
	make -C custom_error clean
	make -C attributes clean
	make -C initialization clean
	make -C local_vars clean
	make -C null_dereference clean
	make -C resource_leaks clean
	make -C memory_leaks
	make -C lists
	make -C dangling_deref

