#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLANG_WRAPPERS_PATH="${SCRIPT_PATH}/../clang_wrappers"

if [ "${0%++}" != "$0" ]; then INFER_XX="++"; fi
export INFER_XX

FCP_CLANG_COMPILER="${CLANG_WRAPPERS_PATH%/}/filter_args_and_run_fcp_clang$INFER_XX";

if [ -z "$INFER_RESULTS_DIR" ]; then
    # this redirects to the compiler without adding any FCP flag
    # this is because xcode requires message category info from the compiler
    # and invokes it without any env var set.
    "$FCP_CLANG_COMPILER" "$@"
    exit $?
fi

"${CLANG_WRAPPERS_PATH%/}/InferClang" "$@" -fno-cxx-modules
