
prebuilt_jar(
    name = 'hamcrest',
    binary_jar = 'hamcrest-core-1.3.jar',
    visibility = [
        'PUBLIC'
    ]
)

prebuilt_jar(
    name = 'junit',
    binary_jar = 'junit-4.11.jar',
    deps = [
        ':hamcrest'
    ],
    visibility = [
        'PUBLIC'
    ]
)

