alias.c:15:13 call_if_aliased ===> set_both [aliases:Dereference(p)=Dereference(q)]
alias.c:19:3 always_call ===> set_both
alias.c:19:3 always_call [aliases:Dereference(p)=Dereference(q)] ===> set_both [aliases:Dereference(p)=Dereference(q)]
alias.c:23:3 call_depending_on_alias ===> call_if_aliased
alias.c:24:3 call_depending_on_alias ===> always_call
alias.c:24:3 call_depending_on_alias ===> always_call [aliases:Dereference(p)=Dereference(q)]
alias.c:29:3 test_aliased ===> call_depending_on_alias
alias.c:35:3 test_not_aliased ===> call_depending_on_alias
basic.c:6:10 f ===> g
basic.c:6:21 f ===> h
basic.c:6:32 f ===> g
basic.c:6:43 f ===> f
basic.c:11:10 g ===> f
basic.c:11:21 g ===> h
basic.c:11:32 g ===> g
basic.c:16:10 h ===> f
basic.c:16:21 h ===> g
basic.c:16:32 h ===> h
fun_ptr.c:7:40 invoke0 [types:Dereference(g):add] ===> add
fun_ptr.c:7:40 invoke0 [types:Dereference(g):mul] ===> mul
fun_ptr.c:9:40 invoke1 [types:Dereference(g):add] ===> add
fun_ptr.c:9:40 invoke1 [types:Dereference(g):mul] ===> mul
fun_ptr.c:11:62 apply [types:Dereference(f):invoke0] ===> invoke0
fun_ptr.c:11:62 apply [types:Dereference(f):invoke0,Dereference(g):add] ===> invoke0 [types:Dereference(g):add]
fun_ptr.c:11:62 apply [types:Dereference(f):invoke0,Dereference(g):mul] ===> invoke0 [types:Dereference(g):mul]
fun_ptr.c:11:62 apply [types:Dereference(f):invoke1] ===> invoke1
fun_ptr.c:11:62 apply [types:Dereference(f):invoke1,Dereference(g):add] ===> invoke1 [types:Dereference(g):add]
fun_ptr.c:11:62 apply [types:Dereference(f):invoke1,Dereference(g):mul] ===> invoke1 [types:Dereference(g):mul]
fun_ptr.c:13:27 test_add_0 ===> apply [types:Dereference(f):invoke0,Dereference(g):add]
fun_ptr.c:15:27 test_add_1 ===> apply [types:Dereference(f):invoke1,Dereference(g):add]
fun_ptr.c:17:27 test_mul_0 ===> apply [types:Dereference(f):invoke0,Dereference(g):mul]
fun_ptr.c:19:27 test_mul_1 ===> apply [types:Dereference(f):invoke1,Dereference(g):mul]
