box2_test_add_0
┗━━ box2_apply#12
    ┗━━ box2_invoke0#8
        ┗━━ box2_add
box2_test_add_1
┗━━ box2_apply#5
    ┗━━ box2_invoke1#6
        ┗━━ box2_add
box2_test_mul_0
┗━━ box2_apply#10
    ┗━━ box2_invoke0#9
        ┗━━ box2_mul
box2_test_mul_1
┗━━ box2_apply#14
    ┗━━ box2_invoke1#7
        ┗━━ box2_mul
box_test_aliased
┗━━ box_call_depending_on_alias
    ┣━━ box_always_call
    ┃   ┗━━ box_set_both
    ┣━━ box_always_call#3
    ┃   ┗━━ box_set_both#4
    ┗━━ box_call_if_aliased
        ┗━━ box_set_both#4
box_test_not_aliased
┗━━ box_call_depending_on_alias
    ┣━━ box_always_call
    ┃   ┗━━ box_set_both
    ┣━━ box_always_call#3
    ┃   ┗━━ box_set_both#4
    ┗━━ box_call_if_aliased
        ┗━━ box_set_both#4
f
┣━━ f (recursive)
┣━━ g
┃   ┣━━ f (recursive)
┃   ┣━━ g (recursive)
┃   ┗━━ h
┃       ┣━━ f (recursive)
┃       ┣━━ g (recursive)
┃       ┗━━ h (recursive)
┣━━ g
┃   ┣━━ f (recursive)
┃   ┣━━ g (recursive)
┃   ┗━━ h
┃       ┣━━ f (recursive)
┃       ┣━━ g (recursive)
┃       ┗━━ h (recursive)
┗━━ h
    ┣━━ f (recursive)
    ┣━━ g
    ┃   ┣━━ f (recursive)
    ┃   ┣━━ g (recursive)
    ┃   ┗━━ h (recursive)
    ┗━━ h (recursive)
test_add_0
┗━━ apply#18
    ┗━━ invoke0#19
        ┗━━ add
test_add_1
┗━━ apply#23
    ┗━━ invoke1#15
        ┗━━ add
test_aliased
┗━━ call_depending_on_alias
    ┣━━ always_call
    ┃   ┗━━ set_both
    ┣━━ always_call#1
    ┃   ┗━━ set_both#2
    ┗━━ call_if_aliased
        ┗━━ set_both#2
test_mul_0
┗━━ apply#20
    ┗━━ invoke0#21
        ┗━━ mul
test_mul_1
┗━━ apply#24
    ┗━━ invoke1#16
        ┗━━ mul
test_not_aliased
┗━━ call_depending_on_alias
    ┣━━ always_call
    ┃   ┗━━ set_both
    ┣━━ always_call#1
    ┃   ┗━━ set_both#2
    ┗━━ call_if_aliased
        ┗━━ set_both#2
