testBodyFail.doli, line 13, column 4: SIL syntax error: unexpected token #lab3
testComments.doli, parsing succeeded.
testEmpty.doli, parsing succeeded.
testJavaArrays.doli, parsing succeeded.
testJavaConvenience.doli, parsing succeeded.
testJavaGenericInstantiations.doli, parsing succeeded.
testJavaModifiers.doli, parsing succeeded.
testJavaThrows.doli, parsing succeeded.
testJavaThrowsBooleanFail.doli, line 13, column 31: SIL syntax error: unexpected token boolean
testJavaThrowsEmptyFail.doli, line 13, column 30: SIL syntax error: unexpected token under
testObjCJava.doli, parsing succeeded.
