# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

TESTS_DIR = ../../..

CLANG_OPTIONS = -c $(OBJC_CLANG_OPTIONS) $(FOBJC_ARC)
CLEAN_EXTRA = $(wildcard *.o)
INFER_OPTIONS = --biabduction-only --debug-exceptions --project-root $(TESTS_DIR) \
  --biabduction-memleak-buckets $(MEMLEAK_BUCKET)
INFERPRINT_OPTIONS = --issues-tests

include $(TESTS_DIR)/clang.make
include $(TESTS_DIR)/objc.make
