# Copyright (c) 2016 - present Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

ROOT_DIR = ../../../../..
include $(ROOT_DIR)/Makefile.config

ANALYZER = infer

CLEAN_EXTRA =

default: compile

print: analyze
	$(INFERPRINT_BIN) -q -a $(ANALYZER) --issues-tests issues.exp.test
	LC_ALL=C sort -t, -k1,1 -k2,2 -k3n,3 -o issues.exp.test issues.exp.test

test: analyze print
	make clean
	diff -u issues.exp issues.exp.test
	rm issues.exp.test

clean:
	rm -rf *.o infer-out $(CLEAN_EXTRA) duplicates.txt
