codetoanalyze/java/performance-exclusive/ExclusiveTest.java, ExclusiveTest.<init>(), 2,  OnUIThread:false, []
codetoanalyze/java/performance-exclusive/ExclusiveTest.java, ExclusiveTest.call_linear_exclusive_constant(int):void, 3,  OnUIThread:false, []
codetoanalyze/java/performance-exclusive/ExclusiveTest.java, ExclusiveTest.call_linear_exclusive_linear(int):void, 5 + 7 ⋅ x,  OnUIThread:false, [{x},Loop]
codetoanalyze/java/performance-exclusive/ExclusiveTest.java, ExclusiveTest.linear(int):void, 5 + 5 ⋅ x,  OnUIThread:false, [{x},Loop]
