Textual: Type Error: expression &y has type *float, while a subtype of *int was expected in annotated.sil at line 21, column 19
Textual: Type Error: expression &n has type **node, while a pointer of array type was expected in annotated.sil at line 22, column 19
Textual: Type Error: expression &y has type *float, while a subtype of *int was expected in basic.sil at line 17, column 19
Textual: Type Error: expression &n has type **node, while a pointer of array type was expected in basic.sil at line 18, column 19
Textual: Type Error: expression n1 has type int, while a subtype of *node was expected in basic.sil at line 20, column 4
Textual: Type Error: variable u has not been declared in basic.sil at line 35, column 11
Textual: Type Error: expression n0 has type int, while a subtype of float was expected in basic.sil at line 24, column 4
Textual: Type Error: expression &x has type *int, while a supertype of *float was expected in basic.sil at line 24, column 11
Textual: Type Error: expression n1 has type int, while a subtype of float was expected in basic.sil at line 25, column 4
Textual: Type Error: expression &x has type *int, while a pointer of array type was expected in basic.sil at line 25, column 11
Textual: Type Error: expression n3 has type *int[], while a pointer of struct type was expected in basic.sil at line 29, column 4
Textual: Type Error: ident n0 is assigned (with type float), but it has already been assigned at line 17 (with type int) in basic.sil at line 36, column 4
Textual: Type Error: expression n2 has type *int[], while a subtype of *node was expected in basic.sil at line 48, column 4
Textual: Type Error: expression n3 has type *node, while a subtype of *int[] was expected in basic.sil at line 48, column 4
Textual: Type Error: expression &y has type *float, while a supertype of *int was expected in basic.sil at line 52, column 11
Textual: Type Error: expression &y has type *float, while a supertype of *int was expected in basic.sil at line 55, column 11
Textual: Type Error: ident n1 is read before being written in basic.sil at line 75, column 4
Textual: Type Error: expression __sil_pluspi([&ptr:*int], 4) has type *int, while a subtype of *float was expected in basic.sil at line 86, column 8
Textual: Type Error: builtin __sil_allocate is called with 2 arguments while it expects 1 in basic.sil at line 96, column 4
Textual: Type Error: expression 0 has type int, while the type of all types was expected in basic.sil at line 98, column 4
Textual: Type Error: expression n1 has type float, while a subtype of int was expected in basic.sil at line 116, column 4
Textual: Type Error: expression n1 has type float, while a subtype of int was expected in basic.sil at line 118, column 4
Textual: Type Error: expression [&y:float] has type float, while a subtype of int was expected in basic.sil at line 120, column 9
Textual: Type Error: variable b0 has not been declared in basic.sil at line 125, column 16
Textual: Type Error: variable x has not been declared in basic.sil at line 125, column 24
Textual: Type Error: branch at location line 132, column 2 is given the type int, but the other branch is given a different type float in basic.sil at line 132, column 2
Textual: Type Error: expression n0 has type int, while a subtype of float was expected in basic.sil at line 133, column 2
SIL: Consistency Error: function g which can be called with 0 arguments is not declared in error2.sil at line 20, column 9
SIL: Consistency Error: field cell.n is not declared in error2.sil at line 19, column 13
SIL: Consistency Error: label lab2 is not declared in function f in error2.sil at line 16, column 8
SIL: Consistency Error: label lab2 is not declared in function B.f in error_label.sil at line 17, column 8
Textual: Type Error: expression [&f1:(fun () -> void)] has type (fun () -> void), while a subtype of float was expected in fun_type.sil at line 14, column 8
SIL: Consistency Error: node entry is implemented twice in the same function f in twice.sil
SIL: Consistency Error: parameter x is declared twice in the same function f in twice.sil
SIL: Consistency Error: function f is implemented twice in the same file in twice.sil
SIL: Consistency Error: field next is declared twice in type node in twice.sil
SIL: Consistency Error: type node is declared twice in the same file in twice.sil
SIL: Consistency Error: global I is declared twice in the same file in twice.sil
Textual: Type Error: expression n0 has type *HackMixed, while a subtype of bool was expected in type_error_argnum.sil at line 19, column 2
SIL: Consistency Error: variadic parameter is not in second-to-last position in trait function T.with_generics_bad2 which has a reified generics parameter in variadic.sil at line 55, column 7
SIL: Consistency Error: variadic parameter is not in second-to-last position in trait function T.with_generics_bad1 which has a reified generics parameter in variadic.sil at line 50, column 7
SIL: Consistency Error: variadic parameter is not in penultimate position in trait function T.bad in variadic.sil at line 40, column 7
SIL: Consistency Error: variadic parameter is not in penultimate position in function with_generics_bad which has a reified generics parameter in variadic.sil at line 28, column 7
SIL: Consistency Error: variadic parameter is not in last position in function f3 in variadic.sil at line 18, column 7
error1.sil, line 14, column 4: SIL syntax error: unexpected token x
error3.sil, line 4, column 0: SIL syntax error: unexpected token ^
error_lit_float.sil, line 10, column 13: SIL syntax error: unexpected token d
error_lit_int.sil, line 10, column 7: SIL syntax error: unexpected token 9b
error_lit_local.sil, line 10, column 2: SIL syntax error: unexpected token n00b
syntax_error_closure1.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_closure2.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_closure3.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_node_call.sil, line 10, column 15: SIL syntax error: foo.lab
syntax_error_procname1.sil, line 8, column 8: SIL syntax error: ?.bar
syntax_error_procname2.sil, line 8, column 7: SIL syntax error: ?.bar
type_token_clash.sil, line 9, column 2: SIL syntax error: unexpected token n00b
