annotated.sil, line 21, column 19: textual type error: expression &y has type *float, while a subtype of *int was expected
annotated.sil, line 22, column 19: textual type error: expression &n has type **node, while a pointer of array type was expected
basic.sil, line 17, column 19: textual type error: expression &y has type *float, while a subtype of *int was expected
basic.sil, line 18, column 19: textual type error: expression &n has type **node, while a pointer of array type was expected
basic.sil, line 20, column 4: textual type error: expression n1 has type int, while a subtype of *node was expected
basic.sil, line 35, column 11: textual type error: variable u has not been declared
basic.sil, line 36, column 4: textual type error: ident n0 is given the type float, but it has already been given the type int at line 17
basic.sil, line 24, column 4: textual type error: expression n0 has type int, while a subtype of float was expected
basic.sil, line 24, column 11: textual type error: expression &x has type *int, while a supertype of *float was expected
basic.sil, line 25, column 4: textual type error: expression n1 has type int, while a subtype of float was expected
basic.sil, line 25, column 11: textual type error: expression &x has type *int, while a pointer of array type was expected
basic.sil, line 29, column 4: textual type error: expression n3 has type *int[], while a pointer of struct type was expected
basic.sil, line 48, column 4: textual type error: expression n2 has type *int[], while a subtype of *node was expected
basic.sil, line 48, column 4: textual type error: expression n3 has type *node, while a subtype of *int[] was expected
basic.sil, line 52, column 11: textual type error: expression &y has type *float, while a supertype of *int was expected
basic.sil, line 55, column 11: textual type error: expression &y has type *float, while a supertype of *int was expected
basic.sil, line 75, column 4: textual type error: ident n1 is read before being written
basic.sil, line 86, column 4: textual type error: builtin __sil_allocate is called with 2 arguments while it expects 1
basic.sil, line 88, column 4: textual type error: expression 0 has type int, while the type of all types was expected
basic.sil, line 106, column 4: textual type error: expression n1 has type float, while a subtype of int was expected
basic.sil, line 108, column 4: textual type error: expression n1 has type float, while a subtype of int was expected
basic.sil, line 110, column 9: textual type error: expression [&y:float] has type float, while a subtype of int was expected
error1.sil, line 12, column 4: SIL syntax error: unexpected token x
error2.sil, line 19, column 9: SIL consistency error: function g which can be called with 0 arguments is not declared
error2.sil, line 18, column 13: SIL consistency error: field cell.n is not declared
error2.sil, line 15, column 8: SIL consistency error: label lab2 is not declared in function f
error3.sil, line 4, column 0: SIL syntax error: unexpected token ^
error_label.sil, line 16, column 8: SIL consistency error: label lab2 is not declared in function B.f
error_lit_float.sil, line 10, column 13: SIL syntax error: unexpected token d
error_lit_int.sil, line 10, column 7: SIL syntax error: unexpected token 9b
error_lit_local.sil, line 10, column 2: SIL syntax error: unexpected token n00b
syntax_error_closure1.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_closure2.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_closure3.sil, line 15, column 13: SIL syntax error: call inside closure should end with y,z
syntax_error_node_call.sil, line 10, column 15: SIL syntax error: foo.lab
syntax_error_procname1.sil, line 8, column 8: SIL syntax error: ?.bar
syntax_error_procname2.sil, line 8, column 7: SIL syntax error: ?.bar
twice.sil: SIL consistency error: node entry is implemented twice in the same function f
twice.sil: SIL consistency error: parameter x is declared twice in the same function f
twice.sil: SIL consistency error: function f is implemented twice in the same file
twice.sil: SIL consistency error: field next is declared twice in type node
twice.sil: SIL consistency error: type node is declared twice in the same file
twice.sil: SIL consistency error: global I is declared twice in the same file
type_error_argnum.sil, line 19, column 2: textual type error: expression n0 has type *HackMixed, while a subtype of bool was expected
type_token_clash.sil, line 7, column 2: SIL syntax error: unexpected token n00b
variadic.sil, line 55, column 7: SIL consistency error: variadic parameter is not in second-to-last position in trait function T.with_generics_bad2 which has a reified generics parameter
variadic.sil, line 50, column 7: SIL consistency error: variadic parameter is not in second-to-last position in trait function T.with_generics_bad1 which has a reified generics parameter
variadic.sil, line 40, column 7: SIL consistency error: variadic parameter is not in penultimate position in trait function T.bad
variadic.sil, line 28, column 7: SIL consistency error: variadic parameter is not in penultimate position in function with_generics_bad which has a reified generics parameter
variadic.sil, line 18, column 7: SIL consistency error: variadic parameter is not in last position in function f3
