java_library(
    name = 'builtins',
    srcs = glob(['builtins/**/*.java']),
    visibility = [
        'PUBLIC',
    ],
)

java_library(
    name = 'models',
    srcs = glob(['src/**/*.java']),
    visibility = [
        'PUBLIC',
    ],
    deps = [
        ':builtins',
        '//dependencies/java/jackson:jackson',
        '//infer/annotations:annotations',
        '//infer/lib/java/android:android',
    ]
)
