java_test(
    name='integration_tests',
    deps=[
        '//dependencies/java:java_libraries',
        '//infer/tests/endtoend:objc_endtoend_tests',
        '//infer/tests/frontend:objc_frontend_tests',
        '//infer/tests/endtoend/c:infer',
        '//infer/tests/frontend:c_frontend_tests',
        '//infer/tests/endtoend:cpp_endtoend_tests',
        '//infer/tests/frontend:cpp_frontend_tests',
        '//infer/tests/endtoend:objcpp_endtoend_tests',
        '//infer/tests/frontend:objcpp_frontend_tests',
        '//infer/tests/endtoend:java_endtoend_tests',
    ],
    source='7',
    target='7',
)


java_test(
  name='objc_tests',
  deps=[
      '//infer/tests/endtoend:objc_endtoend_tests',
      '//infer/tests/frontend:objc_frontend_tests',
  ],
)

java_test(
    name='c_tests',
    deps=[
        '//infer/tests/endtoend/c:infer',
        '//infer/tests/frontend:c_frontend_tests',
    ],
)

java_test(
    name='cpp_tests',
    deps=[
        '//infer/tests/endtoend:cpp_endtoend_tests',
        '//infer/tests/frontend:cpp_frontend_tests',
    ],
)

java_test(
    name='objcpp_tests',
    deps=[
        '//infer/tests/endtoend:objcpp_endtoend_tests',
        '//infer/tests/frontend:objcpp_frontend_tests',
    ],
)

java_test(
    name='clang_tests',
    deps=[
        '//infer/tests:c_tests',
        '//infer/tests:objc_tests',
        '//infer/tests:cpp_tests',
        '//infer/tests:objcpp_tests',
    ],
)

project_config(
  src_target=':integration_tests',
  src_roots=[ 'src' ],
)
