java_test(
    name='objc_tests',
    deps=[
        '//infer/tests/frontend:objc_frontend_tests',
    ],
)

java_test(
    name='objcpp_tests',
    deps=[
        '//infer/tests/endtoend:objcpp_endtoend_tests',
        '//infer/tests/frontend:objcpp_frontend_tests',
    ],
)

java_test(
    name='clang_tests',
    deps=[
        '//infer/tests:objc_tests',
        '//infer/tests:objcpp_tests',
    ],
)
